### ISSUE TITLE
Kaasautorite näitamine algatuste juures

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#1]
- Ainult algatajale
- Kõigile
Kes kontrollib? Kas algataja määrab, et kõik kaasautorid avalikud? Kas kutsutu saab keelduda? Kuidas?
#10

**Comment by moll** [comment]
https://github.com/rahvaalgatus/rahvaalgatus/issues/6 seotud. Käesolev teema käsitleb kutsutud kaasautorite kuvamist algatajale.

**Comment by moll** [comment]
Vaja ka näha inimese meiliaadressi, kellele kutse saatsin.

**Comment by infokujur** [comment]
Praegu ei ole kaasautoreid mida välja näidata. Kui tekib vajadus, siis tuleb avada uus teema.

**Comment by moll** [comment]
Seotud https://github.com/rahvaalgatus/rahvaalgatus/issues/236.

**Comment by moll** [comment]
https://github.com/rahvaalgatus/rahvaalgatus/issues/236 raames lahendatud. Kaasautori nimi ilmub algatuse juurde kõikjal alles siis, kui kaasautor on kutse vastu võtnud. Enne kutse vastuvõtmist (ja sisselogimist) ei tea me niikuinii uue kaasautor nime. Samuti ei saa nõnda kellegi nime ilma tema soovita algatuste juurde lisada.
