### ISSUE TITLE
Kasutajaprofiilide loogika (Google, FB, ID). Kolm kasutajat mergida üheks vms

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#10]
Kerkinud kasutusloogika probleemid:
1) Kui kutsutakse kasutaja e-mailiga, siis millise kasutaja ta peaks endale looma?
Kui on gmail? Kui on mingi muu mail?
Kuidas seda kasutajale kommunikeerida, mis ta tegema peab?
2) Kuidas kasutajale teada anda, mitu tema nimega kontot üldse on?
3) Kuidas ta neid siduda saab - nii, et logib sisse kuidas meeldib vms?

**Comment by infokujur** [comment]
Erinevate kontode alt praegu ei saa allkirjastada sama inimene. Vaja kas lubada või anda parem juhend süsteemi poolt.

**Comment by moll** [comment]
Kuigi see piirang on vist Citizeni poolel olnud ammu, jõustus see meil 9. mail, kui asendasin enamik anonüümseid API päringuid autenditud päringutega, sest eeldasin, et see ei mõjuta nende käitumist. Tegin allkirjastamisega seotud päringud taas anonüümseks ja nüüd peaks saama taas allkirjastada sõltumata sisselogitud kontost.

**Comment by moll** [comment]
Nüüd on küll selline situatsioon, kus peale allkirjastamist nn teise enda konto alt ei näe enam uuesti algatusele tulles, et oled algatust juba allkirjastanud. Seda Citizeni piirang üritas ilmselt takistada, kuid vaatamata sellele arvan, et piirangu eemaldamine on parem lahendus.

**Comment by infokujur** [comment]
Ootame Citizeni User account joining tulemi ära ja siis kohaneme.
https://docs.google.com/spreadsheets/d/1tOiV6hAtLH4aQYaXm-TR3tK9jMV70tlzSq3lpyZJYp4/edit#gid=0

**Comment by moll** [comment]
Tekkis näiteks küsimus, mis juhtub, kui sisse logida Google kontoga, hääletada Mobiil-Id'ga. Järgmine kord tulles peaksin nägema, et olen hääletanud, eks?  Aga mida siis näen, kui teine kord login sisse Mobiil-Id'ga?

**Comment by moll** [comment]
Kardan, et see on üks neist soovidest, mis nii naljalt tehtuks ei saa.

**Comment by infokujur** [comment]
Sellega on tegeletud.
