### ISSUE TITLE
https://rahvaalgatus.ee/about - Citizen OS teenuse tingimuse lingid vajavad uuendamist

### ISSUE THREAD

**Issue by tiblu** [rahvaalgatus/rahvaalgatus#101]
**Probleem**

https://rahvaalgatus.ee/about lehel olev teenuse tingimuse lingid viitavad tühja.

**Lahendus**

Muuta viited https://citizenos.com/et/topics/7abdd244-d45b-40d3-997c-a6290d4e972c -> https://app.citizenos.com/et/topics/7abdd244-d45b-40d3-997c-a6290d4e972c

**Comment by moll** [comment]
Thx. Aga te peaksite ikka redirectid ka lisama, sest me ei pruugi ju ollas ainus, kes Citizeni teemadele elus linkinud on.

**Comment by tiblu** [comment]
Sul on õigus. Teen hetkel teile PR.

**Comment by moll** [comment]
Sa ei saa kahjuks, sest need tekstid tulevad Google Drive'ist Markdowni failidest ja sealt lähevad tõlketabelisse ja lõpuks skriptiga meile. :P

**Comment by tiblu** [comment]
Ahaa, OK! Aga ma tegin ikkagi. Vähemalt saad diffist vaadata, mis ja kus.

**Comment by tiblu** [comment]
https://github.com/citizenos/citizenos-web/pull/16

**Comment by moll** [comment]
Nagu https://github.com/rahvaalgatus/rahvaalgatus/pull/102 öeldud, aitäh, @tiblu, abi eest, kuid õnneks on probleem tänaseks lahenenud ja vastav tekst tõlgete JSONist kadunud.

> "About" tekst on liikus mingi aeg tagasi Google Spreadsheet tõlketabelist Markdown failidesse, https://github.com/rahvaalgatus/rahvaalgatus/tree/master/locales, kus õnneks vigast linki enam pole.
