### ISSUE TITLE
Palun edastada algatus Riigikogu Kantseleile ja anda mulle menetlusinfo lisamise ligipääs

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#103]
Algatus: Poliitilise dieedi kolm retsepti
https://rahvaalgatus.ee/initiatives/1f821c9e-1b93-4ef5-947f-fe0be45855c5

Riigikogu Kantseleile on esitatud puuduvad hääled paberil. Neid on esialgsel hinnangul nõuetekohaselt (nimi, allkiri ja isikukood) vormistatult ca 1200.

**Comment by moll** [comment]
Ligipääs antud. Häälte saatmist oskab praegu vaid @tiblu teostada. Eeldan, et @infokujur soovib häälte saatmist _otse_ Riigikogule nagu eelmise sarnase case'iga.

**Comment by infokujur** [comment]
Jah. Kui ma ei täpsusta, siis läheb alati sama protsess.
Konteiner otse Riigikogu Kantseleile. Ma küsin seda ainult siis, kui sealt
on kinnitus tulnud, et neil on künnise ületamiseks vajalik häälte arv
juurde toodud teisi kanaleid pidi.

Kontakt Andri Möll (<notifications@github.com>) kirjutas kuupäeval N, 8.
november 2018 kell 11:43:

**Comment by tiblu** [comment]
@infokujur Meil on vaja täpsustada kontaktandmed.

**Comment by tiblu** [comment]
@infokujur Tehtud!
