### ISSUE TITLE
SmartID kasutuselevõtt

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#104]
Ainult alates 8. novembrist Smart-ID registreerunud kasutajad saavad automaatselt kõige kõrgema taseme digiallkirja, mis on seaduse järgi võrdne omakäelise allkirjaga.

Vaja hinnata, kas jooksvate kulude tõusule on olemas piisav rahavoog.

Geenius on siin kirjutanud pikemalt:
https://geenius.ee/uudis/suur-uudis-smart-id-saab-vordseks-omakaelise-allkirja-ja-id-kaardiga/

**Comment by moll** [comment]
Praegu on Smart-Id vist hinna tõttu välja jäänud. Liigutan _issue_ wishlist, et saaksime selleni kunagi tagasi tulla.

**Comment by infokujur** [comment]
Hinnastamise osas tuleb asi läbi mõelda.
Infoks:
"Smart-ID kontod, mis on looduid kuni novembrini 2018 ei saa kunagi omama võimekust digitaalallkirja loomiseks. Seega kui kasutajal on selline konto ja ta soovib ikkagi saada digitaalallkirja võimekust, siis peab ta oma vana konto sulgema, kustutama vana Smart-ID rakenduse, alla laadima uue ja looma uue konto (ehk täiesti uus taotlemise/loomise protsess nullist)."

**Comment by moll** [comment]
Smart-Id laivis. Smart-Id nupp algatuse lehel aga vajaks kõpitsemist (torkab teistega võrreldes silma) ja vajab spinnerit sarnaselt Id-kaardile. Funktsionaalselt aga töötab ja allkiri tundub isegi valideerivat.

Spinneri lisamist käsitlen https://github.com/rahvaalgatus/rahvaalgatus/issues/237.

**Comment by infokujur** [comment]
Ei näe nuppu.

**Comment by moll** [comment]
Jäi siia kirjutamata, et Smart-Id allkirjastamine eksisteerib ja on nähtav vaid neil algatustel, mis kasutavad me uut allkirjastamise meetodit. Uut allkirjastamise meetodit omakorda kasutavad vaid need algatused, mis kogunud üle 1000 allkirja, sest meil oli plaan teha üks ring Riigikoguga enne ära, kui teiste jaoks sisse lülitame. Eilse seisuga oli vaid üks selline algatus aktiivne — https://rahvaalgatus.ee/initiatives/5b0406df-6c5f-479d-b3ea-8a4013d7ef88. Mahetoodete algatus oli ka uuel meetodil, kuid on praeguseks lõppenud.

Täna hommikuse seisuga paistab, et [teadusuuringute algatus](https://rahvaalgatus.ee/initiatives/f1700dae-8a5c-47de-8de8-929f744eff68) on kogunud ka julgelt üle 1000 allkirja. Lülitan tema jaoks ka sisse.
