### ISSUE TITLE
ENG lehel viide next.rahvaalgatus.ee

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#105]
http://help.rahvaalgatus.ee/en
Palun vaata menüü lingid üle, et kõik oleks suunatud ikka peadomeenile.

**Comment by moll** [comment]
Oih, üks link inglise lehel viis tõesti stagingusse. Lisasin ka "Algatused" ja "Platvormist" lingi kõigile keeltele, et päisemenüü oleks põhisaidiga identne.

**Comment by moll** [comment]
Voogi lehel liikumine meenutas taas https://github.com/rahvaalgatus/rahvaalgatus/issues/64 ka.
