### ISSUE TITLE
Lühem variant "platvormist" vene keele jaoks

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#106]
Vene keele fraas "platvormist" on pikavõitu ja kukub järgmisele reale:
![screenshot from 2018-11-14 02-50-06](https://user-images.githubusercontent.com/156837/48456735-02b1b700-e7b8-11e8-866d-8f810e150863.png)

Olgugi, et paremasse serva on tänaseks ehk pisut liiga palju logosid kogunenud, on ehk "platvormist" vene keele jaoks ka lühem variant?

**Comment by infokujur** [comment]
#391
