### ISSUE TITLE
Eemaldada algatuse toetajate valikutest allkirjade allalaadimine

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#107]

**Comment by moll** [comment]
Tehtud https://github.com/rahvaalgatus/rahvaalgatus/issues/54 raames, kuid @infokujur, saad meenutada, miks enda allkirja laadimise eemaldamine hea oli?

**Comment by infokujur** [comment]
Siis inimene näeb, millele ta on allkirja andnud ja see kõik on tõsi. Oma allkirjaga konteinerit on inimesel ka vaba voli igale poole saata - nt kui ei saa lävendit kokku, siis saadab enda allkirjaga pöördumise märgukirjana.

**Comment by moll** [comment]
> Siis inimene näeb, millele ta on allkirja andnud ja see kõik on tõsi. Oma allkirjaga konteinerit on inimesel ka vaba voli igale poole saata - nt kui ei saa lävendit kokku, siis saadab enda allkirjaga pöördumise märgukirjana.

Aga see seletaks rohkem allalaadimislingi _lisamist_, mitte eemaldamist. Eemaldatud lingiga ei näe ta ei seda, mida on allkirjastanud, ega saa seda märgukirjana saata.

**Comment by infokujur** [comment]
Jah - on kaks varianti:
1) Algataja ja allkirjade pakk - võtame lingi ära
2) Allkirjastaja ja tema enda allkiri - see link võib olla, juhul kui ta lubab oma allkirja säilitada ajaloo jaoks.

**Comment by infokujur** [comment]
See link olemas veel.

**Comment by moll** [comment]
Mõtled algataja linki? Selgus täna, et see saadetakse meiliga algatajale tõesti. Tuleks algataja riigikogule saadetud meili saajate seast eemaldada, kas mitte?

**Comment by infokujur** [comment]
Jah. Kui allkirjutanu soovib algatajaga suhelda, siis meil tuleb talt edaspidi konkreetne nõusolek küsida ja siis me saame seda jagada.

**Comment by infokujur** [comment]
Aga allkirjastamise fakti kui sellist, tuleb nõusolekuga suhelda, lahus hoida.

**Comment by moll** [comment]
Uuendus laivis. Allkirjade link ei tohiks meilides enam kajastuda.
