### ISSUE TITLE
Registreerimisel andmete kogumise küsimused

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#109]
> > @infokujur:
> > > Peale sisse logimist on vaja kuvada leht, kust inimene ei saa enne edasi liikuda, kui teeb linnukese (või ka mitu) ja vajutab nõustub. Seal me loeme ette, mida me ta kohta kogume ning teeme ja küsime, kas ta on sellega nõus.

> @moll:
> > See on tehtav, aga kellele? Ainult vanadele kasutajatele? Uute puhul võiks selline info olla registreerimise juures.

@infokujur:
> Jah vanadele. Uutel tuleb uus registreerimine.

Vanade puhul on see lihtsam, sest saame selle RA poolele panna. Registreerimisvormi muutmine on aga suurem ettevõtmine ja selle teostamine tuleks praegu Citizeniga läbi arutada. Kui me just ei taha nende registreerimisfunktsionaalsusest lahti öelda, mis pole ka pisike ettevõtmine.

**Comment by moll** [comment]
@infokujur, saad natuke kirjeldada, mida ja mille alusel me esmasel sisselogimisel küsima peame?

**Comment by infokujur** [comment]
@moll kaardistab andmeid, mida süsteem kogub ja siis me loeme selle nimekirja gruppidena üles koos säilitustähtaegadega.

**Comment by infokujur** [comment]
Andmed on kaardistatud, kui praegune automatiseerimine on lõpule viidud, siis saab ka tekstid vastavusse viia.

**Comment by infokujur** [comment]
jur auditiga tulevad puudused välja
