### ISSUE TITLE
Paremini välja näidata toetan/upvote postitusi

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#11]
Vt siin teemas: https://uuseakus.rahvaalgatus.ee/initiatives/ba7b37cd-a5c8-4950-8265-122b74de2abd
Kas akordionina kokku nt?

**Comment by moll** [comment]
Done and done.
E.g. https://uuseakus.rahvaalgatus.ee/initiatives/ba7b37cd-a5c8-4950-8265-122b74de2abd#comment-dac2db0d-2986-4e20-af61-8c111afc74a1
