### ISSUE TITLE
Mailgun "Concept Pay-As-You-Go" vajab krediitkaarti

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#110]
https://www.mailgun.com/pricing

Concept plaan pakub 10k meili tasuta. Sellest peaks piisama, seega oodatav kulu on null.

Konto ligipääsudetaile jagame mitteavalikult. :)

**Comment by infokujur** [comment]
Olemas, saame vahetada, kui vaja. Palun anna pm märku ja vahetame.
