### ISSUE TITLE
Avalik algatuse API

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#113]

**Comment by jaanusnurmoja** [comment]
Põhimõtteliselt oleks mu praegu soov saada JSON kujul kätte toetusallkirjade hetkearv ning näidata seda oma kahel veebilehel. Nii nagu ma siiani sain selle kätte url-iga https://api.citizenos.com/api/topics/c79c1938-dc37-439e-9e5b-9033c534239b/votes/4cee1670-27bc-415c-8920-a60431ca2094
URL toob andmeid ka praegu, aga need ei uuene, st jäid ühel hetkel 801 allkirja juurde. 

Tänulik oleksin ka võimaluse eest saada andmeid toetusallkirjade arvust kuupäevade lõikes, st kui palju toetusallkirju mingil kuupäeval sellele algatusele anti. 

algatuse id on c79c1938-dc37-439e-9e5b-9033c534239b
vote id on 4cee1670-27bc-415c-8920-a60431ca2094

Siin ka pilt probleemi tõstatamisest Facebookis
![image](https://user-images.githubusercontent.com/1138055/48724948-59ddde80-ec33-11e8-9d59-77f7ae0ecefb.png)

**Comment by moll** [comment]
Hei taas, @jaanusnurmoja.

Lisasin minimaalse vastusega versioneeritud API su kasutusjuhu jaoks üles. Tagastab momendil vaid pealkirja ja häälte arvu JSONis. Kas vajaksid ka muid väljasid?

```
curl https://rahvaalgatus.ee/initiatives/c79c1938-dc37-439e-9e5b-9033c534239b -H "Accept:application/vnd.rahvaalgatus.initiative+json; v=1"
```

Tagasiside teretulnud. HTTP `Accept` päise-põhise versioneerimise idee on garanteerida, et hilisemad uuendused eksisteerivate klientide rakendusi ei lõhu. Sama versiooni raames (hetkel `v=1`) puhul ei muutuks kunagi eksisteerivad väljad. Juurde võib neid siiski tekkida, kuid see ei tohiks midagi lõhkuda.

Häälte arv päevade lõikes peab kahjuks hetkel välja jääma, sest selle läbi saab liigagi lihtsalt seostada inimest ja algatuse toetust. Olgugi, et statistika oleks huvitav, ei oska hetkel öelda, kuidas seda optimaalne privaatsuse vaatenurgast teha oleks. Tuleme selle juurde üks hetk tagasi.

**Comment by jaanusnurmoja** [comment]
Vaatasin veel korra, mida citizenos.com välja annab. Statistika jaoks piisaks vist neist andmetest, userid välja poleks vaja.
`{
id: "30105aed-dff4-46f9-b7d9-ca20f852e055",
object: [
{
@type: "VoteList",
voteId: "4cee1670-27bc-415c-8920-a60431ca2094"
}
],
target: {
id: "c79c1938-dc37-439e-9e5b-9033c534239b",
title: "Tingimusteta põhisissetuleku (kodanikupalga) teostatavuse ja mõju uurimisest Eestis",
status: "voting",,
createdAt: "2018-11-12T09:20:17.121Z",
deletedAt: null
}`

**Comment by moll** [comment]
Hei taas! Andestust tiba hilinenud vastuse eest!

> Iseenesest oleks kena, kui saaks ka viimase allkirjastamise aja :)
> Statistikast - püüan kaasa mõelda. Mis seal õigupoolest praegu kasutaja paljastaks?

Ma ei ole printsiibina vastu ei statistikale ega viimase allkirja ajale, kuid pean/peame natuke veel uurima, kas ja kuidas need läheks vastu privaatsusnõuetele. Mõni algatus saab mõnel perioodil nii vähe hääli, et kui keegi minust kohvikus mööda jalutab, näeb algatust mu ekraanil ja õhtul kodus minutpõhist statsi vaatab, võib julgelt hääle minuga seostada. Viimase allkirjastamise kellaaega tihedamalt jälgides saaks sama statsi ise kokku panna, kuid seda saab teha tegelikult täna ka allkirjade numbrit jälgides. Selles valguses ei mõjutaks viimase allkirja kellaaja avalikustamine rohkem privaatsust kui allkirjade number täna...

**Comment by moll** [comment]
Mõte avalikustada anonümiseeritud andmeid on jätkuvalt õhus, kuid hetkel pole selleks konkreetset plaani. Panen praeguseks _issue_ kinni, kuid sildistan "wishlist" tag-iga, et aeg-ajalt taasavamist kaaluda.

**Comment by infokujur** [comment]
Siin on algus olemas https://rahvaalgatus.ee/api Järjest lisame.
