### ISSUE TITLE
Arutelu tähtajale lisada kellaaeg

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#114]
Arutelu tähtaeg: 22.11.2018 23:59 vms

See on vajalik selleks, et algataja saaks oma meediakampaaniat paremini juhtida. (Mis päeval pressiteade vms)

**Comment by moll** [comment]
Ma ei ole üldse veendunud, kelle jaoks arutelu tähtaeg eksisteerib meie saidil? See ei mängi mingit rolli — peale tähtaega saab sama edukalt edasi kommenteerida kui enne. Hääletusse saates jätkub kommenteerimine ühes arutelu faasi kommentaaridega. Algatuse autor saab enne ja pärast arutelu tähtaegu arutelu sisu muuta. Ainus funktsionaalsus on tal ehk kui avalik signaal, umbes mis hetkel võib-olla keegi algatuse teksti lukku paneb, aga see ei juhtu ju niikuinii sekund peale arutelu tähtaega, sest sekund enne võis uusi kommentaare tulla.

**Comment by infokujur** [comment]
Enne 3 päeva möödumist ei saa hääletama panna. Algatajal on vaja teada, millal ta seda saab teha. Puudub info, et see ei ole mitte 24hx3 vaid 24hx3 + aeg südaööni.

**Comment by moll** [comment]
Lisasin kellaaja muude täiendustega: https://next.rahvaalgatus.ee/initiatives/225c8702-ff5a-45b5-8f20-43ea4ad869b8.
