### ISSUE TITLE
Kirjeldada allkirja hoidmine ja saatmine

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#115]
Nõusoleku mitteandmise jaoks töötame välja häälte _offline_'i viimise ja kustutamise.

**Comment by moll** [comment]
AFAICT Citizeni API ei anna allkirjastaja identifikaatorit partneri rakendusele, et saaksime nõusoleku sellega siduda. Leidsin aga Citizeni sisemisi krüptitud andmeid, mis allkirjastusprotsessi vältel meie rakenduse käest läbi käivad ja mida tänu oma instantsile saame dekrüptida nõusoleku seose soovi täitmiseks.

Ei õnnestunud seda küll eile lõpule viia. Jätkan täna.

**Comment by moll** [comment]
Jälgimise pakkumise jaoks on meil tegelikult https://github.com/rahvaalgatus/rahvaalgatus/issues/108 juba olemas.

**Comment by infokujur** [comment]
Jah - allkirja ja jälgimise seost me ei hoia.
Mingil hetkel tekitame profiili lehe, kus inimene saab oma osalusi vaadata (ja seal siis teavituste tellimise/tellimistest loobumise nupud kõrval).  Selleks teeb päringu ja see ongi vajalik nõusolek. Seni hoiame hääli offline.

**Comment by moll** [comment]
Umm, et ühel lehel oleksime — osalemise fakti säilitamise oli vastu mu eelnev argument. Ainus nn osalemise fakt, mida mu meelest tasub ja tuleb säilitada, on teavituste tellimine. Teavituste tellimise puhul pole eraldi nõusolekut vaja — kogu tellimine ongi nõusolek. Allkirja ega allkirjastamise fakti ma ei tooks kunagi _online_'i tagasi. Seda pole https://github.com/rahvaalgatus/rahvaalgatus/issues/115#issuecomment-447681577 -s kirjeldatud näidetes vaja.

**Comment by infokujur** [comment]
Jah, meil praegu kõik hästi. Teavitused ka pole profiiliga mitte kuidagi seotud.
Samas kui kasutaja tahab, siis ta peab saama oma asjadest ülevaate - nii häältest kui ka teavitustest. Meil on see info vaja väga selgelt kuskil esitleda.
Ehk kui kasutajakonto küljes on epostiaadress, millega on tellitud teavitused siis nendest peab mingi nimekiri kuhugi tekkima või link sellele nimekirjale. Äkki Mailchimp teeb selle kuidagi kergeks?

**Comment by moll** [comment]
Teavitused on nii palju profiiliga seotud, et kui profiilil on valideeritud meiliaadress, saab üpris kindlalt öelda, et tegu on sama inimesega.

>  Samas kui kasutaja tahab, siis ta peab saama oma asjadest ülevaate - nii häältest kui ka teavitustest. Meil on see info vaja väga selgelt kuskil esitleda.

Kui lubame, et kustutame allkirjad nt kuu pärast algatuse edastamist riigikogusse ja ka nii teeme, polegi hiljem võimalik anda ülevaadet antud allkirjadest. Nagu aga ülal kirjutasin, väidan, et see ei tekita praktikas mingeid probleeme, sest teavitused katavad peamise kasutusjuhu ära. Algatuse toimumise vältel saab isikukoodi alusel (ehk sisse logides) aga antud allkirjadest ülevaate anda igal juhul. 

Rahvaalgatuse lehel teavituste haldamine ning jälgitud algatuste tuvastamine (nt algatuste vaates) on aga igati mõistlik. Mailchimp teeb meilide saatmise lihtsamaks, aga haldamise tehniliselt pisut raskemaks — a la praegu on teavitusi lubatud tellida vaid avalike algatuste kohta, sest muidu lekkivad läbi Mailchimpi privaatsete algatuste pealkirjad. Ka on siis vaja sünkida Mailchimpis tehtud muudatusi kohaliku andmebaasiga jms. Kui plaan oli niikuinii tulevikus maksimaalselt teavituste saatmist automatiseerida, ei pruugi Mailchimp enam parim lahendus selleks olla.

**Comment by infokujur** [comment]
Mis pakuksid Mailchimpi asemel? (ja siis arutame ülejäänu teema uuesti lahti)

**Comment by moll** [comment]
Automaatseid teavitusi saatdaksime tõenäoliselt niikuinii läbi transaktsioonilise meiliteenusepakkuja nagu Mailgun (või sarnane, sõltuvalt hinnast). Selliselt saab lahendada ka nii käsitsi koostatud meilide saatmise, olgu need siis sinu poolt (enne kui automaatteavitustele loota saame) või algatajalt (et vältida vajadust algatajale jälgijate e-postiaadresside jagamist, kuid võimaldada neilgi infot jagada).

**Comment by infokujur** [comment]
Avasin automaatsete teavituste jaoks eraldi issue. Arutame seal edasi. https://github.com/rahvaalgatus/rahvaalgatus/issues/125

Häälte hoidmise nõusoleku küsimine on eraldi teema. See ei sõltu sellest, kas inimene on/ei ole teavitusi tellinud.

Meil on vaja küsida:
Kas Sa soovid säilitada oma hääletamiste ajalugu? Kui Jah - siis me kuvame selle inimese kasutajaprofiilis.

**Comment by moll** [comment]
Nad ei ole eraldi teema selles ulatuses, et allkirjade ajaloo hoidmiseks oli eelnevalt üks põhjus — aidata eristada juba allkirjastatud algatusi veel allkirjastamata algatustest algatuse vältel ja pärast. https://github.com/rahvaalgatus/rahvaalgatus/issues/115#issuecomment-447681577 -s kirjeldasin, et esimese eesmärgi saab täidetud ilma nõusolekuta ja teise ainuüksi teavitustele tuginedes. Allkirjade ajalugu ega lisanõusolekut selleks vaja ei ole.

Ehk siis, mis probleemi me allkirjade ajalooga lahendame?

**Comment by moll** [comment]
Kirjeldada ära, mis allkirjaga pärast allkirjastamist toimub (saatmine, hoidmine, anonümiseerimine jm) ja viidata lõigule allkirjastamise juures.

**Comment by moll** [comment]
Praegu on "platvormist" teksti juures järgnev lõik:

> Toetusallkirja andmise jaoks ei ole vaja endale kasutajakontot luua. Toetusallkirja andmisel salvestatakse nimi ja isikukood.  Andmeid töödeldakse üksnes kollektiivse pöördumise esitamiseks ning töötlemine toimub märgukirjale ja selgitustaotlusele vastamise ning kollektiivse pöördumise esitamise seaduse 3. peatüki regulatsiooni alusel.

Kirjutasin esimese mustandi, mis kirjeldab ära allkirjade pikemaajalise hoidmise,  anonüümimise ja korduvallkirjastaja tuvastamise: 

> Toetusallkirja andmisel salvestame allkirjastaja nime, isikukoodi, kellaaja, ligikaudse asukoha ja krüptograafilise allkirja. Soovi korral saad sisselogides allkirja iga hetk alla laadida või kustutada.
>
> Kui algatus on kogunud piisavalt allkirju ning algataja on otsustanud selle Riigikogule või kohalikule omavalitsusele saata, saadame digiallkirjad koos algatuse tekstiga Riigikogu Kantseleile või omavalitsusele. Seal töötleb toetusallkirjade nimekirja vastutav töötaja, kes kontrollib digiallkirjade kehtivust ning kinnitab rahvastikuregistrist, et allkirjad on andnud vähemalt 16-aastased Eesti alalised elanikud. Kohalike omavalitsuste korral kontrollib töötaja lisaks allkirjastajate elukohta.
>
> Kuna iga algatus saab allkirju koguda maksimaalselt 18 kuud, siis hoiame nii kaua ka algatusele antud allkirju. Selle aja täitudes, või ka varem, kui algatus kogub vajalikud allkirjad kiiremini kokku ja jõuab Riigikoguni, eemaldame allkirjadelt isikuandmed — kustutame krüptograafilise allkirja ja eemaldame isikukoodi viimased neli numbrit. Nii jääb järele vaid allkirja kellaaeg, allkirjastaja sugu ja sünnipäev, ligikaudne asukoht ning viide algatusele. Anonüümitud andmete põhjal saame hiljem algatuste käekäigu kohta statistikat väljastada.
>
> Korduvallkirjastajate tuvastamiseks hoiame algatustest eraldi iga allkirjastaja viimase 25 kuu allkirjade kuupäevi. Allkirjastamise kuupäevi eraldi hoides ei ole võimalik tuvastada, millist algatust keegi toetas, küll aga saab tuvastada, kui mitu allkirja keegi viimase 25 kuu jooksul andnud on.

Lõike tuleks kindlasti toimetada ja kogu teksti ühtlustada. Praegu on osa "platvormist" tekstist mina-vormis, osa sina-vormis ja osa ametlikum ja umbisikuline. Eks saab mõelda, kas andmete töötlemise seletused peaksid olema sõbralikud ja maakeeles või ametlikumad ja juriidilisemad.

Kas mul käi midagi välja toomata? Tõin sisse ka lihtsustatud korduvallkirjastajate tuvastamise, mille saab teostada eraldi tabeliga, kuhu jääbki vaid isikukood ja allkirjastamise kuupäev. Nii saab hiljem lugeda, mitu allkirja viimase 25 kuu jooksul keegi on andnud, ilma et peaks säilitama terve 25 kuu allkirju koos viidetega algatustele.

Vaatan, et "Platvormist" teksti lõpus on ka viide CitizenOSile. See tasuks vist nüüd, kus me nende platvormil enam jookse, eemaldada.

**Comment by moll** [comment]
Ootavat nõukogu otsust, kuidas allkirjadega edasi minna.

**Comment by orgkadri** [comment]
Kohendasin ning vastavalt räägitule/kokkulepitule muutsin "Platvormist" teksti. (Lisasin Githubis vastavasse kohta).

**Comment by moll** [comment]
> Toetusallkirja andmise jaoks ei ole vaja endale kasutajakontot luua. Toetusallkirja andmisel salvestatakse allkirjastaja ees- ja perenimi, isikukood, allkirjastamise kellaaeg, ligikaudne asukoht ja krüptograafiline allkiri. Kasutajal on võimalik sisse logida ning oma allkiri koos selle juurde kuuluvate andmetega iga hetk alla laadida või kustutada. 

Tehniliselt lubame siiski alla laadida vaid digiallkirja, mille sees on nimi, isikukood ja kellaaeg. IP aadressi-p]hjal tuletatud ligikaudset asukohta me hetkel ei näita. Peaks?

**Comment by orgkadri** [comment]
Eelneva lahendasime ära (esialgu ei hakka näitama). Lisaks täpsustasin ka allkirja alla laadimise/kustutamise osas teksti. Peaks nüüd olema sobilik laivi minekuks.
