### ISSUE TITLE
Menetlus lõppenud

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#119]
Palun märgi algatuse
"LASKE MEIL HINGATA! KOHTLA-JÄRVE LINNA ELANIKE PÖÖRDUMINE Riigikogu poole" menetlus lõppenuks kuupäevaga -19.11.2018

https://rahvaalgatus.ee/initiatives/c132dd42-2709-4baf-9f2a-b269069e8399

**Comment by moll** [comment]
Tehtud!
