### ISSUE TITLE
Kõik menetluses olevate algatuste vaated on katki

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#12]
Sisse logitud kasutajale annab:
Vabandame, aga midagi meie süsteemis ei toiminud. Proovi palun uuesti. Kui viga kordub, võta ühendust kasutajatoega!

**Comment by moll** [comment]
Citizeni API `/api/users/self/topics/:id/events` endpointi paistis tagastavat `401 Unauthorized`, kui kasutaja, kelle alt päriti, ei olnud algatuse autor. `/api/users/self/topics/:id` endpoint töötab aga sõltumata, kas päriv kasutaja on algatuse autor või mitte. Ootab vastust Citizenilt, kas endpoint käitub soovide kohaselt.

**Comment by moll** [comment]
Issue jäi lahtiseks, kuid probleem sai tollal lahendatud. Citizeni API käitus õigesti ja viga oli Rahvaalgatuse poolne — viimane tegi päringu sisseloginud vaataja puhul küll kasutaja spetsiifilise endpointi vastu, kuid ei saatnud autentimise päist kaasa. Lisasin ka sellekohase automaattesti.
