### ISSUE TITLE
Menetlus lõpetatud järgmistel algatustel:

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#120]
Manifest kõikidele Eestimaa metsadele
22.10.2018
https://rahvaalgatus.ee/initiatives/b5eb835d-9593-4fb2-9583-f841fda6b514

Eesti vajab põlevkivienergeetikast väljumise strateegiat ehk PÕXITit
19.11.2018
https://rahvaalgatus.ee/initiatives/e05abc15-5e49-4205-bfb3-520ed6caf057

Kollektiivne pöördumine “Viia läbi II samba väljamaksete reform: maksimaalne kasu kogutud säästudest"
07.05.2018
https://rahvaalgatus.ee/initiatives/574c7dc7-efe9-42aa-8946-c4c356a36f40

Liiklemine jalgratturitele ohutumaks
23.10.2018
https://rahvaalgatus.ee/initiatives/bba06bbf-5a83-47cc-9709-3c61a4109f7d

Vähendame palgalõhe Meie kõigi võrdse tuleviku nimel
16.10.2018
https://rahvaalgatus.ee/initiatives/4cd98a74-3f69-4369-886f-893e7353a7da
(seda menetlusse ei võetud kollektiivse pöördumisena vaid märgukirjana)

**Comment by moll** [comment]
Määratud "menetletuks". Lõpetuskuupäevad elavad praegu küll vaid siin _issue_'s, kuid varsti saab nende jaoks ka oma välja.
