### ISSUE TITLE
Uuseakus.ra.ee 503

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#122]
https://uuseakus.rahvaalgatus.ee/

**Comment by infokujur** [comment]
Seda lehte on vaja arhiveerimise eesmärgil. Kas seda visuaali oleks võimalik elus hoida seniks, kuni seal on kõikdel allkirjastamine läbi?
Usun, et see juhtub järgmise aasta jooksul - siis saab ka visuaali staatiliseks lasta.

**Comment by infokujur** [comment]
Kas oled siin leidnud võimaluse edasi minna?

**Comment by moll** [comment]
Jaa, juba käsil!

**Comment by moll** [comment]
Asendasin eelmise dünaamilise lehe samasuguse staatilise lehega nagu Kestame'l ja lükkasin https://uuseakus.rahvaalgatus.ee aadressile üles. "Algatuste" viide viitab tagasi Rahvaalgatusse, kuid filtreerib algatused "Uus Eakuse" kategooria järgi. Korrigeerisin pisut Uus Eakuse lähtetekste Google Drive'is, millest sisulehed genereeritakse. Võite neid jätkuvalt muuta, andke vaid teada, mil veebi üles lükata.

Uus Eakuse esilehelt on veel puudu visualisatsioon. Lisan ta varsti staatilisena järele, et tulevased muutused Rahvaalgatuse lehel tedagi ei lõhuks.

**Comment by infokujur** [comment]
Suurepärane, andsin teistele teada, kes tahtsid materjale lugeda :).

**Comment by moll** [comment]
Visualisatsioon ka staatiliselt üleval. Väga hõredaks on teine küll jäänud, sest enamik algatusi on tänaseks lõpetanud allkirjade kogumise. Peaks neid ka ehk kuvama?

**Comment by infokujur** [comment]
Ja - hea tähelepanek. Kuvada praegu as is hallina vms. Kui meie mõjumudel
hakkab kunagi kuju saama, siis võtame arvesse ja märgime neile, mis on
tulemus.

**Comment by moll** [comment]
Tõin kõik algatused nähtavale ja lükkasin staatilise lehe koodi ka eraldi reposse ülesse: https://github.com/rahvaalgatus/uuseakus. Võime sealsetes _issue_-des UE lehe täienduste teemal edasi rääkida.
