### ISSUE TITLE
RK kantseleile hea viis teadete saatmiseks

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#123]
Praegu tuleb info@rahvaalgatus.ee peale teated nt see, et homme on arutelu.
See info ei jõua piisavalt kiiresti meist edasi, kas me saaksime seda kuidagi automatiseerida?
Tn üldlisti on see hea, probleem tekib, siis kui oleks vaja kuhugi konkreetsesse gruppi saata?

@moll

**Comment by moll** [comment]
Saad pisut täpsutada? Milliste arutelude info jõuab info@rahvaalgatuseni täna? Arutelud riigikoguni jõudnud algatuste teemal erinevates ametites, kuhu algatus edasi on saadetud? Või räägime juba suuremast pildist, kuidas rohkem kodanikke kõiksugustesse riigiaruteludesse kaasata?

**Comment by infokujur** [comment]
Ainult see, mis toimub kollektiivsete pöördumistega Riigikogu komisjonides. Ehk Riigikogu API võiks kogu infot sisaldada.

**Comment by infokujur** [comment]
Hakkame API-t integreerima. Sealt edasi ... #20 
Aga saaks ka eraldi kasutaja luua, kui nad ise sisestaksid meie lehele infot. Praegu ekirjade kett endiselt.

**Comment by infokujur** [comment]
See on ka lahenenud.
