### ISSUE TITLE
.md failid siin?

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#124]
Kas meil oli mingi põhjus, miks me need drive panime?
Ma saaks neid siin ka uuendada. Võib-olla oleks segadust isegi vähem. @moll

**Comment by moll** [comment]
Võib siia ka liigutada. Esialgu polnud vist kindel, kuidas pikemate tekstide haldamise lahendame, ja kasutasime Markdowni vaid selleks, et sellest mugavamalt HTMLi tõlketabeli jaoks genereerida.

Alternatiivselt, kuna meil on vist praegu vaid kaks-kolm üpris lühikest Markdowni kirjutist, võime Markdowni ka vahelt jätta ja need otse HTMLi-laadsesse keelde tuua. Umbes nagu mõne #kestame lehega tegime, kus oli rohkem struktuuri kui sisu (https://github.com/rahvaalgatus/kestame/blob/master/content/home.haml#L17).

On sul seisukohti? Tunned Markdownis end kindlamalt? Keegi teine, kes tulevikus kirjutaks, tunneks end ühes või teises kindlamalt?

**Comment by infokujur** [comment]
Vajadus on tekste toimetada ja tõlkida, ma võiks mõlemat uuendada - kuid hea oleks ülevaatuseks ca 3x aastas tekstid tekstiinimesele välja lasta ja siis pärast tagasi tõmmata. Mis siin oleks mõistlik lahendus?

**Comment by tiblu** [comment]
@infokujur @moll 
>  ja tõlkida,

Soovitan vaadata tõlkimise osas Crowdini poole - https://crowdin.com/. Vabavaralistele projektidele tasuta.

**Comment by moll** [comment]
Tõlkimine on seni päris okeilt IMO lahendatud Google Spreadsheetiga (või misiganes tabelarvutusprogrammiga). ML mõtleb siin aga pikemaid sisutekste. Seal juures on Crowdin ja Google Drive relatiivselt identsed, nimelt mõlevad on rakenduse koodi välised ja vajavad kuidagi transformatsiooni HTMLiks. Lihtsam oleks Markdownid siia tuua, kuniks sellest probleem kasvab.

**Comment by moll** [comment]
@infokujur, möödunud aastal ilmus https://drive.google.com/drive/u/0/folders/0Bzyw2X6-AWxmMW9YaVBnbTczVTA?ths=true kausta `about_EST.md` kõrvale ka `about_EST_13_04_2018.md` (sama teiste keelte kohta). Oskad öelda, kumb neist värske on? 

Võrreldes on neil järgnevad erinevused (punane `<` märgistega on `about_EST.md`):

```diff
1c1
< # Rahvaalgatus.ee platvormist
---
> # Rahvaalgatus.ee platvormist
3,6c3,6
< Rahvaalgatus.ee on arutelude pidamise ja ettepanekute koostamise platvorm, mille kaudu saab Riigikogule kollektiivseid pöördumisi (ehk algatusi) esitada. Rahvaalgatus.ee võimaldab igaühel teha ettepaneku, kuidas ühiskonnaelu parandada või mõnda seadust muuta. Pärast ettepaneku kirjapanemist saab kutsuda teisi kaasa arutlema, arutelu tulemusel pöördumise (ehk algatuse) ühiselt koostada, vähemalt 16aastastelt Eesti elanikelt digiallkirju koguda ning pöördumine ühe klikiga Riigikogule esitada. Platvormis saab jälgida, mida parlamendi komisjon(id) ettepaneku kohta arvavad ja selle võimalikku seaduseelnõuks kujunemist.
<  
< Rahvaalgatus.ee võimaldab mugavalt ja läbipaistvalt kasutada õigust esitada Riigikogule kollektiivseid pöördumisi. Nimelt uuendati Rahvakogu ettepanekute tulemusel 2014. aasta kevadel Riigikogu töö- ja kodukorra seadust, mille kohaselt Riigikogu peab menetlema vähemalt 1000 allkirjaga pöördumist, mis on tehtud kehtiva regulatsiooni muutmiseks või ühiskonnaelu paremaks korraldamiseks. Seisuga veebruar 2016 on parlamendile esitatud 12 pöördumist, neist kaks on ka seaduseks saanud.
<  
---
> Rahvaalgatus.ee on arutelude pidamise ja ettepanekute koostamise platvorm, mille kaudu saab Riigikogule kollektiivseid pöördumisi (ehk algatusi) esitada. Rahvaalgatus.ee võimaldab igaühel teha ettepaneku, kuidas ühiskonnaelu parandada või mõnda seadust muuta. Pärast ettepaneku kirjapanemist saab kutsuda teisi kaasa arutlema, arutelu tulemusel pöördumise (ehk algatuse) ühiselt koostada, vähemalt 16aastastelt Eesti elanikelt digiallkirju koguda ning pöördumine ühe klikiga Riigikogule esitada. Platvormis saab jälgida, mida parlamendi komisjon(id) ettepaneku kohta arvavad ja selle võimalikku seaduseelnõuks kujunemist.
>  
> Rahvaalgatus.ee võimaldab mugavalt ja läbipaistvalt kasutada õigust esitada Riigikogule kollektiivseid pöördumisi. Nimelt uuendati Rahvakogu ettepanekute tulemusel 2014. aasta kevadel Riigikogu töö- ja kodukorra seadust, mille kohaselt Riigikogu peab menetlema vähemalt 1000 allkirjaga pöördumist, mis on tehtud kehtiva regulatsiooni muutmiseks või ühiskonnaelu paremaks korraldamiseks. Seisuga märts 2018 on parlamendile esitatud 16 pöördumist, neist kaks on ka seaduseks saanud.
>  
8,13c8,13
< 
< - ühiskonnaasjadest huvitatud kodanikele arutelude loomiseks ja ettepanekute esitamiseks
< - huvikaitse- ja katusorganisatsioonidele arutelude loomiseks ja ettepanekute esitamiseks
< - huvitatud kodanikele aruteludes osalemiseks ja pöördumiste ühisloomes koostamiseks
< - pöördumiste toetajatele digiallkirja andmiseks
<  
---
> 
> - ühiskonnaasjadest huvitatud kodanikele arutelude loomiseks ja ettepanekute esitamiseks
> - huvikaitse- ja katusorganisatsioonidele arutelude loomiseks ja ettepanekute esitamiseks
> - huvitatud kodanikele aruteludes osalemiseks ja pöördumiste ühisloomes koostamiseks
> - pöördumiste toetajatele digiallkirja andmiseks
>  
15,30c15,28
< 
< - Riigikogu saadikud ja teised poliitikud, et olla kursis, milliseid arutelusid kodanikud tõstatavad
< - ministeeriumide esindajad, et olla kursis valdkondlike ettepanekutega
< - ajakirjanikud, et noppida üles avalikku tähelepanu pälvivad arutelud ja pöördumised, jälgida pöördumiste saatust 
<  
< Rahvaalgatus.ee platvormi on püsti pannud ja seda haldab SA Eesti Koostöö Kogu tihedas koostöös Riigikogu Kantseleiga.
< Rahvaalgatus.ee on ehitatud sihtasutuse Teeme Ära! loodud kogukondliku otsustamise vabavara CitizenOS.com-i peale. Rahvaalgatusveeb on ka riikliku kohustusena Riigikantselei kureeritavas avatud valitsemise partnerluse tegevuskavas 2014-2016.
< 
< 
< # <a id="tos"></a> Rahvaalgatus.ee kasutamise hea tava
< Rahvaalgatus.ee kaudu saab Riigikogule koostada kollektiivseid pöördumisi (algatusi) ühiskonnaelu paremaks korraldamiseks või seaduste muutmiseks. 
< 
< 
< Platvormi kasutamise hea tava on koostatud uskumuses, et argumenteeritud arutelud aitavad luua häid algatusi, mis omakorda parandada elu Eestis. 
< 
< 
---
> 
> - Riigikogu saadikud ja teised poliitikud, et olla kursis, milliseid arutelusid kodanikud tõstatavad
> - ministeeriumide esindajad, et olla kursis valdkondlike ettepanekutega
> - ajakirjanikud, et noppida üles avalikku tähelepanu pälvivad arutelud ja pöördumised, jälgida pöördumiste saatust 
>  
> Rahvaalgatus.ee platvormi on püsti pannud ja seda haldab SA Eesti Koostöö Kogu tihedas koostöös Riigikogu Kantseleiga.
> Rahvaalgatus.ee on ehitatud sihtasutuse Teeme Ära! loodud kogukondliku otsustamise vabavara CitizenOS.com-i peale. Rahvaalgatusveeb on ka riikliku kohustusena Riigikantselei kureeritavas avatud valitsemise partnerluse tegevuskavas 2016-2018.
> 
> 
> # <a id="tos"></a> Rahvaalgatus.ee kasutamise hea tava
> Rahvaalgatus.ee kaudu saab Riigikogule koostada kollektiivseid pöördumisi (algatusi) ühiskonnaelu paremaks korraldamiseks või seaduste muutmiseks. 
> 
> Platvormi kasutamise hea tava on koostatud uskumuses, et argumenteeritud arutelud aitavad luua häid algatusi, mis omakorda parandada elu Eestis. 
> 
32,74c30,58
< 
< 1. minu ettepanek või algatus on kooskõlas Eesti Vabariigi põhiseaduse aluspõhimõtetega;  
< 2. pakutud lahendus peab olema tõestatud ning tõestus omakorda kontrollitav; 
< 3. ettepaneku või algatuse sisestamisel pakun ka struktureeritud selgitusi, et niimoodi kaasamõtlejaid ja arutajaid juurde meelitada; 
< 4. olen veendunud, et Riigikogu on minu ettepaneku õige adressaat;
< 5. kritiseerin ideid, mitte inimesi. Kriitikas keskendun lahendustele, mitte probleemidele; 
< 6. kaasan teisi inimesi arutellu ja arvestan nende argumentidega lõpliku pöördumise (algatuse) koostamisel; 
< 7. kasutan platvormi juhul, kui mul puuduvad teised kanalid ettepanekute ja seadusemuudatuste esitamiseks. 
< 
< 
< Rahvaalgatus.ee-s pole seega teretulnud vihakõne ega muud solvavad ütlemised, samamoodi pole see platvorm loodud parlamendis esindatud erakondadele. 
<  
< Rahvaalgatus.ee-d haldaval Eesti Koostöö Kogul on õigus eemaldada hea tava vastu eksivad postitused (vihakõne, isiklikud solvamised jms) ilma põhjendusteta. 
< 
< 
< Kui vajad nõu või kahtled, kas rahvaalgatus.ee on sobiv koht oma ettepaneku esitamiseks, küsi abi info@rahvaalgatus.ee.  
< 
< 
< 
< 
< ## Isikuandmete töötlemine 
<  
< Isikuandmed on [rahvaalgatus.ee](http://rahvaalgatus.ee/) platvormil sisestatud kasutaja kohta käivad andmed. Rahvaalgatus.ee kasutaja annab platvormi haldajale õiguse tema poolt sisestatud isikuandmete töötlemiseks. Juhul kui kasutaja soovib [rahvaalgatus.ee](http://rahvaalgatus.ee/) poolt isikuandmete töötlemise lõpetamist, võimaldab [rahvaalgatus.ee](http://rahvaalgatus.ee/) kasutajal oma kasutajakonto ja kõik sinna juurde kuuluvad andmed kustutada.
< 
< 
< Kasutajakonto on vaja luua algatuse loomiseks ja kommentaaride andmiseks. Kasutajakontode haldamiseks kasutame CitizenOS API (omanik Teeme ära SA) teenust. CitizenOS API teenuse tingimused on avalikult üleval [siin](https://citizenos.com/et/topics/7abdd244-d45b-40d3-997c-a6290d4e972c).
< 
< 
< 
<   
< Kasutajakonto on vaja luua algatuse loomiseks ja kommentaaride andmiseks. Kasutajakontode haldamiseks kasutame CitizenOS API (omanik Teeme ära SA) teenust. CitizenOS API teenuse tingimused on avalikult üleval [siin](https://citizenos.com/et/topics/7abdd244-d45b-40d3-997c-a6290d4e972c).
< 
< Toetusallkirja andmise jaoks ei ole vaja endale kasutajakontot luua. Toetusallkirja andmisel salvestatakse nimi ja isikukood.  Andmeid töödeldakse üksnes kollektiivse pöördumise esitamiseks ning töötlemine toimub märgukirjale ja selgitustaotlusele vastamise ning kollektiivse pöördumise esitamise seaduse 3. peatüki regulatsiooni alusel.
< 
< Toetusallkirja andnute nimekiri on nähtav algatuse autori(te)le pärast hääletusaja lõppemist, mil autorkond saab alla laadida digiallkirjadega konteineri ja Riigikogu Kantselei vastutavale töötajale, kes kontrollib rahvastikuregistrist, et digiallkirjad on andnud vähemalt 16 aastased Eesti alalised elanikud.
< 
< Andmeid hoitakse konfidentsiaalsena ning kõiki isikuid, kellel on õigus isikandmeid töödelda, on teavitatud isikuandmete konfidentsiaalsest olemusest. Toetusallkirja andjaid  [rahvaalgatus.ee](http://rahvaalgatus.ee/)  avalikult ei kuva,  kuid selline tehniline arendus on avatuse nimel plaanis. Kui tehniline arendus valmib, siis tagasiulatuvalt seda ei rakendata ning kasutajal on võimalik ise määrata, kas ta toetus on avalik või mitte.
< 
< Kui isik leiab, et tema õigusi on põhjendamatult piiratud või rikutud, on tal õigus pöörduda Andmekaitse Inspektsiooni või kohtusse.
< 
< Teavitame rikkumisest Andmekaitse Inspektsiooni põhjendamatu viivituseta ja võimaluse korral 72 tunni jooksul pärast rikkumisest teadasaamist, v.a juhul, kui rikkumine ei kujuta endast tõenäoliselt suur ohtu füüsilise isiku õigustele ja vabadustele. Suure ohu korral andmesubjekti õigustele ja vabadustele teavitame andmesubjekti, et tal oleks võimalik kohe vajalikud meetmed võtta.
< 
< 
---
> 
> 1. minu ettepanek või algatus on kooskõlas Eesti Vabariigi põhiseaduse aluspõhimõtetega;  
> 2. pakutud lahendus peab olema tõestatud ning tõestus omakorda kontrollitav; 
> 3. ettepaneku või algatuse sisestamisel pakun ka struktureeritud selgitusi, et niimoodi kaasamõtlejaid ja arutajaid juurde meelitada; 
> 4. olen veendunud, et Riigikogu on minu ettepaneku õige adressaat;
> 5. kritiseerin ideid, mitte inimesi. Kriitikas keskendun lahendustele, mitte probleemidele; 
> 6. kaasan teisi inimesi arutellu ja arvestan nende argumentidega lõpliku pöördumise (algatuse) koostamisel; 
> 7. kasutan platvormi juhul, kui mul puuduvad teised kanalid ettepanekute ja seadusemuudatuste esitamiseks. 
> 
> Rahvaalgatus.ee-s pole seega teretulnud vihakõne ega muud solvavad ütlemised, samamoodi pole see platvorm loodud parlamendis esindatud erakondadele. 
>  
> Rahvaalgatus.ee-d haldaval Eesti Koostöö Kogul on õigus eemaldada hea tava vastu eksivad postitused (vihakõne, isiklikud solvamised jms) ilma põhjendusteta. 
> 
> Kui vajad nõu või kahtled, kas rahvaalgatus.ee on sobiv koht oma ettepaneku esitamiseks, küsi abi info@rahvaalgatus.ee.  
> 
> 
> ## Isikuandmete töötlemine 
>  
> Isikuandmed on rahvaalgatus.ee platvormil sisestatud kasutaja kohta käivad andmed. Rahvaalgatus.ee kasutaja annab platvormi haldajale õiguse tema poolt sisestatud isikuandmete avalikustamiseks, töötlemiseks ja säilitamiseks. Juhul kui kasutaja soovib rahvaalgatus.ee poolt isikuandmete avalikustamise, töötlemise ja säilitamise lõpetamist, võimaldab rahvaalgatus.ee kasutajal oma kasutajakonto ja kõik sinna juurde kuuluvad andmed kustutada.
> 
> Kasutajakonto on vaja luua algatuse loomiseks ja kommentaaride andmiseks.
> Kasutajakontode haldamiseks kasutame CitizenOS API (omanik Teeme ära SA) teenust. CitizenOS API teenuse tingimused on avalikult üleval [siin](https://citizenos.com/et/topics/7abdd244-d45b-40d3-997c-a6290d4e972c).
> 
> Toetusallkirja andmise jaoks ei ole vaja endale kasutajakontot luua.
> Toetusallkirja andmisel salvestatakse nimi ja isikukood.
> Toetusallkirja andnute nimekiri on nähtav algatuse autori(te)le pärast hääletusaja lõppemist, mil autorkond saab alla laadida digiallkirjadega konteineri ja Riigikogu Kantselei vastutavale töötajale, kes kontrollib, et digiallkirjad on andnud vähemalt 16 aastased Eesti alalised elanikud.
> 
> Toetusallkirja andjaid rahvaalgatus.ee avalikult veel ei kuva, kuigi selline tehniline arendus on avatuse nimel plaanis. Kui tehniline arendus valmib, siis tagasiulatuvalt seda ei rakendata ning kasutajal on võimalik ise määrata, kas ta toetus on avalik või mitte.
> 
76,83c60,63
< 
< - kollektiivsete pöördumiste esitamisest [Riigikogu kodulehel](https://www.riigikogu.ee/tutvustus-ja-ajalugu/raakige-kaasa/esitage-kollektiivne-poordumine/)
< - Riigikogule alates 2014. aastast esitatud [kollektiivsed pöördumised](https://www.riigikogu.ee/tutvustus-ja-ajalugu/raakige-kaasa/esitage-kollektiivne-poordumine/riigikogule-esitatud-kollektiivsed-poordumised/) 
< - arutamise, otsustamise ja otsuste digiallkirjastamise platvorm CitizenOS.com (mille peale rahvaalgatus.ee on ehitatud)
< <!--stackedit_data:
< eyJoaXN0b3J5IjpbLTM0MjM2NzgzNSwtODU5NDg1MDc0LDI0ND
< MyNjI1OCwxNDg5NDUzMjQ5LC0xNTI0Mjg2NDc0XX0=
< -->
\ No newline at end of file
---
> 
> - kollektiivsete pöördumiste esitamisest [Riigikogu kodulehel](https://www.riigikogu.ee/tutvustus-ja-ajalugu/raakige-kaasa/esitage-kollektiivne-poordumine/)
> - Riigikogule alates 2014. aastast esitatud [kollektiivsed pöördumised](https://www.riigikogu.ee/tutvustus-ja-ajalugu/raakige-kaasa/esitage-kollektiivne-poordumine/riigikogule-esitatud-kollektiivsed-poordumised/) 
> - arutamise, otsustamise ja otsuste digiallkirjastamise platvorm CitizenOS.com (mille peale rahvaalgatus.ee on ehitatud)
\ No newline at end of file
```

**Comment by moll** [comment]
Toetamise/annetusega seotud Markdown failid asuvad https://github.com/rahvaalgatus/rahvaalgatus/tree/master/locales. Tahaks siis ka "Platvormist" tekstid sinna viia.

**Comment by infokujur** [comment]
@moll - punane on õige/praegune versioon.

**Comment by moll** [comment]
@infokujur, igaks juhuks küsin ka inglisekeelse Markdowni kohta. Punane `<` tähisega on `about_ENG.md` ja teine `about_ENG_13_04_2018.md`:

```patch
4c4
< Collective petitioning right emerged from the People’s Assembly process – since 2014 spring every citizen can send collective initiatives to the Parliament for consideration. According to the law (), the Parliament will have to process appeals that have at least 1000 signatures. During the period from spring 2014 until beginning of 2016, the Parliament has processed 12 collective initiatives (link in Estonian) and two of them have been made into laws.
---
> Collective petitioning right emerged from the People’s Assembly process – since 2014 spring every citizen can send collective initiatives to the Parliament for consideration. According to the law (), the Parliament will have to process appeals that have at least 1000 signatures. During the period from spring 2014 until beginning of 2018, the Parliament has processed 16 collective initiatives (link in Estonian) and two of them have been made into laws.
19c19
< Rahvaalgatus.ee portal will be created by the Estonian Cooperation Assembly in close cooperation with the Chancellery of the Riigikogu. The portal is created on the freeware for community decision-making — CitizenOS.com — which is set up by the foundation Lets Do It! The citizen initiative portal is one of the activities in the Estonian Action Plan 2014-2016 of the Open Government Partnership.
---
> Rahvaalgatus.ee portal will be created by the Estonian Cooperation Assembly in close cooperation with the Chancellery of the Riigikogu. The portal is created on the freeware for community decision-making — CitizenOS.com — which is set up by the foundation Lets Do It! The citizen initiative portal is one of the activities in the Estonian Action Plan 2016-2018 of the Open Government Partnership.
```

Näen, et "2018" versioon kirjeldab 4 aasta käekäiku, `about_ENG.md` aga vaid kahe aasta käiku:

> During the period from spring 2014 until beginning of 2016, the Parliament has processed 12 collective initiatives (link in Estonian) and two of them have been made into laws.

versus

> During the period from spring 2014 until beginning of 2018, the Parliament has processed 16 collective initiatives (link in Estonian) and two of them have been made into laws.

Kas selle põhjal võib öelda, et "2018" versioon on värskem? Sama nüanss on siiski aga ka eestikeelse versiooniga, kus `about_EST.md` kirjeldab kahte aastat, `about_EST_13_04_2018.md` aga nelja:

 > Seisuga veebruar 2016 on parlamendile esitatud 12 pöördumist, neist kaks on ka seaduseks saanud.

> Seisuga märts 2018 on parlamendile esitatud 16 pöördumist, neist kaks on ka seaduseks saanud.

Õppetund tulevikuks: käsitsi versioneeritud failid ja vanade versioonide alles jätmine tekitab hilisemat segadust. :)

**Comment by moll** [comment]
Leidsin vana meili (tsitaat all), mis inglise ja vene keele ülemisele küsimusele vastab. Eesti keele `about_EST.md` 2-aasta kirjeldus vs 4-aasta ajalugu on siiski aga kummaline.

**Comment by infokujur** [comment]
Palun võrdle nende versioonidega, mis siin on üleval: https://rahvaalgatus.ee/about
Need on õiged versioonid.

**Comment by moll** [comment]
Laivis on inglise ja vene keelsed tekstid pärit `*_13_04_2018.md` failidest, eesti oma aga `about_EST.md` failist. Lahtine on seega vaid eesti keele tekst.

Kopeerisin kaks lauset, mis viitasid 2016–2018 aastatele 2018. eesti keele failist. Nõnda jääb peamiseks erinevuseks isikuandmete töötlemise sektsioon.

`about_EST.md`:

> ## Isikuandmete töötlemine 
>  
> Isikuandmed on [rahvaalgatus.ee](http://rahvaalgatus.ee/) platvormil sisestatud kasutaja kohta käivad andmed. Rahvaalgatus.ee kasutaja annab platvormi haldajale õiguse tema poolt sisestatud isikuandmete töötlemiseks. Juhul kui kasutaja soovib [rahvaalgatus.ee](http://rahvaalgatus.ee/) poolt isikuandmete töötlemise lõpetamist, võimaldab [rahvaalgatus.ee](http://rahvaalgatus.ee/) kasutajal oma kasutajakonto ja kõik sinna juurde kuuluvad andmed kustutada.
> 
> Kasutajakonto on vaja luua algatuse loomiseks ja kommentaaride andmiseks. Kasutajakontode haldamiseks kasutame CitizenOS API (omanik Teeme ära SA) teenust. CitizenOS API teenuse tingimused on avalikult üleval [siin](https://citizenos.com/et/topics/7abdd244-d45b-40d3-997c-a6290d4e972c).
> 
> Toetusallkirja andmise jaoks ei ole vaja endale kasutajakontot luua. Toetusallkirja andmisel salvestatakse nimi ja isikukood.  Andmeid töödeldakse üksnes kollektiivse pöördumise esitamiseks ning töötlemine toimub märgukirjale ja selgitustaotlusele vastamise ning kollektiivse pöördumise esitamise seaduse 3. peatüki regulatsiooni alusel.
> 
> Toetusallkirja andnute nimekiri on nähtav algatuse autori(te)le pärast hääletusaja lõppemist, mil autorkond saab alla laadida digiallkirjadega konteineri ja Riigikogu Kantselei vastutavale töötajale, kes kontrollib rahvastikuregistrist, et digiallkirjad on andnud vähemalt 16 aastased Eesti alalised elanikud.
> 
> Andmeid hoitakse konfidentsiaalsena ning kõiki isikuid, kellel on õigus isikandmeid töödelda, on teavitatud isikuandmete konfidentsiaalsest olemusest. Toetusallkirja andjaid  [rahvaalgatus.ee](http://rahvaalgatus.ee/)  avalikult ei kuva,  kuid selline tehniline arendus on avatuse nimel plaanis. Kui tehniline arendus valmib, siis tagasiulatuvalt seda ei rakendata ning kasutajal on võimalik ise määrata, kas ta toetus on avalik või mitte.
> 
> Kui isik leiab, et tema õigusi on põhjendamatult piiratud või rikutud, on tal õigus pöörduda Andmekaitse Inspektsiooni või kohtusse.
> 
> Teavitame rikkumisest Andmekaitse Inspektsiooni põhjendamatu viivituseta ja võimaluse korral 72 tunni jooksul pärast rikkumisest teadasaamist, v.a juhul, kui rikkumine ei kujuta endast tõenäoliselt suur ohtu füüsilise isiku õigustele ja vabadustele. Suure ohu korral andmesubjekti õigustele ja vabadustele teavitame andmesubjekti, et tal oleks võimalik kohe vajalikud meetmed võtta.

`about_EST_13_04_2018.md`:

> ## Isikuandmete töötlemine 
>  
> Isikuandmed on rahvaalgatus.ee platvormil sisestatud kasutaja kohta käivad andmed. Rahvaalgatus.ee kasutaja annab platvormi haldajale õiguse tema poolt sisestatud isikuandmete avalikustamiseks, töötlemiseks ja säilitamiseks. Juhul kui kasutaja soovib rahvaalgatus.ee poolt isikuandmete avalikustamise, töötlemise ja säilitamise lõpetamist, võimaldab rahvaalgatus.ee kasutajal oma kasutajakonto ja kõik sinna juurde kuuluvad andmed kustutada.
> 
> Kasutajakonto on vaja luua algatuse loomiseks ja kommentaaride andmiseks.
> Kasutajakontode haldamiseks kasutame CitizenOS API (omanik Teeme ära SA) teenust. CitizenOS API teenuse tingimused on avalikult üleval [siin](https://citizenos.com/et/topics/7abdd244-d45b-40d3-997c-a6290d4e972c).
> 
> Toetusallkirja andmise jaoks ei ole vaja endale kasutajakontot luua.
> Toetusallkirja andmisel salvestatakse nimi ja isikukood.
> Toetusallkirja andnute nimekiri on nähtav algatuse autori(te)le pärast hääletusaja lõppemist, mil autorkond saab alla laadida digiallkirjadega konteineri ja Riigikogu Kantselei vastutavale töötajale, kes kontrollib, et digiallkirjad on andnud vähemalt 16 aastased Eesti alalised elanikud.
> 
> Toetusallkirja andjaid rahvaalgatus.ee avalikult veel ei kuva, kuigi selline tehniline arendus on avatuse nimel plaanis. Kui tehniline arendus valmib, siis tagasiulatuvalt seda ei rakendata ning kasutajal on võimalik ise määrata, kas ta toetus on avalik või mitte.

Laivis on hetkel `about_EST.md` versioon. See tundub sisukam ja jääb. Küll aga on see tänaseks pisut aegunud — ei kasuta me enam Teeme Ära SA teenust nt. Liigutan teksti siia repo-sse ja viskan lingi, et saaksid GitHubi editoriga muuta.

**Comment by moll** [comment]
Eemaldasin ise «Kasutajakontode haldamiseks kasutame CitizenOS API (omanik Teeme ära SA) teenust. CitizenOS API teenuse tingimused on avalikult üleval [siin](https://citizenos.com/et/topics/7abdd244-d45b-40d3-997c-a6290d4e972c).» lause.

Mittevastav on veel "Toetusallkirja andnute nimekiri on nähtav algatuse autori(te)le pärast hääletusaja lõppemist, mil autorkond saab alla laadida digiallkirjadega konteineri [...]" lause. Eemaldasime algataja allkirjade laadimise mingi aeg tagasi.

**Comment by moll** [comment]
Kuna Markdowni failid on nüüd repos, sulgen _issue_, kuid teen sulle tingimuste uuendamise meeldetuletuseks uue issue, @infokujur? Võin tolle lause ka muidugi ise kohe kustutada.

Küll aga ehk tuleks mõelda, kas kolmekeelne tingimuste dokument on hea, nähes, et teised keeled ei saa nii regulaarset ülevaatamist kui eesti keel. Vale tekst on vast hullem kui puuduv tekst — viimase puhul teavad mitte eesti keelt kõnelevad inimesed vähemalt mõnd online tõlkeprogrammi kasutada.

**Comment by moll** [comment]
"Platvormist" tekstid leiad `about.md` failidest https://github.com/rahvaalgatus/rahvaalgatus/tree/master/locales kaustas.

**Comment by infokujur** [comment]
Jah, palun eemalda see lause ja pane mulle tõlkimiseks uus issue üles. Meil juba kogunenud siin teisigi asju, mida tõlkida.

**Comment by moll** [comment]
Lause eemaldatud nii eesti- kui inglisekeelsetest tingimustest.

Tõlgete jaoks on meil tegelikult juba https://github.com/rahvaalgatus/rahvaalgatus/issues/52.
