### ISSUE TITLE
Automaatsed teavitused

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#125]
Ühe algatuse kohta hakkavad saatma teateid erinevad osapooled.
Kasutajal on võimalik tellida:
- Riigikogu kantselei jm ametlik menetlusinfo
- Teated algatajalt
- Algatusele lisatud kommentaarid
- Muu (meedia ja kolmandad osapooled)
- Kõik eelnev

Kogu info peab olema avalik info st nähtav ka menetlusvaates, mis tuleb arendusse 2019.

**Comment by moll** [comment]
Kas selle ülesandega oskame praegu midagi ette võtta? Käsitsi teavituste saatmine on meil olemas. Ka on valmisolek teavituste liikide lisamiseks ja valimiseks.

Kui soovime lubada algatajatel jälgijatele kirjutada, võime seda esialgu teha ka modereeritult — saadame kirja päriselt alles peale ülevaatust.

**Comment by infokujur** [comment]
See kehtib. 
Kogu infovahetus peab olema avalik. Ehk meil ei teki mingisuguseid kinniseid liste. Ühtlasi peab olema teavituse tellijal võimalik algatajalt teateid mitte saada. Võime töösse võtta.

**Comment by moll** [comment]
Jaa, hea lähenemine — saadetud teavitused, praegused käsitsi saadetavad ja tulevikus automaatsemad, kuvame menetlusvaates Riigikogu sündmuste vahel (v.a kommentaaride teavitused ilmselt).

Detailsema teavituse konfi saab's ka koos algataja teavitustega ära teha. Algataja teavituse võib tõenäoliselt vaikimisi sisse lülitada — eriti kui neid algul üle kontrollime. Kommentaarid jätaks opt-in.

Siit siis kolm ülesannet:
- Algataja teavituste saatmine.
- Saadetud teavituste kuvamine menetlusinfos.
- Kommentaaride teavitused.

Ülal tõid ka meedia välja. Oskame selle kohta ka midagi praegu teha või jääb see wishlisti?

**Comment by infokujur** [comment]
Nügimisnuppude teavitused võiksid ka minna - meedia on seal üks osa. Algatuse kampaanialehed, arvamusartiklid jms. Aga see on hetkel detaili läbi mõtlemata.

**Comment by moll** [comment]
Kommentaaride teavituste jaoks tegin https://github.com/rahvaalgatus/rahvaalgatus/issues/177.

Meediakajastuse teavitused on käsitlemata. Ehk ajab asja ära, kui algataja sisestab need lihtsalt meneltusinfona? Muidugi https://github.com/rahvaalgatus/rahvaalgatus/issues/160 raames sai lisatud meediakajastuse linkide loend. Kahtlustan aga, et menetlusinfo ajaline vaade on meediakajastuseks parem — lingiloendis on kõik lingid sama tähtsad, ajajoonel on lugejal lihtsam aga vanu uudiseid ignoreerida. Kõik meediakajastus ei pruugi ka digitaalne olla. Miks mitte lubada menetlusinfosse paberväljaande skänni panna.

**Comment by moll** [comment]
Kuna praegu on teavitustest jäänud vaid kommentaaride oma, #177 _issue_-s, siis võib vast käesoleva sulgeda.
