### ISSUE TITLE
Menetlus lõpetatud

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#127]
See algatus võeti menetlusse siiski märgukirjana.
Panen menetlusinfo kommentaariumi. Peab mõtlema, mida nende märgukirjadega teha.

Rahvusvärvid kuuluvad rahvale
https://rahvaalgatus.ee/initiatives/ab52a156-db89-488a-b364-ccf045b2210a

**Comment by moll** [comment]
Võid oma kommentaari tegelikult ka menetlusinfosse panna (oled sealgi admin-kaasalgataja). Siis torkab ta paremini silma.

**Comment by infokujur** [comment]
Ok. Jah nende märgukirjade jm tuleb eraldi veel tegeleda. Veel paar varianti on, aga ma siis peaks kõigiga samaväärselt tegelema. Ootame lisajõudu, siis menetlusinfo saab üleüldiselt palju paremaks.

**Comment by moll** [comment]
Panin algatuse lõpetatuks, kuid märgukirjad ja disain üldisemalt tuleb jutuks võtta tõepoolest.
