### ISSUE TITLE
Eestikeelsel lehel vaikimis +372 lahtrisse

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#13]
Kasutaja request

"Palun lisage mobiil ID vormi eestikeelsel lehel vaikimisi +372 ise ette, et numbri tüksimine lihtsam oleks."

**Comment by moll** [comment]
Asi ei ole tegelikult niivõrd "+372" lisamises, ma argumenteeriks, kui Citizeni API kontrollis, et numbril suunakood oleks. Mobiil-Id API taustal peaks toetama ka ilma suunakoodita. @tiblu

**Comment by tiblu** [comment]
@moll OK, tegin taski, et kontrollida, kas vaikimisi on +372 ja kui piirang meie pool, siis võtta see maha.

**Comment by moll** [comment]
Yay. Thx.

**Comment by infokujur** [comment]
@moll Kuidas teada saame, mis sellest sai :)?

**Comment by moll** [comment]
Citizeni Trellos 15. maist https://trello.com/c/xQRkyAMw/785-feat-remove-372-requirement-from-mid-login-signing-see-if-dds-defaults-to-372-https-githubcom-rahvaalgatus-rahvaalgatus-issues-1 ja praegu 6ndal kohal.

**Comment by moll** [comment]
Katsetuse tulemusel jääb mulje, et Citizen _ei_ valideeri enda poolt, vaid delegeerib selle SK-le. SK toetab numbreid nii süntaksiga +372xxx kui ka 372xxx. Lihtsalt xxx-ide puhul antakse tagasi veateade.

Lisasin algelise "+372" prefiksi lisamise meie poole ja lükkasin laivi.
