### ISSUE TITLE
Vahetada telefoninumber Riigikogu Kantseleile saadetavas kirjas

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#130]
Praegu 6938330 vaja +372 55 64 52 16

**Comment by moll** [comment]
Tehtud. Meilide sisu on hetkel Citizeni API koodibaasis, sestap ei saa sa teksti ja kontaktandmeid ise muuta. Kunagi võiks needki me tõlketabelis või koodibaasis olla.
