### ISSUE TITLE
#kestame algatustele #kestame sõna juurde (nagu uueeakuse mehikesed ja arvamussfestivali a)

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#132]
Praegu see arutelu:
https://rahvaalgatus.ee/initiatives/360ef438-f657-4905-9a8c-39fc59338cda

Tuleb veel 3 arutelu lähipäevil. Panen siia teemasse siis lisaks need uued teemad.

**Comment by infokujur** [comment]
#kestame (nii näeb kastis parem välja #kuidasmekestame jääb vast liiga pikk)

**Comment by moll** [comment]
Tehtud.
