### ISSUE TITLE
Toetusallkirjade hetkearv Facebooki lehe postituses, uuendused FB lehe laadimisel

### ISSUE THREAD

**Issue by jaanusnurmoja** [rahvaalgatus/rahvaalgatus#133]
Temaatiliselt on see küsimus seotud avaliku API-ga, vt.
https://github.com/rahvaalgatus/rahvaalgatus/issues/113
kuid vääriks ilmselt eraldi vaatlemist, sest ilmselt on siin vaja kaasata mõnda Facebooki app'i.

Väga tänuväärt oleks niisugune funktsionaalsus, mis võimaldaks näidata toetusallkirjade arvu hetkeseisu Facebooki lehel. Näiteks nii, et seda näitab üks kinnitatud postitus lehe uudistevoo alajaotuses. Igal lehe laadimisel kontrollitakse allkirjade hetkeseis rahvaalgatus.ee 's üle ja kui on toimunud mingeid muudatusi, siis toimub postituse uuendamine. 

Kujutan seda praegu ette nii, et 
1) algatuse juures on autori jaoks olemas lisaseadete võimalus. Kõigepealt kirjutab ta Facebooki lehel valmis postituse, kus on kindlasti sees allkirjastanute hulk. Seejärel kopeerib ta teksti täpselt samamoodi sinna lisaseadetesse ning asendab numbri vajaliku muutujaga. Kindlasti on mingid väljad ka lehe id ja postituse id jaoks. Käivitudes kontrollib kood õiget postitust ning kui vahepeal on toimunud muudatusi, läheb postituse muutmise POST teele. 
ALTERNATIIV - kasutajal on veebileht, kus omaloodud kood loeb rahvaalgatuse api-st allkirjade arvu ning uuendab FB postitust, kui vaja.  Sellisel juhul ei ole rahvaalgatuse koodis vaja midagi muuta. 
2) aga selleks, et see käivitumine toimuks, oleks ilmselt vaja Facebooki poolel mingit päästikut, mis rakenduks iga kord, kui lehte laetakse ning käivitaks vajaliku koodi kasutaja veebilehel või siis rahvaalgatuse portaalis algatuse enda juures. Juhul, kui sellise päästiku tekitamise võimalus on Facebookis juba praegu olemas, oleksin tänulik õpetuse eest :)

**Comment by moll** [comment]
Hei

Andestust, jäi ennist vastamata.

> Väga tänuväärt oleks niisugune funktsionaalsus, mis võimaldaks näidata toetusallkirjade arvu hetkeseisu Facebooki lehel. Näiteks nii, et seda näitab üks kinnitatud postitus lehe uudistevoo alajaotuses. Igal lehe laadimisel kontrollitakse allkirjade hetkeseis rahvaalgatus.ee 's üle ja kui on toimunud mingeid muudatusi, siis toimub postituse uuendamine.

Mul pole kahjuks endal kogemust Facebooki Pages API-ga, kuid seni nähtu alusel olen skeptiline, et Facebook võimaldab oma lehe kuvamisse sedasi haakuda. Võimalik, et neil on Facebooki Page'i infolahtrite uuendamiseks küll liides, kuid kardan, et see jääb praegu Rahvaalgatuse koodibaasi ulatusest (_scope_'ist) välja (@infokujur võib mind parandada, kui eksin). https://developers.facebook.com/docs/pages/ põhjal vajaks Pages API kasutamine ka lepingut Facebookiga. Olen ühte lepingut ühe teise FB API kasutamiseks näinud ja ei suutnud uskuda, kui naeruväärselt privaatsusevaenulik see on. Põhimõtteliselt nõuab Facebook õigust pääseda ligi su serverisse, ja seda ei tasu küll lubada. :)

Vaatamata aga Rahvaalgatuse ja Facebooki otsesele koostööle peaks n-ö kolmandal osapoolel — sul — olema võimalik FB-ga siduda. Võtad algatuse küljest allkirjade arvu ja teed vastavad FB API päringud. Kui mingit infot meie poolt selleks veel vaja, anna teada!

**Comment by infokujur** [comment]
Aitäh @moll selgitamast. Ma ei ole spetsiifikaga kursis, kuid jah - meie serveris käima keegi hakata ei saa :).

**Comment by moll** [comment]
Panen _issue_ kinni, kuna momendil pole selle kontekstis Rahvaalgatusel midagi arendada, kuid kui tuvastad töö käigus midagi, mida me ei võimalda, @jaanusnurmoja, anna teada ja avame taas või teeme uue.
