### ISSUE TITLE
#kuidasmekestame märk külge palun veel siia:

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#134]
https://rahvaalgatus.ee/initiatives/360ef438-f657-4905-9a8c-39fc59338cda
#kuidasmekestame arutelusarja teemaseminar: sündimus

https://rahvaalgatus.ee/initiatives/242f910e-f9c8-4e99-9d48-f3fd1e11b3b3
#kuidasmekestame arutelusarja teemaseminar: Eesti sisene ränne

https://rahvaalgatus.ee/initiatives/d02bb13b-6b6b-43f0-ab2f-08b3e67423dc
#kuidasmekestame arutelusarja teemaseminar: tööhõive

**Comment by moll** [comment]
Tehtud! Ja märge peaks ikka #kuidasmekestame olema nagu eile mainisid, jah?
