### ISSUE TITLE
Võeti menetlusse, palun ligipääsu algatusele

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#135]
Nõuame, et teadmata kadunud inimese otsingu alguses kaasaks riik KOHE kogu olemasoleva ressursi, kaasaarvatud vabatahtliku organisatsiooni SA Kadunud OPEROG.

https://rahvaalgatus.ee/initiatives/4810be27-f033-4536-8454-b0343355d0a4

**Comment by moll** [comment]
Tehtud!
