### ISSUE TITLE
Avaandmed - teha avalikult kättesaadavaks Citizen OS avalik statistika aadress `GET /api/stats`

### ISSUE THREAD

**Issue by tiblu** [rahvaalgatus/rahvaalgatus#136]
Palun teha avalikult kättesaadavaks Citizen OS API avalik statistika aadress `GET /api/stats` informatsioon.
Hetkel on ligipääs sellele piiratud - https://cos.rahvaalgatus.ee/api/stats

Näidisinfo, mida väljastatakse Citizen OS keskkonnast - https://api.citizenos.com/api/stats

**Comment by moll** [comment]
@infokujur, eelistusi-seisukohti? Kui seal on infot, mida päriselt keegi asjalikult kasutada tahab, siis tasub seda rahvaalgatus.ee prefiksiga aadressil kuvada. Citizeni aadress on meie süsteemis vaid implementatsioonidetail.

**Comment by moll** [comment]
Kui juba päevade lõikes avaldada, siis pole random timestampil seal mõtet. Piisab lihtsalt ühest numbrist.

**Comment by infokujur** [comment]
Selge. Siis niipidi. Rohkem midagi meil jutuks ei olnud ju? Kui ei, siis võib ära teha - rahvaalgatus.ee prefixiga. Palun viita andmevoog ka opendata.riik.ee lehele.

**Comment by moll** [comment]
Lahendame lähipäevil https://github.com/rahvaalgatus/rahvaalgatus/issues/176 raames. Jätan issue siin küll lahti, kuniks andmed ka masinloetavalt kättesaadavad.

**Comment by moll** [comment]
Ka koondstatistika masinloetavalt kättesaadav. Lühijuhend https://github.com/rahvaalgatus/rahvaalgatus#api koos viitega SwaggerHubi pikemaks dokumentatsiooniks.

Kui keegi soovib API dokumentatsioonile linkida, siis palun tehke seda läbi repo README — ehk https://github.com/rahvaalgatus/rahvaalgatus#api. Võimalik, et tulevikus hostime dokumentatsiooni HTMLi mujal kui SwaggerHubis ja README-i vahendusel linkides ei lähe kellegi lingid katki.
