### ISSUE TITLE
Palun ligipääsu menetlusinfo uuendamiseks: Ilutulestiku algatus

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#138]
https://rahvaalgatus.ee/initiatives/42880cae-dc30-46b4-863f-26b795086bef
Maksustame ilutulestikuga paugutamise vabatahtlike päästjate toetuseks

Võiks korraldada nii, et kõik algatused, mis saadetakse jagatakse menetlusinfo uuendamiseks, siis ei ole vaja eraldi issuet teha.

**Comment by moll** [comment]
Ligipääs antud.

Jaa, juba plaanis anda sulle ligipääs menetlusinfo lisamiseks käsitsi sekkumiseta.
