### ISSUE TITLE
Juhendid üle vaadata

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#14]
Täpsemalt lahti kirjutada isikuandmete käitlemine, kommentaariumi poliitika ja etapid (3 päeva piirang).

**Comment by infokujur** [comment]
#9 #8 Seotud

**Comment by infokujur** [comment]
KKKsse:
Juba avalikustatud algatust ei saa privaatseks muuta, vaid peab uue kinnise algatusena üles panema.

**Comment by moll** [comment]
Tundub pikalt lahti olnuna kas jooksev ülesanne või muidu wishlist.
