### ISSUE TITLE
Palun roppusele tärnid

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#140]
Palun asenda kuus tähte, kuu tärniga: https://rahvaalgatus.ee/initiatives/f13eb6d7-2c94-44fe-b0fa-d56cbfb936f5#comment-34eda9c2-735c-4351-b12f-b30ccef9ef85-reply

Ajaloo võib alles jätta, aga see peab olema vähemalt kliki taga ja hoiatama, et siit ta tuleb.

**Comment by moll** [comment]
Kuus tähte, mida https://rahvaalgatus.ee/initiatives/f13eb6d7-2c94-44fe-b0fa-d56cbfb936f5/comments/34eda9c2-735c-4351-b12f-b30ccef9ef85 kommentaaris silmas pead, moodustavad sõna "nahhui"?

**Comment by moll** [comment]
Sõimusõnad saavad vaikimisi peidetud ning originaalne kommentaar jääb nupuvajutuse kaugusel. Lükkan hommikul laivi.

Sõnade nimekirja ise liigutasin hetkel tõlketabelisse, kuhu nad võib reavahedega eraldatult panna.

**Comment by moll** [comment]
Sõnad `CURSEWORDS` lahtris tõlketabelis saavad nüüd järgnevalt veebis peidetud:
![screenshot from 2019-02-20 12-40-47](https://user-images.githubusercontent.com/156837/53092469-c86d5980-350c-11e9-9189-e07bfc24a5d3.png)

Kuvamiseks piisab hiirega üleminemisest või teksti kopeerimisest.
