### ISSUE TITLE
Githubi link jalusesse jt teised sotsiaalmeedia ikoonid: Twitter ja Facebook

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#142]
Nii Abi rubriik, kui pealeht.
https://github.com/rahvaalgatus/rahvaalgatus

Citos logo ja lingi asemel Githubi oma.
See, mis kood on, näebki siit, kus on litsentsid ja hetkeseis näha ja viidatud.

**Comment by infokujur** [comment]
Twitter: https://twitter.com/rahvaalgatus
Facebook: https://www.facebook.com/rahvaalgatus

- Twitteri ja Facebooki link ka esilehele "Ole algatustega krusis" nupu kõrvale.
- Ja iga algatuse lõppu "Telli teavitus" nupu kõrvale

**Comment by infokujur** [comment]
Selle pisitöö võiks enne suuremat arendust ära teha.

**Comment by moll** [comment]
Lisasin esilehele lingid Facebooki ja Twitteri logodega. Teises raundis vaatan, ehk saaks algatuste jälgimise üleskutset esilehel ka pisut elegantsemalt esitleda.

GitHubi logo lisasin jalusesse. Äkki liigutaks jaluse FB ja Twitteri lingid ka paremale GitHubiga ühte ja asendaks logodega?

**Comment by infokujur** [comment]
Jah, sujuvamaks on seda vaja teha, aga praegu selline asi sobib. Tegeleme edasi siis, kui meil 6 etapiline protsess on tehtud. Siis teame neid ülekusteid ja infot selles UX piirkonnas paremini hinnata.
