### ISSUE TITLE
Facebook-iga jagamine annab veateate

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#144]
"Telli teavitus" nupule klikates annab:
href should represent a valid URL

**Comment by moll** [comment]
Millise algatusega see tuleb? Testisin ise suvalisega ja töötas.

**Comment by infokujur** [comment]
https://rahvaalgatus.ee/initiatives/40bed752-854e-4cab-9cf0-e055480d4a45
Sellega tuli. Oli ka juhuslik :).

**Comment by moll** [comment]
Hehe, tõepoolest. Natuke liigutasin üht-teist ringi paar tundi tagasi ja sellest ka viga. Andestust! Parandatud!
