### ISSUE TITLE
Uute algatuste teavituste tellimine on Mailchimpi poolt piiratud

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#145]
Avastasin https://github.com/rahvaalgatus/rahvaalgatus/issues/144 raames hoopis, et Mailchimpil on 60-grupi piirang ja see on lõhkunud me teavituste tellimise. Selle parandamine tähendab meililoendi pidamist väljaspool Mailchimpi, mis on meil niikuinii kavas olnud. Esialgu tasuks vähemalt meiliaadresside korjamine parandada ja hiljem siis vaadata, kuidas neile teavitusi saadame.

**Comment by infokujur** [comment]
Jah, teeme nii.

**Comment by moll** [comment]
Tehtud. Asendasin Mailchimpi-põhise teavituste tellimise me enda andmebaasis hoitava listiga. Meiliaadressile saadetakse Mailchimpi-laadselt ka kinnitus. Adminnilehel saad kinnitatud ja kinnitamata meiliaadresse näha ja vajadusel kinnitatud aadresside listi [Mailchimpi kaudu] meilimiseks alla laadida. Nüüd võiks põhimõtteliselt menetlusinfo lisamise hetkel ka meilimise implementeerida. Nõnda jääks käsitsi Mailchimpi kopeerimine ära.

Esilehel olev "kõikide algatuste teavitus" toetub veel Mailchimpile. Ka ei ole Mailchimpist vanu aadresse meie andmebaasi üle toonud.

**Comment by infokujur** [comment]
Jah, võtame selle automaatse teavituse siis kohe ette. Meil siis peaks tekkima mingid templiidid, mis eventide peale välja saadetakse. Kas need evendid on meil praegu kuskil olemas juba nimekirjana?

**Comment by moll** [comment]
> Meil siis peaks tekkima mingid templiidid, mis eventide peale välja saadetakse.

Yep. Esimeses versioonis teeks ilmselt tavatekstina ja teise ringina vaataks HTML-iga stiilitavate meilide poole. Esimest meilimustandit näed aga juba tõlketabelis teavituste tellimise kinnitusmeili jaoks võtmega `CONFIRM_INITIATIVE_SUBSCRIPTION_BODY`. 

> Kas need evendid on meil praegu kuskil olemas juba nimekirjana?

Millised eventid? Menetlusinfo? Teavituste tellijad? Kui adminniliidesest mõnd algatust vaatad (nt https://admin.rahvaalgatus.ee/initiatives/4810be27-f033-4536-8454-b0343355d0a4), näed seal nii teavituste tellijaid kui ka menetlusinfo sissekandeid.

**Comment by moll** [comment]
> näed seal nii teavituste tellijaid

Hetkel näed muidugi vaid neid, kes on teavituse tellinud peale eilset. Mailchimpist import ees.

**Comment by infokujur** [comment]
Ok, siis on meil vaja see flow koos läbi käia. Ma siia juurde tooks ka mõjumudeli töö - indikaatorid jms.

**Comment by moll** [comment]
> Ok - hea info, siis on meil vaja see flow koos läbi käia.

Kas lähen hetkel Mailchimpist importimise ja sulle lihtsa plaintext meilide saatmise implementeerimisega edasi või vajad veel taustainfot otsustamiseks? Võid muidugi adminliidesest meiliaadressid iga kord enne saatmist Mailchimpi kopeerida, kuid sellise lähenemisega ei tööta saajatel unsubscribe'imine ega teavitusvalikute muutmine.

**Comment by infokujur** [comment]
Ja, palun mine edasi. Aga ehk saaks juba html-i?
Kui teed mulle ühe põhja, siis teised kohandan selle järgi.

**Comment by infokujur** [comment]
Kas avad siit uued taskid ise? Need võib kohe interatsiooni esimesse tulpa lisada.

**Comment by moll** [comment]
Yes, teen _issue_-d!

**Comment by moll** [comment]
Algatuste teavituste tellimused on Mailchimpist meie andmebaasi kopeeritud. Jätsin hetkel sinna alles, kuid soovitan need varsti sealt eemaldada. Nende API kaudu sai tagavarakoopia tehtud, nii et kõik kellajad ja märgitud tellimused on kenasti alles.
