### ISSUE TITLE
Algatuse tõlked (ja hiljem lisamine)

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#146]
Siin on vaja läbi mõelda, kes tõlgib ja mis taseme tõlge on.
Seni on hea lisada kõik tõlked kohe alguses, et kõik tekstid saaksid allkirjad alla.

Erijuht - eestikeelne tõlge lisatakse pärast. Muude keeltega on küsimus teine, sest neid ei menetleta (kuna neid ei menetleta).

**Comment by moll** [comment]
>  Seni on hea lisada kõik tõlked kohe alguses, et kõik tekstid saaksid allkirjad alla.

Natuke riskantne on kõiki tekste korraga allkirjastada. Esiteks ei pruugi allkirjastaja mõista teisi keeli ja teiseks, isegi, kui mõistab, ei pruugi ta jõuda neid läbi lugeda, et olla kindel, millele ta alla kirjutab. Kolmandaks, kas kollektiivse pöördumise seadus ei nõua tekste mitte eesti keeles? Kelle jaoks teisi keeli siis allkirjastatakse?

**Comment by infokujur** [comment]
Ja, õige. Ma mõtlesin sellist teksti nagu näiteks see: https://rahvaalgatus.ee/initiatives/4810be27-f033-4536-8454-b0343355d0a4

Aga see peateksti ja tõlketeksti teema on vaja sügavamalt läbi mõelda. Igal juhul ei sooviks piirata arutelu ükspuha, mis keeles. Aga praegu jäetakse mitmekeelsus teksti alles ja meil ei ole tõlgete eraldamiseks ka kasutajasõbralikku viisi.

**Comment by moll** [comment]
(Otsustasin oma kommentaari https://github.com/rahvaalgatus/rahvaalgatus/issues/250 teemast siia vanemasse teemasse tuua ja teise sulgeda)

Alljärgnev pole veel laivis, kuid on testkeskkonnas katsetamiseks üleval.

Algatust luues tuleb nüüd määrata algatuse teksti keel:

![Screenshot from 2020-06-21 22-58-33](https://user-images.githubusercontent.com/156837/85237042-c3772d80-b412-11ea-8a0a-b32c655df7fc.png)

Vaikimisi on hetkel valitud alati eesti keel, kuid selle võib siduda algataja saidi keelevalikuga. Keelevaliku juures on kohe ka lõik Riigikogu nõudest viitega kollektiivsete pöördumiste seadusele, kuid seda võib tõlketablelis kohendada. Abitekstid on avatud täiendusteks.

Kuna tõlgete lisamine pidi niikuinii toetuma sama süsteemile (editorile, andmebaasi tabelile jne) nagu põhitekst, polnud mõtet piirata võõrkeelsete tekstide muutmist ühisloomefaasis. Tõlked on nähtavad aga ühisloomefaasis praegu vaid algatajale. Kaasava demokraatia puhul võiks siin kaaluda tõlgete avaldamist ka ühisloome faasis — selleks *ühis*loome ju ongi. Kuna algataja võib ühisloomefaasis teksti niikuinii vabalt muuta, ei ole tõlgete peitmisel erilist võitu — kes tahab tagasisidet tõlkele, saab mitu keelt ühte teksti koondada. Parem lasta neil siis juba keeled eraldada ja toetuda me versioneerimisele. Allkirjastamisele saates võib aga tõlke kuvamiseks kinnitust nõuda.

Algatuse teksti muutmise lehele on seega ilmunud kolm _tab_-i:

![Screenshot from 2020-06-21 23-17-40](https://user-images.githubusercontent.com/156837/85237311-6cbf2300-b415-11ea-8264-a2d75cf119ff.png)

Seal saab algataja muuta algatuse tõlkeid ja vajadusel, kui tegi algul vale valiku või otsustas ümber, muuta algatuse keelt:

![Screenshot from 2020-06-21 23-10-50](https://user-images.githubusercontent.com/156837/85237202-77c58380-b414-11ea-8345-e835ccf441e8.png)

Allkirjastamisele saates on veel võimalus valida, millise keele tekst allkirjastamisele läheb:

![Screenshot from 2020-06-21 23-24-11](https://user-images.githubusercontent.com/156837/85237450-7eed9100-b416-11ea-9525-1fff1afeec7f.png)

Kuna algatuse keelt sai muuta arutelu vältel niikuinii, tasus korra veel inimeselt üle küsida, kui ta otsustab saata algatuse teises keeles, kui Riigikogu seda nõuab.

Nagu varem, allkirjastamise faasis põhiteksti enam muuta ei saa, kuid teised keeled ehk tõlked on jätkuvalt muudetavad. Nagu enne mainisin, allkirjastamise faasis on tõlked nii kaua külastajatele peidetud, kuni algataja nad allkirjastab. Algatuse lehel kuvatakse algatajale lisatud tõlkeid ja selgitust:

![Screenshot from 2020-06-21 23-49-59](https://user-images.githubusercontent.com/156837/85237929-f40e9580-b419-11ea-84cc-611640df4bfb.png)

Ei osanud hetkel hästi hoiatust sõnastada, nii et tekst on illustratiivne. "Allkirjasta tõlge" võib nimetada ümber "Kinnita tõlge" või muuks, et seda eristada algatuse _sisu_ allkirjastamisest. Hea oleks leida üks termin, mida kõikjal kasutada.

Allkirjastamine/kinnitamine ise on tavaline digiallkirjastamine:

![Screenshot from 2020-06-22 00-08-01](https://user-images.githubusercontent.com/156837/85238286-8adc5180-b41c-11ea-9b5d-2fb0256268e6.png)

Ei osanud siingi hetkel väga sisu luua. :) Viimane link, "kinnitus koos tekstiga", lubab näha allkirjastatavat teksti. See on HTML, kus dokumendi alguses on koht kinnitusele/vandele ja all on tsiteeritud tõlge.

Allkirjastatud tõlge ilmub algatuse lehel kõigile nähtavaks:

![Screenshot from 2020-06-22 00-13-54](https://user-images.githubusercontent.com/156837/85238423-48ffdb00-b41d-11ea-9417-5754d6004492.png)

Kui algataja tõlget muudab, jääb külastajatele nähtavaks viimane allkirjastatud versioon. Algataja ise aga näeb viimast versiooni ja hoiatust, et ta peab tõlke avalikustamiseks selle uuesti allkirjastama. 

Vaikimisi võib kuvada nt inglisekeelset tõlget neile, kes Rahvaalgatuse enda jaoks inglisekeelseks on teinud või kelle brauser veebilehtedelt inglisekeelset sisu ootab.

Hetkel ei ole algatuse allkirjastamise juures aga hoiatust, et kuigi teksti ülal on ühes keeles, allkirjastad algatust teises keeles. Arvan, et see tasuks üllatuste vältimiseks välja tuua.

Riigikokku saatmist tuleks meil enne eestikeelse põhiteksti või allkirjastatud tõlke lisamist takistada, eks?

Jään tagasiside ootele.

**Comment by moll** [comment]
- Mainime allkirjastamise juures, kui allkirjastatav tekst on teises keeles kui see, mida ülal kuvame.
- Saadame tõlke Riigikogule kaasa.
- Vaatame, kas annab kuidagi "originaal" vm termini _tab_-ide pealkirja panna.

**Comment by moll** [comment]
Laivis.

"(allkirjastatav)" läks hetkel suffiksiks. Kui algatus on kirjutatud muus keeles kui eesti, siis Riigikogule saatmiseks on vaja lisada ja kinnitada ka eestikeelne tõlge. See läheb Riigikogule allkirjapakis kaasa. Muu funktsionaalsuse kirjeldasin https://github.com/rahvaalgatus/rahvaalgatus/issues/146#issuecomment-647214416 kommentaaris.
