### ISSUE TITLE
Allkirjastamise fakti peitmine

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#148]
Enne allkirjade kustutamise tähtaegade paikapanekut ja täielikku kustutamist otsustasime lubada inimestel allkirjastamise fakt peita. Allkirja peitmine on ainult visuaalne — allkiri ise jääb alles ning kaob vaid kasutajaprofiililt. Algatuse lehel allkirjastanute arv ei muutu.

**Comment by moll** [comment]
Allkirja peitmine laivis. Kuvatakse vaid sisseloginud inimestele. Hetkel ka vaid allkirjastamises olevate algatuste puhul, kuigi, kui juba peita lasta, siis vast tasub seda ka Riigikokku läinud algatuste puhul lubada. Vähemalt seni, kuni mu nägemus, kus Riigikokku jõudes allkirjad me baasist kustutame, reaalsuseks saab. :P

**Comment by infokujur** [comment]
@moll - kas selle võib kinni panna või on siin midagi veel üleval?
