### ISSUE TITLE
HTML-i viga algatuse vaates kommenteerimiseks sisselogimise lingi juures

### ISSUE THREAD

**Issue by ilmartyrk** [rahvaalgatus/rahvaalgatus#149]
![html_bug](https://user-images.githubusercontent.com/19904307/54426491-ac7e6180-4720-11e9-818d-e8eb6471aa38.png) Algatuse vaates sisselogimata kasutajale avaneb praegu selline pilt

**Comment by moll** [comment]
Tõepoolest. Refactordasin template'e tublisti ja jäi kahe silma vahele. Aitäh! Fiksitud.
