### ISSUE TITLE
Inimloetavad URLid

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#15]
Praegu /initiatives/75a0d426-fb72-4553-bd0a-534db8f2ac76
Võiks olla /initiatives/pealkiri

@moll Kas API või ra.ee pool?

**Comment by moll** [comment]
@infokujur: Citizeni.
@tiblu: Mingi "slug"-i teema kunagi läbi käis. Praegu seda tegelikult kasutuses ei ole, eks?

**Comment by tiblu** [comment]
@moll Tõsi, slugist on olnud juttu, aga töösse pole seda kunagi pandud. Olen poolt, et oleks ilus ja ka SEO mõttes kasulik.

**Comment by moll** [comment]
Lahendusi kolm:
- Pealkirjast tehtud URLile sobilik fraas (`kysimused-vastused`). Tekitab probleeme muutuvate pealkirjadega või korduvate pealkirjadega.
- UUID + pealkirjast tehtud URL-ile sobilik fraas (`fb913c43-7e91-45d7-9049-a46c99b8f972-kysimused-vastused`). Pikk ja mitte eriti loetav.
- Lisada numbriline id kõigile algatustele (`123-kysimused-vastused`). Tähendaks Citizenil suuremat muutust ning vajadust varasemaid UUID-sid niikuinii toetada.

Jääb @tiblu seisukohta ootama.

**Comment by moll** [comment]
Tahe on, aga taas, kardan, et nii kergelt ei teosta. Tuleme selle juurde üks hetk tagasi.

**Comment by infokujur** [comment]
Nüüd tuleme tagasi seoses tekstiredaktoriga.

**Comment by moll** [comment]
Genereerime inimloetava osa, võttes arvesse, et eesti ja vene keele tähed tuleks ladina tähestikku tõlgendada.
