### ISSUE TITLE
Rahvaalgatuse toetuse lehel tavade lugemise vajaduse eemaldamine

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#150]
Hei, @infokujur 

https://rahvaalgatus.ee/donate lehel on linnuke hea tavaga nõustumise märkimiseks. Tavade lehel pole mingit seost annetamisega. Säherdune nõustumine pole nõutud enam ka [Maksekeskuse tingimustes](https://maksekeskus.ee/liitumistingimused/).

- Annetus ei ole millegi müük.
- Tavades ei räägita annetusest ja nendega mitte-nõustumine ei mõjuta toetamist. 
- Vanasti toimus annetamine ülekandega ning millegagi nõustumine polnud vajalik.
- Maksekeskusel on annetamiseks nupugeneraator, mis suunab samale lehele, kuhu meie, ilma igasuguse kinnituse vajaduseta. Erineb see meie implementatsioonist vaid aspektis, et lubame summa ise määrata.

Plaanin linnukese annetuse vormist eemaldada, kuid igaks juhuks luban sul sõna sekka öelda. :)

**Comment by infokujur** [comment]
See linnuke on seal punkt 6 pärast. Ehk me peame selgitama, mida inimene teeb n.ö ostu sooritades. Selguse huvides tuleb hea tava  jaotada mitmeks tekstisks ja seal kirjeldada ka täpselt see, mida Maksekeskus palub kirjeldada punktis 5.

**Comment by moll** [comment]
See ei haaku väitega, et *tegu ei ole ostuga* _ja_ näitega, et Maksekeskuse _enda_ poolt genereeritud annetuse nupp ei vajaks kinnitust. Oled nõus, et kui eemaldada meilt annetuse suuruse _input_, siis pole nõustumist vaja? Sealt edasi ütleb loogika, et viiele erinevale suurusega annetuse nupule pole nõustumist vaja ja ergo kui asendada viis erinevat nuppu ühe _input_-i ja ühe nupuga, poleks ka kinnitust vaja.

**Comment by moll** [comment]
Meilisin Maksekeskusele ja nende klienditeenindaja Maria jätkuvalt rõhus eraldi linnukese vajadusele. Jätan hetkel ülemise muutuse tegemata, kuid kui mahti saan, uurin neilt kõrgemalt, kust see otstarbetu vajadus alguse sai.

**Comment by infokujur** [comment]
See on tulemuslikum, kui meie UI igal hetkel hakkab ütlema, mis mingi inputiga inimese vaatevinklist tehakse. Usun, et enne seda suhteliselt võimatu sellest lahti saada.
