### ISSUE TITLE
Arutelu tähtaja muutmine peaks arvestama 3p piirangut avalikustamise hetkest

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#151]
Hetkel lubatakse arutelu tähtaega edasi lükata miinimum 3 päeva kaupa. Kuna arutelu võib olla selleks hetkeks juba mitu päeva kestnud, peaks tähtaja piirang olema arutelu avalikustamise, mitte muutmise hetkest. Praegune lahendus on kahjuks aga tingitud sellest, et arutelu avalikustamise kellaaega ei säilitata. Sellele tuleks lahendus leida.

**Comment by boamaod** [comment]
Asi pole ainult pikendamises. Liideses üteldakse, et arutelu peaks kestma *sisestamise hetkest* 72h ja muid piiranguid pole. Sisestamise hetk pole sama, mis avalikustamise hetk -- väga halvasti on see protsess dokumenteeritud. Aktivistid kipuvad sellise jama peale pahaseks saama, kui neile mingi dokumenteerimata piirang lajatatakse, see jätab tunde, et kuskil mingid kallutatud jõud takistavad.

Tegelikult on see kolme päeva piirang ka soovmõtlemine -- rahvaalgatuse portaal ei peaks minu meelest võtma patroniseerivat hoiakut aktivisti suhtes. Aga see on veel eraldi teema. Jõudu!

**Comment by moll** [comment]
Sul on õigus. Eestikeelne selgitav tekst ei olnud õige. [Tegin selle kiire paranduse](https://github.com/rahvaalgatus/rahvaalgatus/commit/3b15f2d6af621bff1cf2305e048d35ef4d77f9fd) ja lükkasin laivi. Tänu!
Üldiselt on plaanis algatuse loomise voo disain algataja vaatenurgast üle vaadata. Arvan, et seal saaks palju selgemaks teha. Oled teretulnud ka senise kohta tagasisidet andma — kasvõi siin GitHubis.

[Arutelu] tähtaja vajaduse üle olen korra ka ise mõtisklenud: https://github.com/rahvaalgatus/rahvaalgatus/issues/114#issuecomment-440686285. @infokujur oskab ehk algset motivatsiooni meenutada. Kujutan ette, et soov oli propageerida ühisloome faasi, kuigi saan aru, et Rahvaalgatuse keskkond ei pruugi loomisefaasiks kõigile optimaalne olla.

**Comment by moll** [comment]
Tähtaegu arvutatakse nüüdsest kas avalikustamise või allkirjastamisele saatmise hetkest, mis lubab hiljem tähtaega ka päeva võrra edasi lükata. Kolme päeva piirang allkirjastamisele saatmiseks avalikustamise hetkest on jätkuvalt alles. Miinimum tähtaja vajalikkuse üle võib siin edasi arutada, kuid panen _issue_ kinni, kuna täiendus ise sai tehtud.
