### ISSUE TITLE
Arutelu kustutamise funktsionaalus selgemaks

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#152]
"Kustuta arutelu"-st võib aru saada kui kommentaaride kustutamisest. Nii nupp kui üleküsimine tuleks paremini sõnastada.

Selles kontekstis võiks ehk üle vaadata ka "arutelu" termini mujal ja asendada see "algatusega". Nõnda jääb "arutelu" vaid faasi kirjelduseks.

**Comment by infokujur** [comment]
See on tehtud.
