### ISSUE TITLE
Teavituste saatmine menetlusinfot lisades

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#154]

**Comment by moll** [comment]
Administratiivliideses on nüüd iga algatuse lehel võimalik teavituse tellijatele kiri saata. Momendil ei ole see menetlusinfo lisamisega seotud, kuid vajadusel saab mustandi menetlusinfo tekstiga täita. Praegu tuleb mustand tõlketabeli tekstist `DEFAULT_INITIATIVE_SUBSCRIPTION_MESSAGE_BODY`.

**Comment by moll** [comment]
Infoks, et läbi adminniliidese saadetud teavitused jõuavad nüüd ka globaalsetele jälgijatele. Nagu ka enne, näed enne teavituse saatmist, kellele teavitus läheb. Võid vajadusel testida mõne enda algatusega, kus ühtki jälgijat peale sinu pole.

**Comment by infokujur** [comment]
Saadaks teavituse automaatselt mingi mustandi alusel, nii et seda ei peaks tingimata eraldi teavitusena maha salvestama. -- @moll

**Comment by moll** [comment]
Menetlusinfot lisades teavituste tellijatele meilimine on implementeeritud, kuid mitte veel laivis. 

Tekst, mis teavitajatele saadetakse, asetseb tõlketabelis järgmiste nimede all:
- `DEFAULT_INITIATIVE_EVENT_MESSAGE_TITLE`
- `DEFAULT_INITIATIVE_EVENT_MESSAGE_BODY`

Paar kommentaari vorminduse kohta:
- Tellimuse katkestamise link võiks jääda viimaseks asjaks meilis, sest seal on ta harilikult ka kõigil teistel teenustel. St peale allkirja.
- Ainult "Rahvaalgatus.ee" allkirjana ei ole klikitav. Soovitan nii saidi nimi, mis on siiski "Rahvaalgatus", kui ka eraldi link esilehele.
- Menetlusinfo sissekande teksti võib vormindada tsitaadiks (meilikliendid kuvavad tsitaate tavaliselt sinise/halli joonega vasakul), et ta oleks selgemini eristatav sissejuhatavast lausest. Praegu seda ei teinud.
