### ISSUE TITLE
Algatuse etappide kuvamine algatuse lehel ja CTA külastajale

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#156]
1. Arutelu
2. Allkirjastamine
3. Menetlemine
4. ..
5. ..
6. Tehtud

**Comment by infokujur** [comment]
Mõtisklesin selle üle ja jätkame seda, mis meil praegu juba olemas. Kolme järgmise etapi kohta pakun esialgu need variandid. Kui on protsessid kõik detailselt üle käidud, siis võib siin muuta.

1. Ühisloomes
2. Allkirjastamisel
3. Riigikogus
4. Valitsusasutuses
5. Järelkaja
6. Lõpetatud

**Comment by infokujur** [comment]
Lisaks ka külastaja call-to-actioni kõigi faaside jaoks.
Lisame nüüd ka võimaluse kõiki algatusi kõikidesse faasidesse liigutada.

-- @moll

Arutelu CTA võiks olla näiteks "Kommenteeri".
Riigikogu faasis "Telli teavitus", "Jälgi komisjoni tegevust" vms.
Valitsusasutuse faasis sarnane Riigikogu faasile.
Järelkaja puhul rahuolu küsitlus.
Lõpetatu juures näiteks kutse uut algatust alustama.

**Comment by moll** [comment]
Lükkasin faasijoone stagingusse üles (nt https://next.rahvaalgatus.ee/initiatives/0c3a515a-f695-41c6-b485-fd7e38df6430). Võimalik, et valitud ikoone tuleb veel kohendada. Tagasiside oodatud. Ka on lahtine, millist infot faaside vahel kuvada. Praegu kuvatakse "ühisloomes" tähtaegu, "allkirjastamises" allkirjade arvu ja "riigikogu" faasis 30p tähtaega. Valitsusasutust või selle vastamise tähtaegasid me hetkel ei kogu, et neid "valitsusasutuse" faasis kuvada...

![Screenshot from 2019-07-01 11-59-58](https://user-images.githubusercontent.com/156837/60434933-d12b1600-9bf7-11e9-8d98-4a898ce0523d.png)

![Screenshot from 2019-07-01 12-00-13](https://user-images.githubusercontent.com/156837/60434932-cff9e900-9bf7-11e9-8b75-fb7615c22a57.png)

Nii siin kui ka https://github.com/rahvaalgatus/rahvaalgatus/issues/160#issuecomment-507231144 -s tõid välja "järelkaja" faasi. See ühines hetkel visualisatsioonil "tehtud" faasiga ("Tehtud" pealkirja ise saab "Järelkajaks" nimetada), sest on ebaselge, mis eristab järelkaja faasi lõpust. Loogiline oleks, et kõik, mis toimub peale soovitud muutust, on järelkaja. Päev, kuu või kasvõi aasta hiljem. Kui "lõpetatud" faas kerkis vaid vajadusest vanu asju esilehelt jm ära koristada, siis selleks tuleb niikuinii arhiveerimine. Nõnda pole vaja nt unarusse jäätud algatusi "lõpetatud" faasi liigutada, vähemalt mitte kulisside taga, nagu seda seni teinud oleme — iga algatus jääb sinna faasi, kuhu ta jõudis. Praegune muster on tehniliselt probleeme tekitanud, sest on korduvalt vaja suletud algatuste juures välja nuputada, kuhu faasi ta nad ikkagi jõudsid.

**Comment by infokujur** [comment]
Riigikogu faas on 30 päeva + 6 kuud.
Järelkaja on aktiivne faas. Lõpetatud on ahiveeritud.
Järelkaja on näiteks siis, kui ta on valitsusasutused lõpetatud, aga mingi muu protsess veel käib.

**Comment by infokujur** [comment]
Siia veel räägitust. Kui protsess on valitsusasutuses, siis on oluline info - kontakt - nimi, epost, ametikoht ja ülesanne, mis on saadud.
Protokollis on ülesanne kirjas - x ministeeriumile - seisukohad esitada riigielarve protsessi nt

**Comment by infokujur** [comment]
Typo: allkirjastamise**s** asemel allkirjastamise**l**

**Comment by moll** [comment]
Natukese hilinemisega laivis koos räägitud kuupäevavahemike kuvamistega.

Juurde tuli https://github.com/rahvaalgatus/rahvaalgatus/issues/20 jaoks ka algatuse **Riigikogusse jõudmise kuupäev**, mis jälgib, millal algatus Riigikogu dokumendihaldusse jõudis, ja **vastuvõtmise kuupäev**, mis jälgib menetlusse jõudmist. Varasemalt lisatud **saatmise kuupäeva** väli jälgib vaid seda, millal meie süsteemist kiri teele läks. Paberil pöördumiste puhul (https://github.com/rahvaalgatus/rahvaalgatus/issues/18) jääb see tühjaks. Riigikogu API-st jm-lt importides hakkavad teised väljad saama aga täidetud.

Vanemad algatused võivad praegu kohati kuvada "n päeva üle tähtaja" jms kirju, sest mitmed pole õigetesse faasidesse liigutatud. Osa olen liigutanud kas käsitsi või tuletanud faasi muudest kuupäevadest. Lahtine on praegu, kas kõik vanad algatused, millele oleme tänaseks määranud Riigikogu menetluse lõpukuupäeva, tasuks liigutada "tehtud" faasi? Või hoopis "järelkajasse"?

Komisjone ega ka käekäiku valitsuse faasis hetkel veel ei jälgita.

**Comment by infokujur** [comment]
Super. Ma käin kõik vanad algatused üle ja teen järelepärimise. Mis asutuses ja mis seis on ning mis on järgmine liigutus. Kas Sul selle info sisestamiseks ka juba midagi valmis on?
> Kontakt - nimi, epost, ametikoht ja ülesanne, mis on saadud.
Kas teen algatuste kohta eraldi issued?

**Comment by moll** [comment]
> Lahtine on praegu, kas kõik vanad algatused, millele oleme tänaseks määranud Riigikogu menetluse lõpukuupäeva, tasuks liigutada "tehtud" faasi? Või hoopis "järelkajasse"?

Selle saan ühe käsuga teha, kui ära otsustame, kumba faasi vaikimisi liigutame.

> Ma käin kõik vanad algatused üle ja teen järelepärimise. Mis asutuses ja mis seis on ning mis on järgmine liigutus. Kas Sul selle info sisestamiseks ka juba midagi valmis on? Kas teen algatuste kohta eraldi issued?

Võid minu pärast esialgu ühte ka visata. Struktureeritud kohti/väljasid komisjonide ja valitsusasutuste kohta ei ole. Kirjutasid üleval väljad, mis seal võiks olla. Võtame mõned algatused päris andmetega ette ja vaatame, kas too mudel on piisav.

Vanade algatuste Riigikokku jõudmise ja menetluse lõpukuupäevad tulevad varsti ka Riigikogu API kaudu, nii et neid sa tingimata minu pärast käsitsi täitma ei pea.

**Comment by moll** [comment]
Meenutuseks, et ärme seisma jäänud algatusi "tehtud" faasi liiguta. Jätaks selle nende jaoks, kes tõesti Riigikokku jõudsid ja läbi süsteemi mingi tulemuse said. Nõnda saame hiljem eristada, kui kaugele algatused jõudsid — mõni ei saanud allkirju täis, mõni jõudis ehk Riigikokku, kuid lükati tagasi jne. Tagasilükatud algatuste tuvastamiseks meil momendil küll valmidust pole, kui aga mõni ette tuleb, siis lisame.
 
Arhiveerimiseks lisan ka varsti adminniliidesesse nupu. Arhiveerimine on siis peamiselt selleks, et esilehte reguleerida. "Tehtud" faasis algatused võivad muidu aga mingi aeg vabalt ka esilehel inspiratsiooniks olla. Tasuks ehk esilehel algatused ka uute faaside järgi ära grupeerida? Või vähemalt "Tehtud" algatused eraldi välja tuua.

**Comment by infokujur** [comment]
Vastan järjest (palun ava uued teemad nende põhjal, kui korraga ei saa lahendada):
- Palun pane kõik Riigikogus menetletud kuupäevaga algatused järelkajasse. Kui käin käsitsi üle, siis tõstan nad valitsusasutusse või arhiveerin, kui korrektse info kätte saan.
- Kas API kaudu komisjonid ka tulevad? (sest see on standartne info ja võib kuvada).
- Tagasi lükatud algatusi praegu ei ole esinenud veel.
- Ma "tehtud" faasi nimetusena ei poolda, pigem "arhiveeritud" - ja see tähendab, et keegi sellel teemal enam midagi ei tee. Riigikogu ei tee, valitsusasutus ei tee, algataja ei tee.
- Jah - esilehele tuleks ka need faasid tuua. Et oleks kõik näha, kus veel midagi toimub. Kasutame samu samme, mida protsessiski: Ühisloomes, Allkirjastamisel, Riigikogus, Valitsusasutuses, Järelkaja.

**Comment by moll** [comment]
> Ma "tehtud" faasi nimetusena ei poolda, pigem "arhiveeritud" - ja see tähendab, et keegi sellel teemal enam midagi ei tee. Riigikogu ei tee, valitsusasutus ei tee, algataja ei tee.

Ok, nimetan "Tehtud" sammu ajajoonel "Arhiveerituks". Eemaldan ta ka tehniliselt faasina ja jätan vaid varsti ilmuva "Arhiveeri" nupu, sest muidu on süsteemis kaks arhiveerimise kontseptsiooni ja see ei haaku hästi tulevikus "tagasi lükatud" jms käekäikudega. 

> Palun pane kõik Riigikogus menetletud kuupäevaga algatused järelkajasse. Kui käin käsitsi üle, siis tõstan nad valitsusasutusse või arhiveerin, kui korrektse info kätte saan.

Saab tehtud.

> Kas API kaudu komisjonid ka tulevad? (sest see on standartne info ja võib kuvada).

Komisjoni nimi tuleb. Muu info tuletamine (järgmine koosolek jne) on veel lahtine.

**Comment by moll** [comment]
9 algatust, millel oli tänaseks menetluse lõpu kuupäev, läksid "Järelkajasse":
- https://rahvaalgatus.ee/initiatives/d400bf12-f212-4df0-88a5-174a113c443a
- https://rahvaalgatus.ee/initiatives/343fa0e9-d3c2-4bde-b027-7ff76014fbd9
- https://rahvaalgatus.ee/initiatives/bba06bbf-5a83-47cc-9709-3c61a4109f7d
- https://rahvaalgatus.ee/initiatives/b5eb835d-9593-4fb2-9583-f841fda6b514
- https://rahvaalgatus.ee/initiatives/e05abc15-5e49-4205-bfb3-520ed6caf057
- https://rahvaalgatus.ee/initiatives/8a31585f-d7c6-4009-8833-fb5bf80a02d1
- https://rahvaalgatus.ee/initiatives/574c7dc7-efe9-42aa-8946-c4c356a36f40
- https://rahvaalgatus.ee/initiatives/42880cae-dc30-46b4-863f-26b795086bef
- https://rahvaalgatus.ee/initiatives/4cd98a74-3f69-4369-886f-893e7353a7da

**Comment by moll** [comment]
Arhiveerimiseks on adminniliideses faaside kõrval ka "Arhiveeri" nupp, mis salvestab arhiveerimiskuupäeva. Esilehelt ta hetkel ära ei kao, sest see toetub veel Citizeni staatustele. Tuleb varsti https://github.com/rahvaalgatus/rahvaalgatus/issues/187 -ga.

**Comment by infokujur** [comment]
Kõik algatused ei lähe valitsusasutusest läbi. See vist vajab veel ühte eraldi linnukest, mille saan sisse lülitada, kui näen, et valitsusasutus on menetlenud ja midagi otsustanud.

Abiks plakati kavand, millega praegu Arvamusfestivali jaoks tegelen.
Siia protsessile toon numbrid veel juurde ehk see tuleb lõpuks automaagiliselt kokku, siis kui #176 lahendatud.

![Aruteludest algatusteks - rahvakogud ja kollektiivsed pöördumised Riigikogule(2)](https://user-images.githubusercontent.com/12999094/61052317-d0626300-a3f3-11e9-9cc2-0a3087f3ad58.png)

**Comment by moll** [comment]
Valitsusasutuse faas on algatuse lehelt peidetud ja ilmub vaid siis, kui algatusele on määratud valitsusasutusse saatmise kuupäev. Teine variant olnuks kuvada valitsusasutuse faasi senikaua, kuni algatus järelkajasse ilma valitsusasutuseta jõuab. On sul emma-kumma suhtes eelistusi, @infokujur?

Valitsusasutuse kontaktandmete väljasid (https://github.com/rahvaalgatus/rahvaalgatus/issues/156#issuecomment-508410491) käsitleme https://github.com/rahvaalgatus/rahvaalgatus/issues/179 -s edasi.

**Comment by moll** [comment]
Skype'is sai räägitud, et vaikimisi peidamegi valitsusasutuse faasi ja kuvame vaid siis, kui algatus sinna läheb.

**Comment by moll** [comment]
@infokujur, kas me "Valitsusasutuse" faasi ei võiks "Valitsuses" faasiks kutsuda? "Asutus" seal tundub kuidagi kohmakas.

**Comment by infokujur** [comment]
Õige nimi on tegelikult pädev institutsioon. Vt https://www.riigiteataja.ee/akt/107032019002 § 15213.  Otsused pöördumise kohta
