### ISSUE TITLE
Kui liigub In Parlament staatusessse, siis admin saab ligipääsu info lisamiseks

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#159]
Nii ei ole vaja eraldi pingida.
Praegu vaja uuendada järjest neid algatusi, mis saavad endale otsused külge. 
nt https://admin.rahvaalgatus.ee/initiatives/b0d7c521-8cd7-414f-9f52-c15a80838ce0 läks keskkonnakomisjonile ja sotsiaalkomisjonile.

**Comment by moll** [comment]
Mõtled menetlusinfot? Seda peaksid juba saama samalt lingilt lisada. Menetlusinfo kannab hetkel inglisekeelset nime "Events".
