### ISSUE TITLE
Kuvada kuupäeva, millal algatus parlamenti saadeti

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#16]
@moll Palun pane õige silt.

**Comment by moll** [comment]
@tiblu, kuidas seda lahendada võiks?

**Comment by tiblu** [comment]
Me ilmselt API poolelt peame hakkama salvestama staatuse muutmise kuupäeva ehk "status log". Ilmselt siis iga staatuse kohta, mis Algatusel kunagi üldse on.
Kuidas API seda ajalugu tagastaks, ei tea. Kõik ettepanekud on teretulnud.

**Comment by moll** [comment]
Esialgu YAGNItada ja denormida ei taha? Logi äärmus oleks ka createdAt, updatedAt, deletedAt jm asendada logiridadega. :)

**Comment by moll** [comment]
Algatuse parlamenti saatmise hetkel teeme menetlusinfosse sissekande `type` parameetriga, mille kaudu hiljem saame välja lugeda, mil algatus parlamenti saadeti.

**Comment by moll** [comment]
Seotud https://github.com/citizenos/citizenos-api/issues/3.

**Comment by moll** [comment]
Meiepoolses andmebaasis on nüüd väli, kuhu salvestatakse kellaaeg Riigikokku saatmise hetkel. Vanadele algatustele tuleb saatmiskellaaeg tagantjärele lisada. Vaatan, kas teen seda läbi andmebaasi otse või lisan meile elementaarse kõrvallehe selliste jt administratiivtegevuste jaoks.

Hiljuti Riigikokku läinud kadunud inimeste otsingu algatusele lisasin kellaaja ise, et näeksid, kuidas seda kuvatakse: https://rahvaalgatus.ee/initiatives/4810be27-f033-4536-8454-b0343355d0a4#initiative-events. Teksti võib tõlketabelis kohendada, kuid midagi informatiivset tulevase käekäigu kohta ta olla võiks.
