### ISSUE TITLE
CTA algatajale ehk Algatuse nügimisnupud (enesehindamise vorm)

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#160]
Hei

Stagingus ootab sind paar vormielementi algatuse enesehindamise vormi teemal mõtlemiseks, @infokujur. Näed paremal tulbas https://next.rahvaalgatus.ee/initiatives/e152595b-2dab-49f7-bedc-c5c5d22a7975 lehel, kui oled algatuse autorina sisse logitud. Tolle algatuse puhul siis Juhanina (numbri/isikukoodi leiad https://github.com/rahvaalgatus/rahvaalgatus#accounts).

Disaini saame jooksvalt kohendada ja ka miski progressiriba tekitada, sarnaselt nagu mõned teenused profiili täitmise protsenti illustreerivad. Kui tahad sõnu kohendada, võid teada nda või siin ise muuta: https://github.com/rahvaalgatus/rahvaalgatus/blob/next/views/initiatives/read_page.jsx#L394

Võime siin _issue_'s edasi käsitleda, millised küsimused ja millistes etappides küsime. Kas on sel teemal me viimasest kohtumisest uudiseid?

**Comment by infokujur** [comment]
Iga etapi kohta algatajale üks nupp.

**Comment by infokujur** [comment]
Siin teemasse CTA-d külastajale (pealkirja all) > https://github.com/rahvaalgatus/rahvaalgatus/issues/156

- Kuidas lahendada abitekstid - küsimärk, millele klikates näitab lauset? Sooviks UId võimalikult puhtana hoida.
- Kui esimene ring on tehtud, siis on tn vaja iga faasi ja nupu kohta oma issued teha.

**Ühisloomes**
Täiendav info algataja kohta [ühekordne]
CTA - Lisa viide 
Abitekst: Ametliku veebilehe asemel sobib viidata ka lehele sotsiaalmeedias.

Virtuaalse arutelu kese [ühekordne]
CTA - Lisa viide
Abitekst: Sotsiaalmeedia gruppide asemel võib lisada ka teemaviite

Algatusega liitunud ühendused [täienev list]
Kaks välja: Ühenduse nimi; Viide ühenduse lehele
CTA - Lisa ühendus
Abitekst: Soovitame viidata liitunud ühenduse otsusele või pressiteatele, mis on avaldatud nende ametlikul kodulehel.

Lahendusettepanekute loomiseks korraldatud avalikud arutelud [täienev list]
Kaks välja: Kuupäev; Viide kutsele
CTA - Lisa arutelu

**Allkirjastamisel**
Algatuse kampaanialeht [ühekordne]
CTA - Lisa kampaanialeht

**Riigikogus**
Menetlemise käigus tekkinud meediakajastus [täienev list]
CTA - Lisa arvamusartikkel

**Valitsusasutuses**
Ettepanekute jõudmine arengut suunavatesse kokkulepetesse [täienev list]
CTA - Lisa viide dokumendile
Abitekst: Ühiskondliku toetuse leidnud ettepanekud võivad jõuda ka eelarvestrateegiasse, koalitsioonileppesse või arengukavasse.

**Järelkaja**
Kuidas ellu viidud otsused on olukorda muutnud? [täienev list]
CTA - Lisa viide
Abitekst: Siin on hea viidata arengut suunavate dokumentide vahearuanded ja teadustööd.

**Lõpetatud**

CTA - Loo uus algatus [https://rahvaalgatus.ee/initiatives/new]

**Comment by moll** [comment]
Kuni Rigiikogu faasini saad enesehindamise vormiga mängida stagingus: https://next.rahvaalgatus.ee/initiatives/1c475024-a10b-4747-aff7-f9d9a94faed0.

**Comment by infokujur** [comment]
Väga hea - võib live-i panna.

**Comment by moll** [comment]
Laivis!

**Comment by moll** [comment]
https://github.com/rahvaalgatus/rahvaalgatus/issues/156 raames sai Rahvaalgatus nüüd ka uute faaside toe (valitsusasutus, järelkaja/lõpetatud) ja seega sai lisada puuduvad hindamisvormi väljad "Arengut suunavad kokkulepped" ja  "Otsused ja muutused". Nimesid saame muuta, kuid kohendasin nad pisut lühemaks, et mahuksid, nagu teisedki, ühele reale. Tekstid ise pole veel tõlketabelis.

Laivis veel pole, vaid stagingus: http://rahvaalgatus.test:3000/initiatives/0c3a515a-f695-41c6-b485-fd7e38df6430

**Comment by infokujur** [comment]
Järelkaja on siiski veel enne, kui saab lõpetatud. Lõpetatud on siis, kui järelkaja on kogutud.

**Comment by moll** [comment]
Võid hetkel lugeda "lõpetatud" faasi kui "järelkaja" faasi. Käsitleme faase edasi https://github.com/rahvaalgatus/rahvaalgatus/issues/156 -s.
