### ISSUE TITLE
Algataja menetlusinfo lisamine

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#161]
Jätk https://github.com/rahvaalgatus/rahvaalgatus/issues/125 -le.

Võimaldaks algatuse autoritel teavituse tellitajatele kirju saata. Esialgu piirdume tavateksti (plain text) ja ehk pealkirjaga. Enne meili saatmist vajaks moderaatori heakskiitu, et suhtluskanali kaudu spämm teele ei läheks.

Nagu ka https://github.com/rahvaalgatus/rahvaalgatus/issues/125 teemas välja käidi, saadetud teavitused ilmuks menetlusvaatesse.

Või äkki peaks seda rohkem käsitlema algataja menetlusinfo lisamisena ja teavitus tuleneks lihtsalt menetlusinfo lisamisest? Teisest küljest, suhtluskanal algatuse jälgijatega võiks olla avatud ka enne algatuse Riigikokku jõudmist. Meil aga ilmub menetlusinfo aga alles siis, kui algatusel allkirjastamine läbi.

**Comment by moll** [comment]
Modereerimist esialgu vaja pole, küll aga peame lubama inimestel algatuse autori teavitustest keeldumist.

**Comment by moll** [comment]
Teavituste tellijate arvu juurde algatuse lehel võiks siis ka kuvada, mitu neist tellib algatajalt teavitusi.

**Comment by moll** [comment]
@infokujur, kas peaks, huvitav, lubama algatajatel ka menetlusinfo juures toimumise kuupäeva/kellaaega määrata, nagu seda admin saab teha?

**Comment by moll** [comment]
Kas kõikide algatuste jälgijatele (erinevalt konkreetse algatuse jälgijatest) tasub ikka kohe algataja menetlusinfo saata? Mul on hirm, et see on kergesti ärakasutatav — teed uue algatuse ja ilma, et keegi seda jälgima hakkaks, saad menetlusinfo kaudu üldjälgijatele kontrollimatult kirjutada. Lisan tõenäoliselt mingi väikese piirangu igaks juhuks niikuinii (a la max 5 sissekannet per algatus veerand tunni jooksul), aga üldjälgijaid see ei kaitse, sest alati saab uue konto ja uue algatuse teha.

**Comment by infokujur** [comment]
> @infokujur, kas peaks, huvitav, lubama algatajatel ka menetlusinfo juures toimumise kuupäeva/kellaaega määrata, nagu seda admin saab teha?

Mõtleme, mis on selle otstarve. Kui toimub sündmus, siis see lisatakse nügimisnupuga. Kui näeme, et läheks vaja mingiks muuks otstarbeks, lisame juurde.

> Kas kõikide algatuste jälgijatele (erinevalt konkreetse algatuse jälgijatest) tasub ikka kohe algataja menetlusinfo saata?

Siin on mitu lähenemist. Kas algatajal on vaja üldse menetlusinfot koosloome faasis lisada? Siis on ju teksti koosloome ja kogu see muu info mida lisada (mida jälle võib kõigile saata, sest see võib inimestele sisulist huvi pakkuda). Menetlusinfo tuleb sisse pigem siis, kui hakkab allkirjade kogumine.

**Comment by moll** [comment]
Tehtud. Laivi jõuab ilmselt homme või ülehomme.

Jätsin arutelu ja suletud faasid kõrvale — algataja saab menetlusinfot lisada vaid allkirjastamise ja Riigikogu faasides. Eraldi sündmuse toimumise kuupäeva määrata ei saa. Vorm on seega suhteliselt minimalistlik:

![Screenshot from 2019-06-05 22-01-31](https://user-images.githubusercontent.com/156837/58993631-9c38c880-87dd-11e9-9838-c1374cc5477f.png)

Tegin igaks juhuks juurde https://github.com/rahvaalgatus/rahvaalgatus/issues/173 potentsiaalse spämmivektori käsitlemiseks.

**Comment by moll** [comment]
![Screenshot from 2019-06-10 14-19-48](https://user-images.githubusercontent.com/156837/59201831-d8c44580-8b8a-11e9-8ac4-3311284017dd.png)
