### ISSUE TITLE
Teavituste kinnituse uuesti saatmine mingi aja möödudes

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#163]
@moll:
> Kui inimene esimesele kinnitusele reageerinud ei ole ja päev või paar hiljem uuesti teavituse tellib, võiks talle uuesti kinnitusmeili saata.

**Comment by moll** [comment]
Kinnitusmeil võib nüüd minna teele korra tunnis. See peaks takistama spämmimist, ent siiski võimaldama inimesel kiiremini uuesti teavitus tellida, kui eelmise kinnitusmeiliga midagi ootamatut juhtus. Lükkan homme laivi.

Kahjuks aga privaatsuse tõttu ei näita me uuesti teavitusi tellides välja, et eelmisele kinnitusmeilile on reageerimata. See tuleks vast infotekstis pärast vormi saatmist välja tuua.

**Comment by moll** [comment]
Natuke kohendasin teksti, mida kuvatakse peale teavituse tellimist.

Tõlketabelis järgmistes võtmetes:
- `CONFIRM_INITIATIVES_SUBSCRIPTION`
- `CONFIRM_INITIATIVE_SUBSCRIPTION`
