### ISSUE TITLE
Kuvada menetlusinfo algatuse kõikides faasides

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#165]
@moll:
> Näiteks infoga, millal algatus loodi, millal läks hääletamisele, millal sai sada, millal tuhat allkirja täis jne.

**Comment by moll** [comment]
Tehtud, kuid enne https://github.com/rahvaalgatus/rahvaalgatus/issues/167 lõpetamist pole menetlusinfos teistes faasides veel midagi kuvada.
