### ISSUE TITLE
Teavitada kõikide algatuste jälgijaid algatuse allkirjastamisele minemisest

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#166]
@moll:
> K.a konkreetse algatuse jälgijaid. -- @moll

**Comment by moll** [comment]
Tehtud ja ootab laivi lükkamist.

Teavituse tekstid on tõlketabelis järgmistes ridades:
- `SENT_TO_PARLIAMENT_MESSAGE_TITLE`
- `SENT_TO_PARLIAMENT_MESSAGE_BODY`

Tegin esialgse teksti mustandi su viimase «Algatus "Lageraied Ajalukku" on Riigikogule edastatud» põhjal. Kombineerisin esimesed kaks paragrahvi kokku ja viisin sotsmeedia lingid praegu jalusesse.

**Comment by moll** [comment]
Nüüd tehtud ja ootab laivi lükkamist.

Tekstid:
- `SENT_TO_SIGNING_MESSAGE_TITLE`
- `SENT_TO_SIGNING_MESSAGE_BODY`

**Comment by moll** [comment]
@infokujur, kas allkirjastamisele ja Riigikokku saatmise teavitus peaks, huvitav, olema "autori" või "ametliku" kanali teavitus? Riigikokku saatmine tundub justkui ametlik, aga allkirjastamisele saatmine? Või vajame kolmandat teavituste klassifikatsiooni sellisteks teavitusteks?

**Comment by infokujur** [comment]
Süsteemi teated on meie  - ehk ametlikud teated. Seal autor sisu ei loo, ega vali. Ta pärusmaa on ainult ajamoment.
Kolmas tuleb samas teemaks küll - aga järgmistes etappides. Ma praegu ette ei võtaks. Lahendame siis, kui on selge, mis see kolmas on.

**Comment by moll** [comment]
Selge. Staatuse/faasi muudatused lähevad vaid ametlike teavituste tellijatele.
