### ISSUE TITLE
100 ja 1000 allkirja kogunedes teavitada algatuse jälgijaid

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#167]
@moll:
> Ja nagu ka enne mainitud, kuvada need menetlusinfos ja juba allkirjastamise faasis.

**Comment by moll** [comment]
Tehtud. Laivis veel pole.

Seotud tekstid:
- `EMAIL_SIGNATURE_MILESTONE_N_SUBJECT`
- `EMAIL_SIGNATURE_MILESTONE_N_BODY`
- `SIGNATURE_MILESTONE_EVENT_TITLE`

Meili sisu on hetkel lakooniline ja sama nii 100 kui ka 1000 allkirja teavituse jaoks, kuid vast võiks nad olla erinevad. Esimese puhul allkirjastama kutsuv ja teise puhul mainida, et Riigikokku saamiseks allkirjad koos, kuid tasub edasi allkirjastada.

Verstapostid salvestab kõikide, k.a vanade lõpetatud algatuste kohta, ja kuvab need algatuse menetlusinfos, kuid teavituse saadab vaid nende kohta, mis on hetkel allkirjastamises ja mille verstapost saabus viimase 24h jooksul. Sobib? Või pikendaks? Kuigi ega vist parasjagu ühtki algatust pole, mis viimaste päevade jooksul 100 või 1000 täis sai nkn.

**Comment by moll** [comment]
Laivis. Ühelegi algatusele teavitust praegu välja ei läinud, sest viimase 24h sees pole keegi verstapostist mööda läinud.

Küll aga said varasemad algatused allkirjade arvud menetlusinfosse:
https://rahvaalgatus.ee/initiatives/c79c1938-dc37-439e-9e5b-9033c534239b#initiative-events

![Screenshot from 2019-06-17 11-02-47](https://user-images.githubusercontent.com/156837/59600085-bd5bbc00-90ef-11e9-93f8-2049c5cf2fcc.png)
