### ISSUE TITLE
Atom/RSS feed algatuse lehele menetlusinfo kohta

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#168]
@moll:
> Kasutusjuhuks oleks näiteks Twitterisse automaatselt tweetide tegemine läbi mingi kolmanda teenuse.

**Comment by moll** [comment]
Menetlusinfo sissekanded on nüüd läbi Atom-i saadaval. Lehel linki veel pole, kuid HTML päistes on viide nende brauserite jaoks, kes seda toetavad.

Näiteks https://rahvaalgatus.ee/initiatives/42880cae-dc30-46b4-863f-26b795086bef.atom
Feedly kuvab selliselt: https://feedly.com/i/discover/sources/search/feed/https%3A%2F%2Frahvaalgatus.ee%2Finitiatives%2F42880cae-dc30-46b4-863f-26b795086bef.

_Feed_-i nimi on tõlketabelis `ATOM_INITIATIVE_FEED_TITLE` all. Arvan, et lisan sinna ka jutumärgid pealkirja ümber. Praegu kuvatakse ka vaid käsitsi lisatud menetlusinfot. Automaatsed, nagu "Läks Riigikokku" ja "Menetlus lõpetati" on puudu.

**Comment by moll** [comment]
Atom sisaldab nüüd ka genereeritiud menetlusinfot — parlamenti saatmise ja menetluse lõpetamise sissekandeid.
