### ISSUE TITLE
Teavitada kõikide algatuste jälgijaid algatuse Riigikokku minemisest 

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#169]
@moll:
> K.a konkreetse algatuse jälgijaid.

**Comment by moll** [comment]
Tehtud ja ootab laivi lükkamist.

Teavituse tekstid on tõlketabelis järgmistes ridades:
- `SENT_TO_PARLIAMENT_MESSAGE_TITLE`
- `SENT_TO_PARLIAMENT_MESSAGE_BODY`

Tegin esialgse teksti mustandi su viimase «Algatus "Lageraied Ajalukku" on Riigikogule edastatud» põhjal. Kombineerisin esimesed kaks paragrahvi kokku ja viisin sotsmeedia lingid praegu jalusesse.
