### ISSUE TITLE
Inimese kõikide hääletamiste kuva. Kõikide häälte, mis ta on andnud.

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#17]
Seotud kasutajaprofiilide loogika läbimõtlemisega #10

**Comment by infokujur** [comment]
Hääle eemaldamiseks on võimalus kontot vahetada või hääl võtta tagasi vahetult peale hääletust. Lahti kirjutada juhendis. #14

**Comment by moll** [comment]
Puudutab inimese hääletatud algatusi.

**Comment by moll** [comment]
Seotud ka https://github.com/rahvaalgatus/rahvaalgatus/issues/115.

**Comment by moll** [comment]
https://rahvaalgatus.ee/user lehel saab näha enda allkirjaga algatuste nimekirja. Kohe kui peidetud allkirjade funktsionaalsus laivi läheb, siis loomulikult kuvatakse vaid peitmata algatusi.
