### ISSUE TITLE
Menetlussündmuse ja menetlusinfo avalikustamise hetkede salvestamine

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#170]
@moll:
> Et eristada, millal sündmus toimus ja millal avalikkus või meie sellest teada saime.

**Comment by moll** [comment]
Nüüdsest hoiame algatuse menetlusinfot oma andmebaasis koos menetlusinfo sissekande kellaja kui ka eraldi sündmuse kellaajaga. Adminniliides lubab lisada menetlusinfole sündmuse kuupäeva ja kellaaja. Algatuse lehel kuvame hetkel vaid sündmuse kuupäeva.

Laivi läheb siis, kui meilide saatmise teemalised _issue_'d on kinnituse saanud.
