### ISSUE TITLE
Teavituste kinnitamine, kui teavitused on juba tellitud ja meiliaadress kinnitatud

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#171]
Sarnane https://github.com/rahvaalgatus/rahvaalgatus/issues/163 -le.

Mõte on saata inimese meil ka siis, kui ta juba teavituse tellinud ning meiliaadressi kinnitanud. Hetkel ei saadeta siis ühtki meili, olgugi et peale tellimist väidab süsteem, et teda ootab postkastis kinnitus.

**Comment by moll** [comment]
Tehtud, aga veel mitte laivis. Võid meilisisudele pilgu peale heita, @infokujur. Vbla peaks algatuse teavituse meilile algatuse lingi lisama?

Tõlketabelis:
- `ALREADY_SUBSCRIBED_TO_INITIATIVE_TITLE` — Ühe algatuse kohta
- `ALREADY_SUBSCRIBED_TO_INITIATIVE_BODY`
- `ALREADY_SUBSCRIBED_TO_INITIATIVES_TITLE` — Kõikide algatuste kohta
- `ALREADY_SUBSCRIBED_TO_INITIATIVES_BODY`

**Comment by infokujur** [comment]
Jah, link oleks hea. Ma vaatan peale.

**Comment by infokujur** [comment]
Kõik ok.
