### ISSUE TITLE
Google Analytics asendamine lokaalse alternatiiviga

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#175]
Tänane Rahvaalgatuse Google Analytics kasutamine tähendab põhimõtteliselt seda, et Google'ile jõuab info, milliseid algatusi keegi vaatab ja kuhu oma allkirja annab. Kas ja kuidas nende profiilialgoritmid seda infot kasutavad, ei oska öelda. Privaatsuse vaatenurgast pole aga Rahvaalgatuses toimetamine nende asi, eriti kui allkirjade peitmise funktsionaalsuse raames käsitlesime allkirju kui delikaatseid isikuandmeid. Igaks juhuks rõhutan ette, et GA-le saatmine ei ole nõusoleku küsimus — isegi küsides ei peaks ega tohiks keegi seda anda. Olen mõnelt huvi pärast uurinud ja kellelegi ei tundu Google'ile saatmine aktsepteeritav.

Pakun välja, et loetleme, millist statistikat Google Analytics-is täna vaja läheb, ja leiame sellele lahenduse ilma GA-ta. Serveri logide põhjal saab külastusstatistikat probleemideta genereerida, k.a seadmete (mobiil/lauaarvuti) lõikes.

**Comment by moll** [comment]
See on rohkem päevakorras tänu Firefoxi default blokkimisele septembrist: https://blog.mozilla.org/blog/2019/09/03/todays-firefox-blocks-third-party-tracking-cookies-and-cryptomining-by-default/. Iga kord Rahvaalgatust külastades kuvab nüüd Fx lillat kilpi, et ta on blokkinud GA jälituscookie'd.

**Comment by moll** [comment]
Jätkuvalt Firefox "hoiatab" ja informeerib, et on Rahvaalgatuse lehel jälitusskripte blokkinud. Tore oleks, kui saaks spioonivarast lahti. Ei ole mõistlik ega ka juriidiliselt hea mu meelest Google'ile saata teavet, kes milliseid algatusi allkirjastab. ;)

**Comment by tiblu** [comment]
@infokujur Ma arvan, et sellele teemale peaks panema kõrgema prioriteedi.

Nimelt hetkel jagab Rahvaalgatus.ee oma lehe Kasutajate infot 3ndate pooltega - Google, UserVoice, Sentry/Raven. Heade tavade ja GDPRi järgi ei ole see lubatud.

Vähe sellest, nagu @moll mainis, uus Firefox blokib neid skripte ühel või teisel moel blokeerima. On suhteliselt kindel, et muud lehitsejad lähevad sama rada, kas kohe joonelt võib lisade abiga. On aja küsimus, millal analüütika ja potentsiaalselt mõni teine kasutatav vigur lakkab töötamast.

Citizen OS liigub lahenduse suunas, kus loobume Google Analyticsist ja otsib alternatiivse lahenduse minimaalse info kogumiseks ning salvestamiseks enda serverties, et pakkuda paremat teenust ja seda mitte 3nda pooltega jagada.

**Comment by moll** [comment]
Tänaseks on Google Analytics RA lehelt kadunud. Juhei!
