### ISSUE TITLE
Koondstatistika

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#176]
Vajab täpsustamist.

- Millal loodud?
- Millal allkirjastama saadetud?
- Millal Riigikokku jõudis ja kaua oli?
- Millal ja kaua menetleti?

**Comment by moll** [comment]
Ka ehk keskmised numbrid ja kuu lõikes kuskil esilehel kuvada.

**Comment by infokujur** [comment]
Jah - minu tabelis on praegu sellised mõõdikud ja nendest võiks lähtuda (sest nende vastu on huvi tuntud ja ma olen esitlustes neid läbivalt kasutanud).

Ehk mõõdikud siis:
Millal loodud?
Millal allkirjastama saadetud?
Kui palju allkirju kogus?
Millal Riigikokku saadeti?
Millal menetlusse võeti?
Kes menetleb? (võib olla erandjuhul ka kaks komisjoni)
Millal menetlus lõpetati?

Seda siis algatuse kohta, keskmine läbi aegade ja kuu kaupa.

**Comment by infokujur** [comment]
Paberil esitatud algatuste kohta #18 saame kätte need mõõdikud:
Millal menetlusse võeti?
Kes menetleb? (võib olla erandjuhul ka kaks komisjoni)
Millal menetlus lõpetati?

Paberil olevate allkirjade arv on hinnanguline. Kontrollitakse ainult lävendit ületav hulk. Algataja poolne hinnang ei päde, kuna sageli esitatakse lisaks allkirjadele e-posti aadresse, PIN1-sid (petstsioon.ee kaudu korjatud) või allkirju ilma isikukoodideta vms

**Comment by infokujur** [comment]
Protsessi järgmised mõõdikud:
- Otsuse tüüp (lükati tagasi, suunati edasi, lahendati)
Kui suunati edasi siis:
- Kuhu?
- Seal tehtud otsuse tüüp (lükati tagasi, lahendati)

Kavand protsessist, mida on koondstatistikaga vaja rikastada.
![66292585_1391732514317513_5776696816590389248_n](https://user-images.githubusercontent.com/12999094/61286766-2bb59c00-a7cc-11e9-8bd9-ff6f200cf503.png)

**Comment by moll** [comment]
Tegin kolm kavandit räägitud nelja andmeühiku kuvamiseks.

1. Eesti brändi ikoonidega.
  ![Front Page with Estonian Brand](https://user-images.githubusercontent.com/156837/64926819-c5f88700-d7f1-11e9-9ae5-7123a8fc1244.png)

2. Eesti brändi ikoonidega, kuid faasivärvides.
  ![Front Page with Colored Arrowed Estonian Brand](https://user-images.githubusercontent.com/156837/64926814-b37e4d80-d7f1-11e9-86cb-e94ced1a42f1.png)

3. Meie faaside ikoonidega.
  ![Front Page with Timeline](https://user-images.githubusercontent.com/156837/64926816-b416e400-d7f1-11e9-888a-8433a4287abf.png)

Värviline Eesti bränd (valik 2) tundub mulle päris viisakas kavandis, aga ülejäänud Rahvaalgatuse disainiga haakub meie faaside ikoonidega valik mu meelest rohkem — nupud esilehel ja algatuse lehel on meil suuremad ja värvilisemad kui Eesti brändi "peen" ja õhuke stiil. 

Lahtine on ka, mis terminiga kõiki loodud algatusi nimetada. Ülal kavandites kutsun neid "aruteludeks", kuid pole veendunud, et teistele on selge, et see sisaldab kõiki loodud algatusi, k.a neid, mis pole enam arutelud ehk ühisloome faasis. "Algatuse" terminiga on sama häda — see peaks tähendama algatusi, mis liikusid allkirjastamisse, isegi kui nad _enam_ pole allkirjastamises. Kutsuda neid faasi järgi "Allkirjastamises" oleks sama vale kui kutsuda "arutelusid" "ühisloomeks". Teisest küljest, ehk joonte/noolte kasutamine on piisav vihje, et tegemist on teekonnaga, kus paremale jäävad numbrid ja algatused pärinevad vasakul olevatest.

**Comment by moll** [comment]
Meeldetuletuseks endale, et "algatuste arvud" sisaldavad nii Rahvaalgatusest pärit kui ka Riigikogule muid kanaleid pidi esitatud algatusi (ja meie süsteemi imporditud). Riigikokku jõudnud algatuste arv omakorda sisaldab nii 1000 allkirjaga Riigikokku läinud algatusi kui ka märgukirju.

Hiljem, kui näitame statistikat ka Riigikogus toimunu kohta, siis "tagasi lükatud" algatuste arv peaks sisaldama nii ka valitsuses tagasi lükatud algatusi.

**Comment by moll** [comment]
Otsustasime viimati ümber kuvada praegu statistikana ainult Rahvaalgatuses tehtud, allkirjastatud ja Riigikokku saadetud algatusi. Käiku läks ka nooltega variant, mis hetkel näeb laivis selline:

![rahvaalgatus](https://user-images.githubusercontent.com/156837/65415595-99420200-dde5-11e9-87ce-934708db52ec.png)

Natuke on "Riigikogus" number vigane, sest meil on 8 algatust, millel pole Riigikokku saatmise kuupäeva ja kolm tühja avalikustamata algatust, mis on "riigikogus" staatusse määratud. Ilmselt Citizenist importimise käigus, kui nad sealt "tehtuks" said määratud. Vaatan need täna üle. 

Infoks, et Riigikokku saatmise kuupäevata on järgmised algatused:
- https://rahvaalgatus.ee/initiatives/db3d09d6-18ba-467a-9527-6bfc0605aab9
- https://rahvaalgatus.ee/initiatives/c132dd42-2709-4baf-9f2a-b269069e8399
- https://rahvaalgatus.ee/initiatives/623d03dd-512e-4fe2-8a8b-11671779770b
- https://rahvaalgatus.ee/initiatives/92cc16ee-107e-4208-b92c-2ffed24d4f4b
- https://rahvaalgatus.ee/initiatives/78ba564c-9843-4dc1-8e79-dcad2941537c
- https://rahvaalgatus.ee/initiatives/6b8e7472-897a-430f-955a-0726f3c717a5
- https://rahvaalgatus.ee/initiatives/84b1d496-1037-4c7b-b7f3-b2e1ca6b4781
- https://rahvaalgatus.ee/initiatives/2977d4e8-2835-44a8-b650-daa99b481f3e

**Comment by moll** [comment]
Tegelikult tuleb ka vaadata allkirjade arvu pärimise kiirust. Mulle tundub, et Citizeni andmebaasile saaks mõned indeksid lisada, et see kiirem oleks. Hetkel kulub esilehe renderdamiseks koos statsiga ca sekund, mis on üpris aeglane.

**Comment by moll** [comment]
Ülal nimetatud kaheksal algatusel on nüüd juures ka Riigikokku saatmise kuupäev ja selle läbi kajastuvad õigesti ka esilehe statsis.

Esilehe kiirust käsitleb jooksvalt ja statistika "API" jaoks https://github.com/rahvaalgatus/rahvaalgatus/issues/136, nii et võib vast issue sulgeda.

**Comment by moll** [comment]
Open Data portaalis ka üleval tänu @keeganmcbride -le:
- https://opendata.riik.ee/andmehulgad/rahvaalgatus/
- https://opendata.riik.ee/en/andmehulgad/rahvaalgatus/
