### ISSUE TITLE
Kommentaaride teavitused

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#177]
Ehk tasub saata vaid korra päevas.

**Comment by moll** [comment]
Esialgne kommentaaridest teavitamise implementatsioon on valmis ja stagingus (https://next.rahvaalgatus.ee). Implementatsioon saadab praegu ühe meili kommentaari kohta. Korra päevas grupeerimise võiks jätta hilisemaks, kui kommentaaride arv päevas 

Vaikimisi kommentaaride teavitust sisse ei lülitata. Momendil pole ka nende sisselülitamiseks muud varianti kui kinnitusmeili lingi kaudu avanev tellimusteavituste eelistuste leht (kolme valikuga — ametlikud ja autori teadaanded ning kommentaarid). Varem suunas kinnituslink esilehele, kuid suunasin ta nüüd eelistuste lehele, et vajadusel saaks kohe kommentaarid sisse lülitada. Üks variant oleks kommentaari vormi kõrvale lisada "Teavita mind uutest kommentaaridest" linnuke, mis teeks uue tellimuse inimese profiilis määratud meiliaadressile. See tundub mugav neile, kes oma kommentaaride vastuseid jälgida tahaksid.

Meilide tekstid:
- `EMAIL_INITIATIVE_COMMENT_TITLE`
- `EMAIL_INITIATIVE_COMMENT_BODY`
- `EMAIL_INITIATIVE_COMMENT_REPLY_TITLE`
- `EMAIL_INITIATIVE_COMMENT_REPLY_BODY`

**Comment by moll** [comment]
Jätan _issue_ siiski igaks juhuks "Teavita mind uutest kommentaaridest" linnukese aruteluks lahti.

**Comment by infokujur** [comment]
Jah - see linnuke idee sobib küll. Palun tee ära.

**Comment by moll** [comment]
Tehtud. Homme läheb laivi.

Linnukesega "Teavita mind teiste kommentaaridest." saab tellida kommentaaride teavitusi. Järgmine kord kommenteerides saab aga linnukest eemaldades kommentaari teavitustest lahti. Ametlike teavituste tellimust ei tehta ega olemasolevat muudeta — kui enne ühtki teavitust tellitud ei olnud, siis peale kommenteerimist on ainsaks tellimuseks uued kommentaarid.

**Comment by moll** [comment]
Jõudis laivi ka. Testkeskkonnas (https://next.rahvaalgatus.ee/) saab katsetada, kuid meilide saamiseks võid ühele teistkontodest dev@rahvaalgatus.ee meiliaadressi panna. Teiseks, kommentaari autorile tema kommentaarist teavitust ei saadeta.
