### ISSUE TITLE
Atom/RSS feed kõikide algatuste kohta

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#178]

**Comment by moll** [comment]
Kõik senised menetlusinfo liigid üle käidud ja kõigi jaoks nii veebi kui Atomi jaoks testid lisatud. Kui #210-s sotsmeediani jõuad, anna teada, kuidas Atomisse genereeritud tekst sobib. Vajadusel saame kokkuvõtte Atomi `<summary>` tag-iga eraldada, millest ehk kergem Twitterisse vm postitusi genereerida. Mõtlen siis menetlusinfot, kus oleme kokkuvõtte võimaluse juurde lisanud.

**Comment by moll** [comment]
Menetlusinfo sai üle käidud, aga kogemata jäi kõikide algatuste feed lisamata.

@infokujur mainis, et katsetab esialgu sotsmeediasse postitamise jaoks Zapieri. Kui panna iga Atom sissekande pealkirja ka algatuse nimi, kas see haakuks su nägemusega?

**Comment by infokujur** [comment]
Jah, nii sobib küll.

**Comment by moll** [comment]
Ühine algatuste menetlusinfo Atomi voog on laivis. _Feed readerid_ jm peaksid ta avastama nii [esilehelt](https://rahvaalgatus.ee) kui ka [algatuste lehelt](https://rahvaalgatus.ee/initiatives), kuid kui vaja otselinki, asub ta aadressil https://rahvaalgatus.ee/initiative-events.atom. Ei leidnud sellele paremat URLi, sest https://rahvaalgatus.ee/initiatives/events oleks lugenud justkui «algatus identifikaatoriga "events"». https://rahvaalgatus.ee/initiative-events URL toetab praegu vaid Atomit, kuid temast saab tulevikus teha ka brauseris loetava veebilehe.

Ühine Atom voog on hetkel suts alla megabaidine fail kõigi 587 menetlusinfo sissekandega aegade algusest. Kunagi võib ta panna kuvama vaid viimast 100, aga hetkel pole kiiret.

Iga menetlusinfo sissekanne on ühises voos ka Atomi `<source>` tag-iga, mis tähistab, et Atomi postitus on pärit ühe algatuse menetlusinfo voost. Selle juures võinuks jätta postituse pealkirja puutumata, aga kuna pole kindel, kas erinevad lugemisprogrammid allika-_tag_-i toetavad, lisasin algatuse pealkirja ka postituse pealkirja ette. Pealkirja formaati saab hiljem probleeme tekitamata muuta.
