### ISSUE TITLE
Algatusele Riigikogu komisjoni ja valitsusasutuse nimi

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#179]
Menetleja 1 välja sisuks on Riigikougu komisjon(id). Üks on peamine ja teised kaasatud.

Menetleja 2 välja sisuks on valitsusasutus, kuhu komisjon suunab algatuse etapis 4.Valitsusasutuses #156. Sama loogika - üks on peamine ja teised kaasatud.

Seda infot tuleb ajajoonel välja näidata ja selle kohta statistikat koguda ja üldvaates välja näitama hakata.

**Comment by moll** [comment]
Ajajoonel kuvamise all mõtled, et näidata, millal on üks või teine asutus algatust menetlema määratud? Siis tuleks [peamise] komisjoni sisestamise juurde lisada ka kuupäeva/kellaaja väli.

**Comment by moll** [comment]
Valitsusasutuse ja valitsusasutusse saatmise kuupäev laivis. Adminniliidesest saad lisada. Võid ka CSV-na koos algatuse id-ga anda ja impordin otse andmebaasi. Kontakt- jm detailsema info väljasid veel pole, mida https://github.com/rahvaalgatus/rahvaalgatus/issues/156#issuecomment-508410491 -s välja tõid.

**Comment by moll** [comment]
Meenutuseks, et Riigikogu komisjoni info tuleb Riigikogu API-st ja seetõttu pole ka adminnilideses selle muutmise varianti — see kirjutataks üle.

Kuna mainisid, et vahel võib olla rohkem kui üks komisjon, siis võid nad tegelikult komaga eraldada. Nõnda ei pea uhkemat implementatsiooni nende haldamiseks tegema, ent saab hiljem siiski nad eraldi struktureeritult välja lugeda.

**Comment by moll** [comment]
Tegelikult API-eelsete algatuste puhul komisjoni nii kergelt kätte ei saa (võib muidugi jälle heuristikatega teha tuletades protokollide osalejatest) ja ehk on seega vaja seda siiski käsitsi lisada. Lisan ta adminni, võtab vaid minuti.

**Comment by infokujur** [comment]
Ok, lisan kogu puuduva info käsitsi. Käin nüüd neid käsitsi läbi.

**Comment by moll** [comment]
Meil on praegu komisjoni ja valitsusasutuse nimed ja saatmise-lõpetamise kuupäevad, kuid allolevas kommentaaris mainisid ka valitsusasutuse kontaktandmeid. Kas see on jätkuvalt jõus, @infokujur?

https://github.com/rahvaalgatus/rahvaalgatus/issues/156#issuecomment-508410491:
> Siia veel räägitust. Kui protsess on valitsusasutuses, siis on oluline info - kontakt - nimi, epost, ametikoht ja ülesanne, mis on saadud.
> Protokollis on ülesanne kirjas - x ministeeriumile - seisukohad esitada riigielarve protsessi nt Ja siit saab mingi ajalise verstaposti ka juurde - kas küll kuu aja täpsusega, aga vähemasti sündmuse täpsusega küll (algavad riigieelarve arutelud nt)

**Comment by moll** [comment]
Skype'is leppisime kokku, et lisada ametikoha väli ja üldine kontaktandmete väli, kuhu sisestada meilid, telefoninumbrid jm.

**Comment by moll** [comment]
Mõlemad väljad lisatud ja adminniliideses muudetavad. Hetkel me aga ei kuva ei asutuse nime ega kontakti kuskil. Küljeribale tasuks ta vast lisada. Teen seda.

**Comment by moll** [comment]
![Screenshot from 2019-09-15 20-24-00](https://user-images.githubusercontent.com/156837/64927192-0575a200-d7f7-11e9-90b5-29f307941c75.png)

Komisjon ja valitsusasutus on nüüd ka faasijoonel.

**Comment by moll** [comment]
Küljeribal ilmuvad nüüd Riigikogu faasis komisjoni nimi ja valitsusasutuse faasis valitsusasutuse ja kontaktisiku andmed.
