### ISSUE TITLE
Kõikide kollektiivsete pöördumiste kajastamine rahvaalgatus.ee veebis (ka need, mis paberkandjal).

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#18]
Tuleb siis, kui Open Data API on Riigikogu Kantseleil valmis.

**Comment by infokujur** [comment]
Esimene algatus siin: https://rahvaalgatus.ee/initiatives/c15464d2-a85d-4917-a125-36a9f1fcc78c
Teema privaatne - algataja autoriks näitame Rahvaalgatus ja algatuse teksti lõppu märgime:
Rahvaalgatus.ee märkus
Kollektiivne pöördumine esitati paberil.
Viide originaaldokumendile siin:

**Comment by infokujur** [comment]
See oleks nüüd vaja: 
- viia olekusse menetlemine ning
- häälte arvuks kuvada 1000+. Me ei tea paberil hääletajate arvu, kuna kontrollitakse esimene 1000 (künnise ületamiseks vajalik arv). Või parem variant märkida numbri asemel sõnena EST "esitatud paberil".

**Comment by infokujur** [comment]
@moll - kuidas selle apiga on? Sealt tuleb kogu info kõikide kollektiivsete pöördumiste kohta ju? Kui on nii, siis võiks selle taski siin töösse võtta.

**Comment by moll** [comment]
Kahjuks ei tule sealt just palju infot. Kõigil esitatud algatustel
(nt https://aavik.riigikogu.ee/api/documents/collective-addresses/34a281e2-bd6c-449a-81d4-6d6be5e319a0) on puudu on kõige olulisem dokument — algatus ise.
Tegin selle käsitlemiseks https://github.com/riigikogu-kantselei/api/issues/14.

Oleneb, kui kiiresti seda funktsionaalsust tahame ja kui palju oleme nõus käsitsi tegema. Saame kindlasti lihtsustada [paberkandjal saadetud] algatuste sisestamist Rahvaalgatusse, kuid protsessi automatiseerimine pole niivõrd käkitegu. Isegi kui saame PDFi lingi https://www.riigikogu.ee/tegevus/dokumendiregister/dokument/34a281e2-bd6c-449a-81d4-6d6be5e319a0 lehelt muude vahenditega, peame PDFist midagi loetavat veebi jaoks genereerima.

**Comment by moll** [comment]
Küll aga on tobe praegune situatsioon, kus Rahvaalgatuses tehtud ja riigikokku saadetud algatustel on n-ö vale allkirjade arv, sest osad esitati paberil. Seda peaks kuidagi disainis paremini käsitlema.

**Comment by infokujur** [comment]
Kui saab ling Riigikogu Kantselei doksüsteemi, siis on ka juba hästi. Tekstiga teen ma käsitööd nii ehk naa iga dokumendi juures. Hakkame seda ka mingi hetk lahendama.
Jah - puuduvad hääled esitati paberil. Selle võiks selgelt juurde märkida.

**Comment by moll** [comment]
@infokujur, kas veebist lõppenud menetlusega algatused jätta Riigikogu faasi või liigutada tehtuks ehk järelkajaksse? API-st imporditud ent lõppenud algatused jäävad praegu Riigikogu faasi. See on jätkuvalt soov, eks?

**Comment by infokujur** [comment]
Jah ning arhiveeritud olekusse. Need tuleb käsitsi üle käia ja järelkaja teha.

**Comment by moll** [comment]
Kõik vanad algatused on nüüd imporditud. Paar-kolm, mis allkirjade avalikustamise tõttu Riigikogus uuesti tehti, ilmusid ka kollektiivsete pöördumiste API-sse, kuid ilma menetluse lõpukuupäevata. Veebi sünk hetkel ignoreerib neid ja teisi, mis kollektiivsete pöördumiste API kaudu saadaval, ja eelistab seega API-t veebitabeli ees. Mõned dokumendi/sündmuse liigid ei ole veel meil toetatud ning nende jaoks tegin eraldi _issue_-d: #196, #197, #198.

Jätkuvalt on kohati järjestusega probleeme — mõnedel dokumentidel/sündmustel on kellaaeg, teistel mitte. Kellaajata sündmused paigutatakse südaööle, isegi kui nad toimusid tegelikult hiljem See on õhus juba API-ga sünkimise ajast. Tegin eraldi käsitluseks sellele ka lõpuks issue: https://github.com/rahvaalgatus/rahvaalgatus/issues/203
