### ISSUE TITLE
Arvamusfestivali logo selle algatuse külge

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#180]
https://rahvaalgatus.ee/initiatives/86c0a961-ca9c-4818-96b6-302793124a00

Sellel aastal oleme ka Arvamusfestivalil. Koondan info siia teemasse.

**Comment by moll** [comment]
Märk küljes.

Muide, Uus Eakuse jaoks sai kunagi väike filtri funktsionaalsus tehtud. UI-s valikut pole, aga URLi teades saad vaid Arvamusfestivaliga seotud teemat välja võtta: https://rahvaalgatus.ee/initiatives?category=arvamusfestival.
