### ISSUE TITLE
Ürituste kuupäev vaja viia kujule dd-mm-yyyy

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#181]

**Comment by moll** [comment]
Panin ta hetkel samale numbrilise formaadile nagu muud kuupäevad. Kunagi tulevikus võiks kuupäeva kuu asendada sõnaga aga see vajab natuke kohandamist, et inglise keelne variant näitaks inglise keeles jne.

Laivis veel pole, kuid stagingus näeb: https://next.rahvaalgatus.ee/initiatives/0c3a515a-f695-41c6-b485-fd7e38df6430.
