### ISSUE TITLE
Algatuse teksti osaliselt peitmine hilisemates faasides

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#182]
Nagu https://github.com/rahvaalgatus/rahvaalgatus/issues/54#issuecomment-443562229 kirjeldas, võiks menetlusfaasis algatuse teksti osaliselt "Loe rohkem" taha peita:

![screenshot from 2018-12-03 00-56-19](https://user-images.githubusercontent.com/156837/49347453-6718b580-f696-11e8-8ea4-3335218451d4.png)

**Comment by infokujur** [comment]
Seda probleemi enam ei ole uue menetlusinfo kuvamise viisiga.
