### ISSUE TITLE
Tekstid algatuse vaates lähevad parema tulba peale - Chrome

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#183]
https://rahvaalgatus.ee/initiatives/86c0a961-ca9c-4818-96b6-302793124a00

**Comment by moll** [comment]
Hehe, see küll omapärane brauserite erisus (arendan Firefoxiga). Viska veel laivi ilma Chrome'i vaatamata! Aitäh.
