### ISSUE TITLE
EDIT: Võimaldame lävendi täitmiseks juurde koguda. Algataja viis paberil allkirjad kantseleisse - saadame digiallkirjad järgi ja muudame algatuse staatust

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#185]
https://rahvaalgatus.ee/initiatives/83beeb14-b161-4708-beb4-7e578c7911a1

**Jagame Eesti Euroopa Liidu toetuste taotlemisel ja rakendamisel kaheks piirkonnaks**

**Comment by moll** [comment]
Saab homme (täna) esimese asjana tehtud.

**Comment by moll** [comment]
Läks teele.

**Comment by infokujur** [comment]
Palun ava uuesti see algatus digiallkirjastamiseks. Algataja on kogunud PIN1 -sid petitsioon.ee keskkonnas ja need ei lähe lävendina arvesse. Riigikogu Kantseleiga on suheldud.

**Comment by moll** [comment]
Tehtud. See vajas adminniliidese lehel "Phase" rippmenüüs "Sign" valimist. Faasi võid alati julgelt muuta — selle peale teavituste tellijatele ega Riigikogule kirju välja ei lähe. Lisaks eemaldasin ka "Sent to Parliament" kuupäeva.
