### ISSUE TITLE
Algatuste lehe kuupäevad

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#188]
Algatuste lehel olevat algatuste kuupäevad võiksid kajasta järgnevat:
- Ühisloome faasis algatuse loomise kuupäeva. Algatuse privaatne staatus ei mõjuta ühisloomet.
- Allkirjastamise faasis algatuse allkirjastamisele saatmise kuupäeva.
- Riigikogu faasis algatuse Riigikokku saatmise kuupäeva. See klapib imporditud algatuste kuupäevadega. Riigikogu vastuvõtmise kuupäev ei ole nii oluline.
- Valitsusasutuse faasis valitsusasutusse saatmise kuupäeva.
- Järelkajas/tehtud faasides Riigikogu või valitsusasutuse lõpukuupäeva, sõltuvalt, kumb hilisem.

**Comment by moll** [comment]
Tehtud. Laivis veel pole.

Riigikogu kuupäevaks sai praegu saatmise kuupäev ja imporditud algatuste puhul Riigikokku jõudmise kuupäev. Need kaks ei pruugi aga kuidagi klappida. [OPEROG algatus](https://rahvaalgatus.ee/initiatives/4810be27-f033-4536-8454-b0343355d0a4) saadeti Riigikokku nt 23. dets, registreeriti 4 päeva hiljem 27. detsembril ning võeti menetlusse pool kuud hiljem, 15. jaanuaril. Ajajoonel kuvame siiski aga Riigikokku jõudmise kuupäeva, sest sellest tuleneb ka 30-päeva tähtaeg. Peaks ehk esilehel ka Riigikokku jõudmise kuupäeva näitama, kui see teada, @infokujur?

**Comment by infokujur** [comment]
Jah, see erinevus võib tulla sellest, et algataja saadab meilt osa allkirju ja toob ise hiljem juurde ka teistest kanalitest korjatud allkirjad. Sellisel juhul kantselei registreerib kuupäeva, kui kõik nad on koos.
Ehk reegel - näitame jõudmise kuupäeva, kui seda ei tea, siis saatmise oma.

**Comment by moll** [comment]
Laivis.
