### ISSUE TITLE
Menetluse vaate parendamine

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#19]
Praegu on MVP.

**Comment by infokujur** [comment]
#20 Otsesest sõltub

**Comment by infokujur** [comment]
Ajajoone loogika korda - st dokumendid on tekkimise mitte lisamise järjekorras (praegu vastavalt avaldamise järjekorrale)

**Comment by infokujur** [comment]
Tuua välja otsused ja osalejad - täistekstile pigem viidata.

**Comment by moll** [comment]
Lükkasin MVP versioon 2 ka laivi: https://rahvaalgatus.ee/initiatives/5140419e-2c53-47d7-a596-922a6bb1eeff. Terve algatuse ajatelge jms seal siiski pole, kuid vähemalt samm lähemale.

Menetlusinfo kuupäeva häkk sai ka sisse viidud — kui menetlusinfo pealkiri algab kas ISO 8601 kuupäevaga (`YYYY-MM-DD`) või kohaliku vormiga (`DD.MM.YYYY`), siis läheb see kuupäevaks.

**Comment by moll** [comment]
Ma sulgeks _issue_, sest ta on liiga üldine, et midagi lähitulevikus ette võtta. Täiendusi, mida hetkel ette võtsin, käsitleme https://github.com/rahvaalgatus/rahvaalgatus/issues/54 -s. Värsked ideed võib täna-homme sinna viia ja hiljem uute _issue_'dena ilmale tuua.
