### ISSUE TITLE
Algatuse default tellimus ka kommentaaridele

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#192]
Tagasiside põhjal. Kui inimene tellib teavituse, siis märkida kõigile tellitud (praegu viimases linnukest ei ole).

Ametlik menetlusinfo (sh käekäik Riigikogus).
Algataja menetlusinfo ja teavitused.
Algatuse kommentaarid.

**Comment by moll** [comment]
Nüüd tellitakse teavitus vaikimisi ka kommentaaridele. Laivi läheb homme.
