### ISSUE TITLE
Kasutaja (/user) lehel kõikide tellitud teavituste välja näitamine

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#193]
Vaja on:
- Mis algatus (algatuse nimi) ja millised kolm liiki: 1) ametlik, 2) algatajalt, 3) kommentaarid.

**Comment by moll** [comment]
Täiendasin kasutajalehte eraldi allkirjade ja teavituste haldamise alamlehtedega. Nii allkirja- kui ka teavitusridade küljendamine saab https://github.com/rahvaalgatus/rahvaalgatus/issues/261 raames täiendusi, kui algatuste "arhiivini" jõuan. Praegu näevad pisut lahjad, aga vähemalt info ja funktsionaalsus olemas. Lisasin ka allkirja allalaadimise otselingi.
