### ISSUE TITLE
Olulise tähtsusega riiklikud küsimused menetlusinfos?

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#196]
Mõnel algatusel on küljes olnud "Olulise tähtsusega riiklik küsimus" (OTRK) tüüpi dokument. Näiteks https://www.riigikogu.ee/tegevus/dokumendiregister/dokument/9188ced0-5a2e-4980-8640-c873e603301d/. Kas seda peaks ka menetlusinfos kuvama? Võib vist eeldada, et OTRK dokument on lihtsalt teemaks mõnes kohtumises, mille kohta eeldatavasti on ka protokoll. Kui arutelu/protokolli kohta teha "Toimus arutelu" stiilis menetlusinfo sissekanne, siis saab OTRK dokumendid ja failid selle külge lisada, ilma et peaks eraldi OTRK-ide jaoks sissekande tegema.

**Comment by infokujur** [comment]
Seda peaks menetlusinfos kuvama küll ja kõike seotud ka.

**Comment by moll** [comment]
OTRK tugi lisatud. Praegu jäid silma kaks algatust OTRK-iga:
- https://rahvaalgatus.ee/initiatives/ae0fc2e9-7c69-4d6c-984c-9f09ef03d080#event-445
- https://rahvaalgatus.ee/initiatives/6b8e7472-897a-430f-955a-0726f3c717a5#event-446

Esimese puhul on iga seotud faili pealkiri sama, sest API-s polnud failidele eraldi peakirju määratud. Teise puhul oli. Sünkimise kood võtab sellistel juhtudel pealkirja dokumendi küljest. Muude sissekannete puhul töötab see paremini kui failinimed, mis kipuvad teinekord olema stiilis "12345678N.pdf". Võib-olla tasuks sellistel juhtudeks lisada heuristika, et kui on rohkem kui üks sama pealkirja ja sama tüübiga fail, kuvada failinimesid...

Teisena ei ole OTRK impordis hetkel heuristikat, mis seostaks ta toimunud Riigikogu istungiga ja kuvaks kuupäevana istungi, mitte OTRK-i väljapakkumise kuupäeva. Istungi kuupäeva jaoks peaks saama lisada taas heuristika, mis loeb ta OTRK dokumendiga seotud arutelupunkti dokumendi toimiku pealkirjast. :P Tehniliselt siis OTRK dokument (https://api.riigikogu.ee/api/documents/9188ced0-5a2e-4980-8640-c873e603301d/) viitab `plenaryAgendaItemDocument` dokumendile (https://api.riigikogu.ee/api/documents/5e701da0-ccc5-469f-bcb4-eff5c2ebba32).

**Comment by moll** [comment]
Teen eraldi _issue_ lisafunktsionaalsuse tegemiseks, k.a istungi kuupäeva väljalugemiseks.
