### ISSUE TITLE
Teiste tellitud teavituste näitamine ühe algatuse teavituste haldamise lehel

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#199]
Kuna vähestel on Rahvaalgatuses konto, ei ole hetkel lihtsat võimalust neil näha kõiki algatusi, mille kohta nad teavituse on tellinud. Lihtsa lahendusena otsustamise kuvada iga algatuse teavituse haldamise lehel ka teisi tellitud teavitusi. Teavituse haldamise lingi saab kas teavitust uuesti tellides või teavituse kirja lõpust.

Sellega kaasneb väike privaatsuse riski suurenemine — kui inimene teavituse kellelegi ilma halduslinki eemaldamata edastab, saab saaja näha kõiki tellitud algatusi. Enne nägi ja sai muuta vaid ühte algatust. Arvan, et vaatamata sellele tasub on kõikide nägemine mugavuse ja kasutatavuse poolest parem.

**Comment by infokujur** [comment]
Tehtud ja laivis

**Comment by moll** [comment]
Algatuste teavituste haldamine kõik ühelt lehelt.
