### ISSUE TITLE
Riigikogu OD API implementeerimine 

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#20]
Selleks, et menetlusvaade uueneks automaatselt.

Ootame Riigikogu Kantselei poolt ligipääsu testkeskonnale.

**Comment by moll** [comment]
API dokumentatsiooni näeb https://aavik.riigikogu.ee/api/ems/v1/raml/ems-api-v1.html.
Ühe algatuse API vastus näeb välja selline: https://gist.github.com/moll/36b57533efe1e26fa164e16460a8b6da

Praegu on seal ka vaid kaks algatust:
- Kollektiivne pöördumine Eestimaa kaitseks
- Kollektiivne pöördumine - Peatame veipimise võrdsustamise suitsetamisega

Seotud dokumentide viidetega saab alla laadida nt protokolli PDFi.
Põhimõtteliselt natuke sisukat infot saab kätte. Seotud komisjoni, need paar staatuste muutust kuupäevaga ning vajadusel ka komisjoni andmeid. Komisjoni API annab komisjoniliikmete nimed ja kontaktandmeid.

**Comment by infokujur** [comment]
@moll Teil on olnud arenguid, palun viita siia ka.

**Comment by moll** [comment]
Praeguse seisuga ei saa süsteemselt siduda algatuse menetluse sissekandeid neid tinginud dokumendiga. Võttes näiteks ülaltoodud algatuse (https://rahvaalgatus.ee/initiatives/373edf9a-f39c-4c69-894e-3f1cf043d845), saame API-st (https://aavik.riigikogu.ee/api/ems/v1/collective-addresses?senderReference=373edf9a-f39c-4c69-894e-3f1cf043d845) kätte menetlusse võtmise kohta vaid järgnevad sissekanded:

```json
{
	"statusDate": 1479467597836,
	"statusCode": "REGISTREERITUD",
	"status": "Registreeritud"
},
{
	"statusDate": 1481212705982,
	"statusCode": "MENETLUSSE_VOETUD",
	"status": "Menetlusse võetud"
}
```

Võrdluseks @infokujur-i käitsi lisatud esimene sissekanne (https://rahvaalgatus.ee/initiatives/373edf9a-f39c-4c69-894e-3f1cf043d845), mis sisaldab lisainfoks paragrahvi teksti ja ametikku otsust koos esimehe nimega. Hilisema menetlussissekandega — komisjoni aruteluga — on sama lugu. Kuigi algatuse küljes on nimekiri kõigist temaga seotud dokumentidest, ei saa neid menetlussissekandeid kronoloogiliseks kuvamiseks nendega siduda.

Tegin selle kohta ka RK API repos teema: https://github.com/riigikogu-kantselei/api/issues/5

**Comment by moll** [comment]
Pakuks esimese implementatsiooni teha Rahvaalgatuse koodibaasi ja vajadusel see kunagi CitizenOSi liigutada. Riigikogu API-ga sünkimine võib vabalt selline korra-päevas tüüpi taustaprotsess olla niikuinii.

**Comment by tiblu** [comment]
@moll Ma olen nõus, kuna see on Eesti spetsiifika, siis oleks parem kui Teie meile infot suruks. 24h välp tundub täiesti OK.

**Comment by moll** [comment]
Kinnitan, et uuemad 10 algatust on Riigikogu API kaudu täna kättesaadav. Eelmise aasta tosin+ mitte. Nende kohta uurisin https://github.com/riigikogu-kantselei/api/issues/10 teemas. Muud piirangud seoste vahel on jätkuvalt alles ning https://github.com/riigikogu-kantselei/api/issues vaadates kahjuks ei paista, et palju arengut oleks toimunud. Õnneks aga @infokujur'i teavituse soovi saab ka käesolevaga ellu viia.

**Comment by moll** [comment]
Lihtne riigikogu API kaudu algatuse käekäigu jälgimise lahendus olemas. Meilib hetkel staatuste muutuste, failide lisamise kui ka muu metadata muutuse korral. Kahjuks linke failidele lisada ei saa — vt https://github.com/riigikogu-kantselei/api/issues/13.

Lükkan homme koos värskendatud algatuse vaatega laivi.

**Comment by moll** [comment]
Leidsin alternatiivse failide laadimise aadressi `https://www.riigikogu.ee/download/:id` läbi riigikogu dokumendiregistri: https://www.riigikogu.ee/tegevus/dokumendiregister/.

**Comment by moll** [comment]
Oeh, _deploy'des_ selgus, et Zone'i Node.js'i hostingust ei saa läbi Mailguni e-posti saata. Uurin neilt, kuid niikuinii oli plaan viia RA äpp kokku CitizenOSi API'ga ühte serverisse. Sealt kindlasti saab meilida.

**Comment by moll** [comment]
Rahvaalgatus jooskeb nüüd koos API monitoorijaga samas serveris, kus me CitizenOSi instants. Riigikogu API-t vaadakse 3x päevas. https://github.com/riigikogu-kantselei/api/issues/13#issuecomment-446573489 sõnutsi aga jookseb nende API kahjuks päris andmete koopial ja võib vahel olla kuni kuu aega ajast maas. :/

**Comment by infokujur** [comment]
Miks kuu aega? Kas seda koopiat kuidagi kiiremini uuendama ei saaks panna?

**Comment by moll** [comment]
Heida omalt poolt ka sõna sekka @ https://github.com/riigikogu-kantselei/api/issues/13#issuecomment-446573489. Ehk aitab kiiremini asju liikuma panna. :)

**Comment by infokujur** [comment]
Hakkame omalt poolt nende infot välja näitama. See tuleb järgmise iteratsiooni töödes ära kirjeldada. Kui me saame varem kuskilt info kätte, siis märgime selle eraldi juurde. Eesmärk on autmaatika tööle panna ja tulemus välja näidata.

**Comment by infokujur** [comment]
@moll - see jäi meil kirjeldamata? Võiks kohe töösse võtta. Protokollid jõuavad minuni e-kirjadega pikema aja vältel kui kuu aega. Kasutaja võidab.

**Comment by moll** [comment]
Läheneme loovalt ja kuvame kõik, mida API-st välja suudame lugeda ja interpreteerida. Üritame siduda protokollid ja dokumendid sündmustega, kui ei õnnestu, kuvame ehk niisama kõrvale.

**Comment by infokujur** [comment]
Kuna sealt tulevad kõik algatused, siis tegin #18 aktiivseks. Tuleb see ka korraga ära lahendada.

**Comment by moll** [comment]
#18 on hetkel veel suletud. Mõtlesin aktiveerimise all avamist?

**Comment by moll** [comment]
API sünkimine toetab nüüd ka otsuseid ja kirjasid.

Kirjade näide: https://rahvaalgatus.ee/initiatives/ae292221-8968-4c48-ad8e-71213dba5622
Ainus näide otsusedokumendist: http://rahvaalgatus.test:3000/initiatives/0fa0e375-f817-426d-b3ad-8ae18f780754#event-162

**Comment by moll** [comment]
Riigikogu API sünkimine on olnud laivis nüüd mõned nädalad, käsitleb enamikke dokumente ja tuvastab olulisemad seosed heuristikate abil. Võib _issue_ vist lõpetatuks lugeda, kui sul midagi lahtist meelde ei tule, @infokujur.

**Comment by moll** [comment]
Lisada ka https://opendata.riik.ee/rakendused/ lehele.
