### ISSUE TITLE
Lisada "Hea annetuste koguja" logo ja tekst "Toeta" lehele.

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#205]
https://rahvaalgatus.ee/donate

Tekst:

Annetuse saaja on SA Eesti Koostöö Kogu, kes kasutab kogutud summat Rahvaalgatus.ee ülalpidamiseks. Rahvaalgatus.ee on liitunud [annetuste kogumise hea tavaga](https://heakodanik.ee/annetuste-kogumise-hea-tava/).

**Comment by moll** [comment]
Asendame "Toetajad" sektsiooni nimed logodega ja lisame ka Hea Kodaniku logo.

**Comment by moll** [comment]
Nimed asendatud logodega ja lisatud "Hea Kodaniku" logo.
