### ISSUE TITLE
Autori nimele klikates peaks avanema Avaliku profiili leht

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#21]
Disaini vaade olemas.

**Comment by moll** [comment]
Mõtled Jaanuse kunagi disainitud vaadetest? Andmete osas pole meil sinna praegu vist peale kontaktaadressi ja kõikide autori algatatud algatuste kuvamise muud panna, eks?

**Comment by infokujur** [comment]
Jah. Sinna võiks minna ka avalik hääletamine, kui see CitOS poolt tuleb.
#10 #1 #9 #8 #25

**Comment by moll** [comment]
Lahendame hetkel probleemi märkmete väljaga (https://github.com/rahvaalgatus/rahvaalgatus/issues/54) ning lubame inimesel ise valida, milliseid kontaktandmeid kuvada.
