### ISSUE TITLE
Sotsiaalmeedias levitamise automatiseerimine

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#210]
#168 #178 

Mõistlik on siin teenust kasutada. Samas tuleb vaadata, et pakume kõike, mida teenusega kasutada saab.
Eelkõige jääb puudu visuaalist. Tuleb kaaluda visuaali lisamise lubamist.

**Comment by moll** [comment]
Pärast automatiseerimise konfimist anna kindlasti detailselt teada, millistele Atom-feedi vormingu eeldustele (a la algatuse pealkiri kooloniga eraldatud jne) ja muule automatiseerimise seadistus tugineb. Vastasel juhul võib keegi üht-teist tulevikus Rahvaalgatuses muuta ja seeläbi automatiseerimise lõhkuda või hoopis ta topeltsõnumeid saatma panna.

**Comment by infokujur** [comment]
Iga sissekande juures on vaja selle sissekande pildile viidet. Ta ei mõtle seda ise lingi kaudu välja.

**Comment by moll** [comment]
Mis asi ei mõtle seda ise välja? Mõni spetsiifiline sotsmeedia sait või ainult läbi Zapieri tehtud sissekanded kõigil sotsmeedia saitidel? Milliseid sotsmeedia saite proovisid?
