### ISSUE TITLE
Pildi või logo lisamine algatusele (k.a sotsiaalmeedias jagamiseks)

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#211]
Seotud https://github.com/rahvaalgatus/rahvaalgatus/issues/210.

Mõtlesime paigutada küljeribale.

**Comment by moll** [comment]
Adminniliideses nüüd võimalus lisada kõigile algatustele sotsmeedia eelvaateks pilt. Lisada võib kui suure pildi tahes (suurusepiirang preagu 3MiB), ent sotsmeedia jaoks tehakse tast maksimaalselt 1200x675px suur pilt – 16:9 suhtega. Kui laadida väiksem pilt/logo, siis jääb suurus puutumata. Toetatud hetkel JPEG kui ka PNG. Teisi formaate saab kergelt lisada.

Lisasin näiteks RA logo https://admin.rahvaalgatus.ee/initiatives/1b481b4b-9fe1-496f-9c49-b1697da3810d külge. Facebookis näeb ta välja selliselt: https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Frahvaalgatus.ee%2Finitiatives%2F1b481b4b-9fe1-496f-9c49-b1697da3810d.

Algatuse lehe küljeribal pilt veel ei kajastu. See kui ka algataja muutmise võimalus tuleb peatselt.

**Comment by infokujur** [comment]
Oluline lisa, mis on jäänud mainimata. Pildil võiks olla _watermark_ rahvaalgatus.ee.

**Comment by infokujur** [comment]
Tegin uue issue watermark teemaga.: https://github.com/rahvaalgatus/rahvaalgatus/issues/222

**Comment by moll** [comment]
Pilti kuvatakse nüüd algatuse küljeribal, kus algataja saab seda ka vahetada või eemaldada. Nt https://rahvaalgatus.ee/initiatives/42880cae-dc30-46b4-863f-26b795086bef või https://rahvaalgatus.ee/initiatives/8a31585f-d7c6-4009-8833-fb5bf80a02d1.
