### ISSUE TITLE
Kollektiivne digiallkirjastatud avalik kiri e ühisavaldus

### ISSUE THREAD

**Issue by jaanusnurmoja** [rahvaalgatus/rahvaalgatus#218]
Tunnen puudust keskkonnast, kus oleks võimalik kirjutada traditsioonilisi avalikke kirju / ühisavaldusi neid digiallkirjastades. Põhimõtteliselt on seda võimalik juba praegu teha eesti.ee portaalis, aga seal on see mitmel põhjusel liiga keerukas. Samuti pole praegu võimalik kokku sulatada mitut identse sisu, kuid erinevate allkirjadega bdoc või asice konteinerit. 

Erinevus kollektiivsetest pöördumistest seisneks vähemalt järgnevas:

- allkirjade alampiir oleks kaks allkirja

- allkirjastanute nimed oleksid avalikult nähtavad ning lisanduksid tekstile nii veebivaates kui ka digiallkirjastatud konteineris olevale pdf failile, kujul Eesnimi Perekonnanimi (mitte PEREKONNANIMI,EESNIMI,ISIKUKOOD)

- kui vajalike inimeste allkirjad koos, saab koostaja allkirjastamise lukku panna või anda (teatud ajaks) võimaluse ühinemiseks ka teistele. Täiendavad ühinejad saaksid valida, kas nende nimi peaks olema avalikult nähtav või mitte. 

- adressaati või adressaate saaks koostaja ise valida (või jätta valimata)

- vallida saaks ka meediaväljaannete või väljaannete rühmade (nt kõik üleriigilised, kõik maakonnalehed) vahel, kuhu avalikust kirjast teatada

- soovi korral saaks koostaja täita ka nö pressiteate vormi (pealkiri ja tekstiala), kus ta võtab avaliku kirja lühidalt kokku. Sel juhul läheks see pressiteate sisu ainult meediaväljaannetele, sellele järgneks avaliku kirja täistekst. 

- meediaväljaannetele läheks avaliku kirja tekst puhta tekstina e-maili sõnumikehas koos lingiviitega originaalile, teemaks oleks mõistagi pealkiri

- kindlasti võiks siia loetellu lisada veelgi funktsionaalsusi, aga piirdugem praegu nendega. 

Võib-olla saaks kasutada juba olemasolevat avaliku pöördumise vormi. Sel juhul peaks kasutaja valima, kas ta tahab koostada avalikku pöördumist (min 1000 allkirja, adressaadiks riigikogu, menetlemiskohustus jne) või avalikku kirja / ühisavaldust (min 2 allkirja, tavaline märgukiri jne). 

Aga kui ma saaksin ülaltoodud funktsionaalsuse ise oma saidil luua kasutades siinset koodi, siis ma heameelega prooviksin :)

**Comment by infokujur** [comment]
See teemapüstitus on jäänud teenimatult vahele. Vaatame regulaarselt projekti vaadet https://github.com/rahvaalgatus/rahvaalgatus/projects/4 ning oleme harjunud, et peale meie siin keegi teemasid ei ava. Vabandan.

Vastuseks: Siin on palju aspekte. Toon mõned välja.

1) Ra.ee muutub järjest paindlikumaks. Oma aeglases rütmis, kuid areneme pidevalt. Kui algatajaid lisandub ja neil on konkreetseid ettepanekuid, siis proovime täiendada. A'la pressiteate vorm vms.

2) Hakkame kaardistama kohalikku 1% õigust. Algus on tehtud: https://kohalik.rahvaalgatus.ee/
Seal tulevad erinevad lävendid ja erinevad adressaadid.

3) Allkirjastajad hoiame anonüümsed. Põhiline argument hetkel - avaldamine ei ole tagasipööratav. Ja see teema vajaks väga põhjalikku arutelu. Nt situatsioon, kus algataja survestab kedagi allkirjastama. Sõnades deklareerimine on võimalik nii ehk naa.

4) Meie kood on avatud ja vaba kasutamiseks. Siin piirangut ei ole. Toetame omalt poolt erinevate tööriistade teket ja levikut. Ra.ee ülesanne on anda ülevaadet ühest kodanikuõigusest, seda täitvad instrumendid võivad olla erinevad ning konkurents on hea, sest mõjub üldisele kvaliteedile hästi.
Küll on aga vaja selgelt kirja panna kellele kopeeritud leht kuulub ja kuidas käideldakse andmeid (kes näeb ja mis nendega teeb).

**Comment by jaanusnurmoja** [comment]
Avalikku kirja ei saa võrrelda nende praeguste avalike pöördumistega. Avaliku kirja puhul ei eeldatagi, et selle edastajad tahaksid olla anonüümsed. Ettevalmistusperiood on lühike ja sisu tavaliselt päevapoliitiliselt aktuaalne. Neid saadetakse meediaväljaannetele ja vahel isegi avaldatakse sõnasõnaliselt ning siis on ju kõikide allkirjastanute nimed all. Reeglina lepivad nad ka omavahel selle tekstis enne kokku. 
Asja mõte on mugavama ühisallkirjastamisplatvormi pakkumine traditsiooniliste avalike kirjade koostamiseks. 
Muide, siit üks mõte. Kui kirja autorid leiavad, et see võiks koguda veel rohkem allkirju, siis neile uutele allkirjadele peaks andma nö peidetud staatuse. Mõistagi kuluks ära ka võimalus "konverteerida" see avalik kiri kodanike avalikuks pöördumiseks, kusjuures siis, kui seda tehakse muutmata kujul, jääksid ka esialgsed allkirjad alles.

**Comment by infokujur** [comment]
Seda käsitletakse menetlemisel märgukirjana. Osaliselt tegeleme nende küsimustega siis, kui hakkame lahendama küsimust, kuidas viidata organisatsioonid.

**Comment by infokujur** [comment]
> 
Mõistagi kuluks ära ka võimalus "konverteerida" see avalik kiri kodanike avalikuks pöördumiseks, kusjuures siis, kui seda tehakse muutmata kujul, jääksid ka esialgsed allkirjad alles.

Ka praegu saab Riigikogu kantseleile esitada allkirju mitmest allikast. Võib koguda avalikud allkirjad ühel platvormil ja 900+ kaitstud identiteediga allkirja ra.ee platvormil. Siin on algatajal vabadus valida tööriista. 

Hetkel me märgukirja ei paku ja tehnilist lahendust konvertimiseks ette ei näe, kuna hoiame allkirjastaja identeedi kaitstud.
