### ISSUE TITLE
Lisada kõikide algatuste number esilehele

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#219]

**Comment by infokujur** [comment]
![esilehe_stat_täiendus](https://user-images.githubusercontent.com/12999094/69638643-c0c27e80-1063-11ea-9fa6-c4b080d49f76.png)
Nagu midagi sellist. Detailsem statistika tuleb ka, aga see vähendab praegust segadust vähekenegi.

**Comment by moll** [comment]
Punktid eemaldame ka fraaside lõpust.

**Comment by moll** [comment]
Laivis lihtsama fraasiga ja punktideta.

**Comment by moll** [comment]
Või tegelikult juba möödunud aastast laivis, ainult punktid jäid eemaldamata. :P
