### ISSUE TITLE
Jalusest ja päises info parandada

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#220]

**Comment by infokujur** [comment]
Esilehele õige aadress > A.Weizenbergi 30, 15050 Tallinn

Abi lehe päis ja jalus esilehe järgi õigeks.

**Comment by moll** [comment]
Jalus ja päis kohendatud. Muud käsitleme https://github.com/rahvaalgatus/rahvaalgatus/issues/64 raames.
