### ISSUE TITLE
Kohaliku Rahvaalgatuse lehe demo

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#223]
Demolehel võiks olla Eesti haldusjahotusega kaart, kus saab _zoomida_ kohalikule omavalitsusele. A la https://juhtimislauad.stat.ee/dashboard/6.

Algatuse loomise puhul võtaks ära viisardi, ehk looks uue algatuse kohe peale "Loo uus algatus" nupu vajutust. Abiteksti paneks algatuse muutmise lehele. Avalikustamise nupu juurde kinnitus, kas oled "hea tavaga" tutvunud.

Lisada vaja ka algatuse saaja valik (vastuvõtja) — Riigikogu või mõni Eesti valdadest.

**Comment by infokujur** [comment]
Domeenil kohalik.rahvaalgatus.ee

**Comment by infokujur** [comment]
Kohalike omavalituse elanike arv iga aasta 1.01 seisuga: http://andmebaas.stat.ee/Index.aspx?lang=et&DataSetCode=RV069U

**Comment by moll** [comment]
Too (http://andmebaas.stat.ee/Index.aspx?lang=et&DataSetCode=RV069U) väljavõte ei tundu mulle KOVide lõikes rahvaarvu kuvavat. Rahandusministeeriumi lehel on lihtne rahvaarvu ja KOViga tabel, küll aga möödunud aasta jaanuarist: https://www.rahandusministeerium.ee/et/eesmargidtegevused/kohalikud-omavalitsused-ja-haldusreform/eesti-kohalike-omavalitsuste-loetelu.

Kahtlustan, et tahtsid ehk mõnele teisele Statsikaameti lehele viidata. Seal liigeldes ei paista brauseri URL õigesti uuenduvat. Lähim, mis silma jäi, oli http://andmebaas.stat.ee/Index.aspx?DataSetCode=RV028U (Aastakeskmine rahvastik. haldusjaotus seisuga 01.01.2018), kuid see on veel vanem kui Rahandusministeeriumi oma.

Piirmäär, mida jahime, tuleneb seadusest https://www.riigiteataja.ee/akt/13312632?leiaKehtiv#para32, eks? Ehk teisisõnu miinimum 1% _ja_ 5 inimest:

>   (1) Vähemalt ühel protsendil hääleõiguslikel valla- või linnaelanikel, kuid mitte vähem kui viiel hääleõiguslikul valla- või linnaelanikul on õigus teha kohaliku elu küsimustes valla- või linnavolikogu või -valitsuse õigusaktide vastuvõtmiseks, muutmiseks või kehtetuks tunnistamiseks algatusi, mis võetakse arutusele hiljemalt kolme kuu jooksul.

**Comment by infokujur** [comment]
@moll Meil oleks vaja saada see valimisõigulik 1% (16+ aastat) number kätte. Seadus õige. Viitame alguses sellle RAM-i lehele ja ma ajan täpsemaks. Rahvastikuregistrist pärimine tundub overkill. Suurusjärgu saab kätte ja sellest MVP jaoks piisab.

**Comment by moll** [comment]
Praegu parem allikas kui Rahandusministeeriumi tabel silma ei jäänud. Vast on variant ka otse Statistikaametilt küsida. Kindlasti kuskil selline info peidus.

https://kohalik.rahvaalgatus.ee demo on aga üleval. Puudu on esilehelt kaardi graafika ja algatuste juurest vastutava võimu/KOVi märge (nii esilehel kui algatuste lehel _mitte autori_ jaoks). Algatajana saad aga saaja määramist demoda:

![Screenshot from 2020-01-06 23-58-22](https://user-images.githubusercontent.com/156837/71857717-7ad7ec00-30e0-11ea-8f0b-5286de0d61d3.png)

Terminoloogia ("algatuse saaja"), abitekstid ja muu osa lahtine. Puudu on ka allkirjade määrad. Senisega saad aga ehk kohtumisel idee edastatud. Puuduvate detailideni jõuan ilmselt homme (ehk täna). 
 
Kui näeme ette, et keegi varst lisab ka mõne päris kohaliku algatuse, tuleks otsustada, mida "Saada parlamenti" valikuga teha. Peidame, kuniks kohalike algatuste protsessi kava selgem?

**Comment by moll** [comment]
Mõtlemispunkt on ka määramata saajaga diskussioonid. Hea oleks neile linkide ja otsingumootorite tarbeks määrata _üks_ aadress (nt ülddomeen). Muidu hakkab otsingumootoritesse ilmuma kas kaks linki iga diskussiooni kohta, _või_, hullemalt, hakkab mõni otsingumootor ühte saitidest teise duplikaadiks pidama ja peidab selle täiesti. Kui aga määramata saajaga diskusioonid praegu ülddomeenile suunata, võib see külastajale segadust tekitada, sest saidid on visuaalselt eristamatud, kuid kuvavad esilehel ja "algatuste" lehel erinevat sisu. Pakun, et tuleks navigatsioon selliselt välja mõelda, kus kahe domeeni vahel liikumine probleeme ei tekita.

**Comment by moll** [comment]
Otsustasime hetkel suunata sihtpunktita ja Riigikogule suunatud diskussioonid rahvaalgatus.ee ülddomeenile, kuid kohalikule omavalitsusele suunatud diskussioonid jätta kohalik.rahvaalgatus.ee lehele. Lehtede päiste ja menüüdega tegeleme hiljem, kui mõni kohalik algatus ilmub.

Faaside, hääleõiguslike kodanike arvu ja kogu kohaliku algatuse protsesside kohta teeme eraldi _issue_-d.

**Comment by moll** [comment]
Sihtpunktita algatused suunavad nüüd ülddomeenile ja kohalikule valitsusele suunatud algatused jällegi alati kohalik.rahvaalgatus.ee lehele.

Lükkan homme laivi.
