### ISSUE TITLE
Peamenüüs viidata Abi > http://help.rahvaalgatus.ee/abi

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#224]

**Comment by moll** [comment]
Tehtud. Eeldasin, et tahtsid samalaadset muudatust ka inglise ja vene keelsetele linkidele.
Lingid ise on konfifailis (https://github.com/rahvaalgatus/rahvaalgatus/blob/095618ad7421fd30d8dc4629bf9b1f0fbf1e95fa/config/index.json#L48-L52), kui vaja üle vaadata.
