### ISSUE TITLE
Kohalike omavalitsustele algatuste saatmise protsess ja faasid

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#227]
https://github.com/rahvaalgatus/rahvaalgatus/issues/223 jätkuks.

Demo käigus lisasime kohalik.rahvaalgatus.ee lehe ja võimaldasime luua KOVidele suunatud algatusi. Peale allkirjade kogumise aga ei ole meil järgmisi samme. Tuleks välja mõelda, mida allkirjade künnise ületanud algatustega teha, kellele nad saata ja kuidas algatuse faase kuvada.

**Comment by infokujur** [comment]
Saadetud, Menetluses, Järelkaja

Lävend on erinev - kuidas see lahendada? @moll 
Seadusest vaadata tähtajad @infokujur

**Comment by moll** [comment]
Teavitused ja menetlusinfo tekstid ka selle valguses üle vaadata.

**Comment by moll** [comment]
Funktsionaalsus peaks olema valmis — teavitustekstid on kohandatud KOVide jaoks ning lävendid käsitsi uuendatavas tabelis. KOVile saatmise nupp ilmub alles siis, kui KOVide tabelisse on lisatud meiliaadress, kuhu algatus saada.

https://github.com/rahvaalgatus/rahvaalgatus/issues/264 tulemusel saame ehk rahvastikuarvu uuendama hakata.

Korra tasuks üle vaadata, kuidas https://www.riigiteataja.ee/akt/13312632?leiaKehtiv#para32 lõike tõlgendada. Kas saadetud algatusele on aega vastata kolm kuud või üks kuu? Või kolm kuud aega vastamiseks ja esmaseks arutamiseks, ning kui arutelu tulemusel ollakse ettepanekuga nõus, vaid üks kuu edastamiseks?

**Comment by infokujur** [comment]
Teine > Kolme kuu jooksul peavad arutama ja siis sellest arutelust kuu, et toimuks järgmine arutelu volikogus.

**Comment by moll** [comment]
Uuendasin `SENT_TO_LOCAL_GOVERNMENT_MESSAGE_BODY` ja `SENT_TO_LOCAL_GOVERNMENT_CONTENT` tekste, et need viitaks kolmele kuule. Mujal me hetkel kohalike omavalitsuste kolme kuu tähtaega ei maini ega välja näita.
