### ISSUE TITLE
Etherpadi sisumallid – Aruteluteema vaiketekst ja pikkuse limiteering

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#23]
Arutelu/algatuse teksti sisestuse juurest puuduvad struktureerivad lahtrid: algatuse pealkiri, ettepaneku lühike kokkuvõte, ettepanek, probleemi selgitus või taustinfo, vaba tekstiväli (selle 7000-midagi tähemärgipiiranguga) - Jannusel on vajalikud pealkirjad olemas

Kehtestada juba mallis järgmine hääletatava teksti struktuur: Pealkiri
Lühike (u 350 tähemärki) või säutsu-lühike (140 tähemärki) sisukokkuvõte – see oleks mõeldud selleks, et algatusi platvormis ja sotsiaalmeedias paremini kajastada
Ettepanek – mida tahetakse muuta
Põhjendus – miks see on oluline
Kokku maksimaalselt 12 000 tähemärki

Minu arvestuse järgi on leheküljetäis teksti 3000 tähemärki ilma vahedeta.
Teksti sees eraldaks ma Ettepanekud ja Põhjendused ainult eeltäidetud malli kaudu (kujunuse täiendus lk 02d Create - step 4 - blank page.) aga arvestaks tähemärke kogu sisuteksti peale kokku. Lubaks siiski 12 000 tähemärki lootuses, et struktuur pidurdab grafomaane.

**Comment by moll** [comment]
Saame küll asendada Etherpadi kolme tavateksti kastiga, kuid otsustamise hetkel selle vastu.

**Comment by infokujur** [comment]
Teen selle lahti - tekstiredaktor teemaks.

**Comment by moll** [comment]
Jätame hetkel tähemärkide lugemise ja mallid kõrvale ning toetume tulevasele kooskõlastusringi funktsionaalsusele kui sisu pikkuse ja kvaliteedi filtrile.
