### ISSUE TITLE
Kõikide teavituste tellinute arv algatuse juures. Praegu jääb mulje, et mõne algatuse uuendamise teade ei lähe mitte kellegile.

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#239]

**Comment by moll** [comment]
Oleneb, mis jälgijate numbri eesmärk on. Mu meelest on ta rohkem huvi ja populaarsuse indikaator. Kõikide algatuste jälgijate arv iseenesest aga algatuse huvi ei näita. Näiteks su ["Pole kunagi digiallkirjastanud"?](https://rahvaalgatus.ee/initiatives/a3adaaaa-207e-4816-9479-c7f61e3e33da) algatusest ei ole 77 inimest huvitatud, vaid ainult üks — ilmselt mina, kes testis teavitusi. Ainult umbes kolmandikul algatustel on üldse keegi jälgijaks. Selle põhjal ütleks, et oluline on jätta algatuse jälgijate arv eraldi ja vältida situatsiooni, kus jääb mulje, et algatus on sama populaarne kui kõikide algatuste jälgijate arv. Nüüd on lihtsalt küsimuse all, kas ja kuidas "kõikide" arv seal juures välja tuua.

Ma isiklikult ei näe sel veel mõtet, küll aga on sul mõni hea sõnastus välja pakkuda, kuidas seda kuvada? Lihtsalt lisada "Kõikide algatuste jälgijaid 77" on mu meelest segane, sest lause "Algatuse jälgijaid 1 ja kõikide algatuste jälgijaid 77" paneb mind küsima, mida "kõiki algatuste jälgijaid" tähendab? Kas kogu saidi algatuste peale on vaid 77 jälgijat kokku? Teine potentsiaalne sõnastus oleks "Algatuse jälgijaid on 1 ning kogu saidi jälgijaid 77", kuid "kogu sait" või "terve sait" võib ka ebaselge sõnastus olla. Enamikel algatustel (u kaks kolmandikku) pole tegelikult ühtki jälgijat ja kuvada oleks vaid globaalsete jälgijate arv. Hetkel aga ei kuvata sellisel juhul midagi, sest ma ei pidanud vajalikuks või isegi "kenaks" jälgijate puudumist rõhutada. Kui lisada globaalsete jälgijate arv, tuleks selgitada, et see ei tähenda huvi konkreetse algatuse vastu, mis omakorda võib viia jälgijate puudumise rõhutamiseni.

Kahtlustan, et mida populaarasemaks Rahvaalgatus läheb, seda ebatõenäolisem on, et kõiki algatusi korraga tavainimesel jälgida tasub. Viimase 10 kuuga on juurde tulnud vaid u 20 inimest, keda kõik algatused huvitavad.

**Comment by infokujur** [comment]
Meie mõte on olla info edastamisel täpne.
Lause > Seda algatust jälgib juba [27] inimest sj läheb teavitus veel [77] inimesele, kes on tellinud teated kõikide algatuste kohta.

**Comment by moll** [comment]
Sõnastus võiks olla nõnda, et see oleks grammatiliselt korrektne ka 0 ja 1 juhtumi puhul. Isegi kui eesti keelt eraldi käsitleda ja eraldi fraasid "1" käänetega lisada, ei piisa sellest vene keele jaoks. Lihtsam on nii sõnastada, et käänet ei ole.

"Algatuse jälgijaid on 0" mõtlesid sisse jätta? Mis su seisukoht selle rõhutamise või rõhutamise vältimise osas on, millest keskmises lõigus kirjutasin?

**Comment by moll** [comment]
Käiku läks fraas "kogu saiti jälgib", sest "kõikide algatuste jälgijaid on X" tähendus kipub olema "kõikide individuaalsete algatuste jälgijate summa".
