### ISSUE TITLE
E-mail notifications of parliament processing events

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#24]
#20

**Comment by infokujur** [comment]
Vajab meiliteavituste tuge.

Kas lahendatakse #8 selle raames?

**Comment by infokujur** [comment]
Sõltub: Internal events and user2user messaging
https://docs.google.com/spreadsheets/d/1tOiV6hAtLH4aQYaXm-TR3tK9jMV70tlzSq3lpyZJYp4/edit#gid=0

**Comment by moll** [comment]
Teeme ühes https://github.com/rahvaalgatus/rahvaalgatus/issues/78'ga Rahvaalgatuse poole uue menetlussissekande sisestamise peale.

**Comment by moll** [comment]
Nagu https://github.com/rahvaalgatus/rahvaalgatus/issues/20 kirjutasin:
> Lihtne riigikogu API kaudu algatuse käekäigu jälgimise lahendus olemas. Meilib hetkel staatuste muutuste, failide lisamise kui ka muu metadata muutuse korral. Kahjuks linke failidele lisada ei saa — vt https://github.com/riigikogu-kantselei/api/issues/13.
>
> Lükkan homme koos värskendatud algatuse vaatega laivi.

Sulgen selle issue ja jätkan #20 -s.

**Comment by infokujur** [comment]
ok
