### ISSUE TITLE
Digiallkirjastamise harjutamise leht 

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#240]
Mõte on teha `/digiallkiri` leht digiallkirjastamise harjutamiseks. Näiteks koolides noortega kasutamiseks. Lehele jätame vaid ülemise Rahvaalgatus logo ja keelevaliku. Viited algatustele jm-le eemaldame. Sisuks jääb õpetusega video, selgitav lõik ja kolm allkirjastamise meetodit. Peale allkirjastamise valikuid ka statistika, mitu korda on allkirjastamist harjutatud.

Allkirju peaks saama pärast allkirjastamist natuke aega ka alla laadida, kuid pikaajalist allkirjade säilitamist ei ole plaanis. Allkirjastamisele läheks esialgu sama sisutekst, mida lehel näha. Sisutekst ja video tulevad @infokujur poolt mingi hetk. Enne seda võib aga demo-demolehe üles panna.

**Comment by moll** [comment]
Pärast allkirja enda kustutamist võiks säilitada soo ja sünnipäeva aasta ning kuu. Sellega kaasnevalt ka kellaaja, millal allkirjastati, ja meetodi (Id-kaard, Mobiil-Id).

Enne ja pärast allkirjastamist võiks kuvada ka platvormi toetamise võimalust. @infokujur poolt tekst. Toetades võiks toetusele juurde märge, et tegemist oli kodanikuhariduse toetamisega.

Mõtleme mingile graafikule või loendurile ka, mida all kuvada. Tõenäoliselt arv päevade lõikes.

**Comment by moll** [comment]
Funktsionaalsed nupud koos allkirja allalaadimisega laivis @ https://rahvaalgatus.ee/digiallkiri.
Küljendusele ei tasu veel palju keskenduda. Sellega tegeleme, kui mõtted sisust paigas. Lisasin digiallkirjastamise lehele lihtsalt https://kestame.rahvaalgatus.ee stiilis päise ja Aino fondi. Sisuks "lorem ipsum" täiteteksti nii /digiallkiri kui ka "allkirjastatud" (mida kuvatakse pärast edukat allkirja) lehel.

"Toeta" sektsiooniks on "allkirjastatud" lehel hetkel sama vorm nagu päris allkirjade juures. Sellegi sisu pidime kohandama. /digiallkirja läbi tehtud toetused saavad juurde kirjeldusse `for=education`. Kui tahate muud märget, anna teada. Too haakus lihtsalt `person=38706...` isikukoodi formaadiga. Enne allkirja oli ka plaanis toetamise võimalus, nagu rääkisime.

Hiljuti allkirjastanute statistika näidet veel pole. Lisan esialgu tavatekstina meeldetuletuseks ja kui kujunduseks läheb, teeme vajadusel graafikuks.

**Comment by infokujur** [comment]
Graafikut on vaja nagu rääkisime. Sisu tuleb hiljem, hea oleks kohe tegelema hakata, et hiljem kiireks ei läheks.

**Comment by moll** [comment]
Viimaste päevade allkirja juurde ka graafik 16–20 aastaste allkirjastajate vanustest kuu täpsusega, nii et saaks eristada 16a ja 1 kuu vanuseid 16a ja 6 kuu vanustest.

**Comment by moll** [comment]
Tekstid on praegu kahes failis:
- https://github.com/rahvaalgatus/rahvaalgatus/blob/master/locales/et/demo_signatures.md
- https://github.com/rahvaalgatus/rahvaalgatus/blob/master/locales/et/demo_signatures_sign.md

"_sign" järelliitega failis allkirjastamise sektsiooni tekst. Sõltuvalt, kuidas küljendus jääb-tuleb-muutub, võib ka tekstide jaotus failides muutuda, kuid vaatamata sellele, https://github.com/rahvaalgatus/rahvaalgatus/blob/master/locales/et/ kaustast leiab nad alati üles.

**Comment by infokujur** [comment]
Palun viita esilehelt ka. Selle teema siin võib kinni panna, kui konkreetsed uued küsimused, avame uued issued https://github.com/rahvaalgatus/rahvaalgatus/issues/247

**Comment by moll** [comment]
Teeme nii. Lisan hommikul https://github.com/rahvaalgatus/rahvaalgatus/issues/246 -st ka viiteid ja midagi mõtlen kahe graafikuga välja.
