### ISSUE TITLE
Viimaste algatuste info Rahvaalgatuse API kaudu

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#241]
Lisaks avalikustatud üldstatistikale (https://github.com/rahvaalgatus/rahvaalgatus/blob/master/openapi.yaml) lisame võimaluse pärida viimase _n_ päeva jooksul enim allkirju kogunud algatusi ja viimati täiendatud menetlusinfoga algatusi. 

Lisame ka API kasutamise näidise, kus on nt viimase 7 päeva jooksul enim allkirju kogunud algatused koos pealkirjade ja allkirjade arvuga, ning viimased ~5 algatust, mille menetlusinfot on täiendatud. Võib olla ka koos menetlusinfo pealkirjaga.

**Comment by moll** [comment]
https://rahvaalgatus.ee/api lehel on üleval näiteid API kasutamisest kui ka milliseid infokastikesi sellega teha saab. Tehtud on näiteid nii viimase 7 päeva jooksul allkirjastatud algatuste jaoks kui ka ilma duplikaatideta menetlusinfodest. API päringuid tuleks parajalt optimeerida. Hetkel võtab API näidete leht kokku vist oma hea 5 sekundit ja see on pisut palju. Ehk mõned andmebaasi indeksid aitaks. Kindlasti saab aitama ka https://github.com/rahvaalgatus/rahvaalgatus/issues/230. 

@infokujur:
> Palun pane esimesse lausesse praegu esilehel olevate algatuste arvud.

Sa ilmselt viitad sellele, et esilehel kuvatakse "arutelusid 220" ja "algatusi 107", kuid API ja näide vastavalt 113 ja 68. See toob meid tagasi tollal esilehe koondarvude teema juurde (https://github.com/rahvaalgatus/rahvaalgatus/issues/176#issuecomment-531594684), kus otsustasime, et esilehe etappide numbrid sisaldavad ka hilisemate faaside algatusi:

@moll:
> Lahtine on ka, mis terminiga kõiki loodud algatusi nimetada. Ülal kavandites kutsun neid "aruteludeks", kuid pole veendunud, et teistele on selge, et see sisaldab kõiki loodud algatusi, k.a neid, mis pole enam arutelud ehk ühisloome faasis. "Algatuse" terminiga on sama häda — see peaks tähendama algatusi, mis liikusid allkirjastamisse, isegi kui nad enam pole allkirjastamises. Kutsuda neid faasi järgi "Allkirjastamises" oleks sama vale kui kutsuda "arutelusid" "ühisloomeks". Teisest küljest, ehk joonte/noolte kasutamine on piisav vihje, et tegemist on teekonnaga, kus paremale jäävad numbrid ja algatused pärinevad vasakul olevatest.

Kuna näitelause on "Arutelu käib 113 idee üle ja toetust koguvad 68 algatust", siis ütleks, et pisut segane on siin kuvada kõikide algatuste numbreid. Variant oleks ümber nimetada esimene osa "Algatusi kokku" ja teine "allkirjastamiseni jõudnud" näiteks. "Toetust koguvad" on muidugi umbmäärane ja võib tähendada, et need ülejäänud Riigikokku jõudnud 39 algatust koguvad ka "toetust"...

**Comment by infokujur** [comment]
Ma mõtlen, et selles lauses oleks arvud praegu sellised:
Arutelu käib 7 idee üle ja toetust koguvad 10 algatust.

Ehk täpselt need numbrid, kus inimesel on kohe praegu võimalik osaleda ja on esilehel reas (mitte need kogu arvud, mis on üldstatsis).

**Comment by moll** [comment]
Ma sõnastaks selle ümber algatuste omaduste järgi. Sa ilmselt mõtled siis algatusi, mille arutelu või allkirjastamise tähtaeg ei ole saabunud, eks? Esileht on meil juba iseärasusi täis ja filtreerib kohati veel ka siltide alusel. Sellised iseärasused ei sobi API-sse.

**Comment by infokujur** [comment]
Kui nii on hea, siis las olla, et tähtaeg ei ole saabunud.
Lause selline nagu öeldud.
"Arutelu käib 7 idee üle ja toetust koguvad 10 algatust."

**Comment by moll** [comment]
Uuendan kohe sõnastuse, aga täpsustan tähtaja osas. Mõtlesid seega, et lubame API kaudu pärida statistikat ka selliselt, et saaks tuvastada ühisloome ja allkirjastamise faasis olevate algatuste arvu, millel on tähtaeg veel tulevikus? Ja's näite teeme sellega?

Mõtlen valjult, mis sellise klassifikatsiooni termin võiks API-s pärimiseks olla... Tähtaeg on lõpuks termin, mis kehtib ka Riigikogu faasis, kuid seal on see üpris paindlik — esialgu vastamistähtaeg, siis komisjon ja kes teab, mis pärast.

**Comment by infokujur** [comment]
Jah

**Comment by moll** [comment]
Sõnastus juba klappis. Nüüd lisatud API-sse ka aktiivsete arutelude ja allkirjastamises olevate algatuste numbrid, mida siis API näide kasutab. Praegusega 6 arutelu ja 11 allkirjastamises.
