### ISSUE TITLE
Etherpadi väljavahetamine

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#242]
Plaan on välja vahetada Etherpadi tekstiredaktor millegi lihtsamaga, mille väljund ei oleks HTML ja mis töötaks hästi ka mobiilis. Oluline on uuel lahendusel ka muudatuste ajalugu, et algataja saaks vajadusel varasemaid versioone taastada. Küljendusfunktsionaalsusest kulub esialgu ära vaid paar pealkirja taset, rasvane ja kaldkiri, loend ja lingid.

Lahtine on, kas varasemate versioonide puhul tuleks näidata ka võrdlust praegusega, stiilis nagu Wikipedia seda teeb.

**Comment by moll** [comment]
Uus redaktor on testkeskkonnas katsetamiseks olemas möödunud nädalast, kuid olen vahepeal kohendanud ta stiile, lisanud automaatteste ning katsetanud mobiilis. Kõikide võimalike stiilidega näitetekst asub https://next.rahvaalgatus.ee/initiatives/ecacbe57-04d4-48b5-8398-f2cfac0fbeea. Seda saab muuta Smart-Id demokasutajaga. Sisselogimiseks piisab https://next.rahvaalgatus.ee/sessions/new lehel isikukoodi "10101010005" sisestamisest.

Esialgu kasutab süsteem vanade arutelude puhul Etherpadi edasi, kuid uued arutelud luuakse juba ilma CitizenOSi andmebaasi sissekannet tegemata. Kõik allkirjastamisele läinud algatuste tekstid on juba varasemast meie andmebaasis, kuid arutelu ajal hoiti tekste veel Etherpadi käes. Kui redaktor laivis, impordime CitizenOSi andmebaasist ka need tekstid. Järgmine kord muutes kuvatakse vana tekst siis juba uues redaktoris. Küljendus jm kandub enam-vähem üle, ainult värvid kaovad ja mitmetasandilised (H2–H6, nagu Etherpad neid nimetas) pealkirjad asendatakse tavalise pealkirjaga. Kuna iga muudatus salvestatakse uue versioonina, jääb ka CitizenOSist imporditud versioon meie andmebaasi alles ja vajadusel saab käsitsi hiljem korrektuure teha.

Vanade versioonide vaatamiseks veel kasutajaliidest ei ole.

Puudu on teksti pikkuse piiramine ja seda eriti kasutajasõbraliku loenduri näol. Pikkuse piirangu lisamine pole nii kerge kui võib arvata, sest struktureeritud formaadist tehakse HTML alles serveris. Ka pole uut algatust luues algatusel vaiketeksti. See pole ehk esialgu probleem, sest enam ei hoita algatuse pealkirja tekstis.

Üldiselt võiks algatuse muutmise lehest teha klassikalisema muutmise lehe, kus on rohkem kui üks vormielement ja väljade juures on ka seletav tekst. Sinna saaks paigutada nt ka pealkirja välja ühelauselise seletusega, kuidas kirjutada head pealkirja. Algatuse teksti elemendi juurde aga väikese lõigu, mis nõuetele peaks tekst vastama, kuidas seda vormistada ja kust sügavamat lisainfot leida. Arvan, et kontekstipõhine info on tunduvalt parem kui vaid eraldi abileht. Ka saaks nii ehk algatajal protsessi lihtsamaks teha. Praegu on pealkiri ühes, tekst teises, tähtaeg kolmandas ja lisainfo muutmine neljandas kohas.

**Comment by moll** [comment]
Editor näeb välja hetkel siis selline:

![Screenshot from 2020-05-04 08-23-48](https://user-images.githubusercontent.com/156837/80947916-a8a81580-8de0-11ea-88d9-4c9d535bf658.png)

**Comment by infokujur** [comment]
Jah

Kontakt Andri Möll (<notifications@github.com>) kirjutas kuupäeval E, 4.
mai 2020 kell 11:24:

**Comment by moll** [comment]
Möödunud nädalast laivis ja paar sellega tehtud algatustki juba avalikustatud.
