### ISSUE TITLE
Tõlke tekstide eraldi hoidmine

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#243]
Praegu kasutatakse samas tekstis mõlema teksti kuvamist.
Riigikogu ei võta vastu teksti, mis on tõlkimata.

**Comment by moll** [comment]
Vajab kindlasti lahendamist, kuid käsitleks seda edasi https://github.com/rahvaalgatus/rahvaalgatus/issues/146 teemas.
