### ISSUE TITLE
Menetluse lõppemine Riigikogus

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#244]
Praegu me ei saa seda infot automaatselt kätte?
Menetlus lõpetatakse Vastuskirjaga.  Aga siis peab kirjast lugema, mis sellega edasi saab ja käsitsi selle liigutuse tegema.

**Comment by moll** [comment]
Riigikogu API-s on algatustel staatus. Kui see määratakse kas `TAGASI_LYKATUD` või `MENETLUS_LOPETATUD` staatuseks, salvestatakse algatusele Riigikogu menetluse lõpukuupäev. See kajastub menetlusinfos kui ka faasijoonel. Kui staatusemuutust pole, on meil veel heuristika, mis üritab seotud dokumentide pealkirjast staatusemuutusi tuletada. "Vastuskiri" on üks selleks heuristikaks, kuid seegi ei ole nii lihtne, sest iga vastuskiri ei ole aga menetluse lõpp. Riigikogul on tihti kombeks oma väljaminevaid kirju "vastuskirjadeks" kutsuda. :P

"Tehtud" faasi algatusi automaatselt aga ei liigutata, sest menetluse lõpp ei tähenda, et algatus ei liikunud edasi valitsusasutusse. Seda ei oska API-st hetkel välja lugeda ja nõnda vajab meie ülevaatamist.

**Comment by moll** [comment]
Kas saan menetluse lõpu küsimuse osas veel midagi kirjeldada või võib _issue_ sulgeda?

**Comment by infokujur** [comment]
See tähendab, et kõik algatused tuleb käsitsi üle vaadata ja siis vastavalt liigutada kas Valitsusasutuse või tehtud faasi?

**Comment by moll** [comment]
Kahjuks, jah, tuleb käsitsi üle veenduda, kas algatus lõppeski Riigikogus, või läks edasi valitsusse.
