### ISSUE TITLE
Digiharjutamise lehele näited, kus noor saab e-ID kasutada

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#246]
Lisan juurde e-keskkonnad, mida mina õpilastele koolis olen tutvustanud:

1. EIS

2. SAIS

3. Kaitseväeteenistus.ee

4. Digilugu.ee (digiregistratuur on miski, mida olen neile lähemalt tutvustanud)

5. EMTA

6. Eesti.ee 

7. eteenindus.mnt.ee

**Comment by infokujur** [comment]
Artiklist:
Näiteid, kus digiallkirjastamisest, st digiminast ei saa üle ega ümber:
• Seda on vaja näiteks elukoha registreerimiseks rahvastikuregistris (noortel võib seda kohe vaja
minna, kui ülikooli õppima asudes elukoht muutub), sest paljud avalikud teenused (nt tasuta
ühistransport) on elukohaga seotud.
• Samuti saab digimina e-maksuametis tuludeklaratsioon esitada (näiteks selleks, et õppemaksult
tulumaksu soodustust saada jne).
• Patsiendiportaalis näeb digimina abil oma terviseandmeid (sh saatekirju, analüüside vastuseid ja
haiguslugusid).
• Digimina on vaja valimistel hääletamiseks. Samuti vajadusel kollektiivseks pöördumiseks
riigikogu poole.
• Milliseid e-teenuseid noored digiminad veel kasutada saavad, näeb Eesti riigi infoportaalist:
https://www.eesti.ee/et/.

**Comment by moll** [comment]
Kas lingid-näited paneme pärast allkirjastamist nuppe? Või alles kogud neid ja vaatame hiljem?

**Comment by infokujur** [comment]
See võiks olla jah pärast allkirjastamise kohta. Täiendame jooksvalt.

---
E-keskkonnad, kus saad oma e-ID kohe päriselt kasutada:
-
-
---

Ja peale seda võiks olla tagasiside küsimise nupp, tänu millele avaneb UV.

---
Sul tekkis mõtteid või ettepankuid? Kirjuta meile!
---

**Comment by moll** [comment]
Liigutasin su üleval paste'tud näited https://opleht.ee/2020/03/kodanikuopetus-kuidas-kahe-minuti-ja-kolme-nupuga-digimina-selgitada%EF%BB%BF/ artiklist digiallkirjastamise harjutamise lehe lõppu. Tekstid https://github.com/rahvaalgatus/rahvaalgatus/tree/master/locales/et kaustas. Tegin ka asutuste nimed linkideks.

UV avamise asemel panin meiliaadressi. Arvan, et see on parem suhtluskanal kõigile kui UV popup. Sinna võib vajadusel juurde panna ka Facebook Messengeri lingi (mis suhtleb Rahvaalgatuse FB lehega) või's Twitteri.
