### ISSUE TITLE
"Harjuta digiallkirjastamist" nähtavale kohale

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#247]
Võiks olla päises.
Tõstame #kuidasmekestame ja Uue eakuse rahvakogu jalusesse.

Ma hakkan nüüd KOV teemaga tegelema, siis saab peamenüü uue loogika nii ehk naa rohkem süvenemist.

**Comment by infokujur** [comment]
Siis saab selle allkirjastamise "algatuse" ka kinni panna.

**Comment by moll** [comment]
Liigutasin kõik logod jalusesse ja lisasin navigatsioonimenüü stiiliga "Harjuta digiallkirjastamist" nupu päise paremasse serva. Mobiilides ja muudes kitsastes ekraanides liigub ta navigatsioonivalikutega kokku. Tunduvalt rahulikum päis mu meelest kui koos saja logoga. :)
