### ISSUE TITLE
Allkirja allalaadimine

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#248]
Uute (Undersign.js-ga tehtud) allkirjade puhul oleks mõistlik lubada inimesel peale allkirjastamist ka allkirja alla laadida. Nii kaua vähemalt, kuni ta meil alles on. Funktsionaalsus on telgitaga olemas, lihtsalt link puudu.

**Comment by moll** [comment]
Praegu kuvatakse allkirja kustutamist ka sisseloginud inimestele, kuid vaid nii kaua, kuni algatus on allkirjastamise faasis. Siin tasuks ilmselt mõelda, mida hilisemas faasis kuvada. Kuna plaan on peale Riigikokku saatmist allkirju kustutama hakata, poleks meil enam teada, kes mida allkirjastas. Alati on võimalus muidugi allkirja konteiner kustutada, kuid allkirjastamise fakt alles jätta, ent see on võrdne teadmisega, et keegi allkirjastas.

**Comment by moll** [comment]
Allkirja allalaadimisnupp on nähtaval vahetult peale allkirjastamist ja sisseloginud inimestele alati — vähemalt nii kaua, kuni allkirja hoiame. Laivis homme.

**Comment by infokujur** [comment]
Citizeni kaudu allkirjad ei ole näha. Kui küsitakse, siis jagame.
