### ISSUE TITLE
Allkirjastajate kuva - anonüümne vr nimeline. Algatajal võimalik näha kõiki.

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#25]
#9

**Comment by moll** [comment]
@infokujur otsustab ja ootab juristi hinnangut.

**Comment by infokujur** [comment]
Hetkel algatajal ei ole võimalik näha. Kohandame GDPR-i siin nii, et ei saa olema võimalik.
Kui otsus tuleb, et saab näidata, siis igal juhul ei saa see olema tagasiulatuv (nõusolek vajalik).
