### ISSUE TITLE
Haldusjaotuse kaart osalusvõimalusega

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#253]

**Comment by moll** [comment]
Ei õnnestunud nii lihtsalt täiesti staatilist (nt eelgenereeritud SVG) kaarti luua ning otsustasin [Leafleti](https://leafletjs.com) JavaScripti teegi kasuks, mis lubab kaardil navigeerida, zoomida ja tooltippe teha. Aluskaart põhineb [Maaameti andmetel](https://geoportaal.maaamet.ee/est/Ruumiandmed/Haldus-ja-asustusjaotus-p119.html). Nende kaardil on omavalitsuste geomeetria juures EHAKi kood, mistõttu lisasin selle klapitamiseks ka meie tabelisse.

Demo on nähtaval https://kohalik-next.rahvaalgatus.ee/ lehel.

Panin kaardi praegu eraldi sektsiooni, ning mitte tervituslõigu kõrvale. Kaardil on 79 omavalitsust ning need on ka suurel kaardil niigi väikesed. Esialgne mõte oli meil kuvada osalusvõimalusi märgistega. Hetkel on osalusvõimalustega omavalitsused lihtsalt siniselt ning alale vajutades näidatakse lisainfot. On võimalus märgiseid kuvada vaid sisse zoomides. Ilma zoomita, vaikimisi, aga kahtlustan, et ei loe sealt suurt midagi välja. Isegi Tallinn on tilluke tervet kaarti vaadates, Rakverest, Viljandist ja väiksematest saartest rääkimata.

Tõin kaardi alla välja ka tabelis maakondade kaupa osalusvõimalustega omavalitsused. Kuna hetkel päris võimalused on uurimisel, lisasin mõnele näidisandmed. Ka on osalusvõimaluse kategooriad illustratiivsed. Demoks lisasin "rahvaalgatused" ja "kaasav eelarve".

**Comment by infokujur** [comment]
Igas omavalitsuses on võimalus osaleda. Küsimus on selles vaid - kuidas. Ehk kaardil navigeerides on vaja osalusvõimalus tuua kliki kaugusel. Kuidas seda lahendada?

**Comment by moll** [comment]
Õigus, 1% teema oli kõigil. Mõtleme midagi kindlasti välja, aga käiks korra läbi, mis infot kuvada vaja tasuks? Vajalike allkirjade arv rahvaalgatuseks tundub ühe tükina. Mis veel? Kaasa eelarve sisendi korjamise perioodi all mõtled, et on paar kuud aastas, kus inimene saab kaasa rääkida? Mõtled neid kuupäevi kuvada ja ehk lingiga kohta, kus sisendit anda saab?

**Comment by infokujur** [comment]
Seda saab kõike keerulisemaks ajada. Alustame järgmste sammudega

1%:
1) omavalitsuse IS pakub võimalust - link sinna,
2) ra.ee peal on algatused - link nendele,
3) midagi ei ole - loo ise ra.ee peal.
kaasav eelarve:
1) kaasav eelarve on/ei ole
2) omavalitsuse IS pakub võimalust - link sinna,
3) omavalitus on meile esitanud ajakava - tõstame esile perioodid, kui palutakse sisendit (ideede esitamine, hääletus)

Lisaks on veel muud osalusvõimalused - planeeringud, küla ja kandikogud jm ühistegemised. Seda võiks välja tuua viidetena omavalitust kirjeldavad lõigus. Kui tekib üldistamise võimalus, siis toome kaardile.

**Comment by infokujur** [comment]
AF-i skoop.

Hüpikus:
KOV nimi, kogu elanike arv ja lävend.

Linnukesega > Link
Tekst: Rändnäitus „Kodukoha kompass“
Url: https://www.kogu.ee/kodukoha-kompass/

Nupud > Loo algatus ja Vaata algatusi (kui neid on, sellel KOV-il)

Kaardil:

KOV on tumesinine, kui seal on algatusi.
KOV peal on beež mumm, kui seal on näitustuur planeeritud (12 KOV-i) > https://www.kogu.ee/rannugraafik/ https://github.com/rahvaalgatus/rahvaalgatus/issues/270

**Comment by moll** [comment]
Kas mõtlesid kaardil välja tuua kõik plaanitud näitusega KOVid, või ikka vaid need kolm (Paide, Rakvere, Narva), kuhu ta päriselt praegusega rändab?

**Comment by moll** [comment]
Seotud https://github.com/rahvaalgatus/rahvaalgatus/issues/270.

Laivis.
