### ISSUE TITLE
Algatuse juurde lisatud visuaalide juurde lahtiütleja ning väli - viide autorile/allikale

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#255]
Abitekst:
Algataja vastutab pildi üles laadimise eest. Palun veenduge, et teil on olemas pildi autori poolt selleks antud luba.

Palun lisada väli:
Viide autorile või allikale

**Comment by moll** [comment]
Pildile saab nüüd juurde lisada autori nime, vajadusel litsentsi ja lingi. Autori saab välja tuua pärast pildi lisamist. Enne pildi lisamist aga rõhutatakse, et lisajal peab olema pildi autori luba selle levitamiseks.

Peale esmast lisamist näeb algataja pildi all võimalust autori lisamiseks:
![Screenshot from 2020-06-19 08-36-45](https://user-images.githubusercontent.com/156837/85114281-5001d000-b208-11ea-9866-8b99640461e8.png)

Tulevikus tahaks algatusega seotud info haldamise viia eraldi lehele. Seal saaks pikemalt vajadusel autoriõiguse seadust lahti seletada. Kuna Rahvaalgatuse puhul on tegemist poliitiliste lehtedega, siis tuleb algatajal ettevaatlik olla, kas autor lubab end pildi juures mainida või mitte. 

Autor nime ja linki lisades kuvatakse see pildi all:
![Screenshot from 2020-06-19 09-00-36](https://user-images.githubusercontent.com/156837/85115547-63626a80-b20b-11ea-9149-93a0f0d1b369.png)

Vajadusel saab lisada autori nime juurde ka litsentsi nime, aga ma ei ole täheldanud litsentse, mis nõuaks litsentsi enda mainimist teoste juures. Üldiselt piirdutakse autori nimega/viitega. Nime lisamise juures tuleb aga tähele panna [autoriõiguse seaduse §12](https://www.riigiteataja.ee/akt/128122011005?leiaKehtiv#para12), mis lubab autoril oma nime mainimist reguleerida või keelata. Kuna on võimalik, et pildi autorit võidakse kogemata seostada algatusega, siis poleks uskumatu, kui mõni autor seda õigust ka kasutab. Lisasin seostamise riski vähendamiseks nime ette prefiksi "Pildi autor", nagu ülal näha.

Lahtine küsimus on, kuidas pildi autori nime ja ja litsentsi sotsmeedia kontekstis lahendada. Kahjuks ei tea hetkel seal pildi autori mainimise võimalust. Kindlam oleks vast, kui algatusele lisatud pildid autorile viitamist ei nõua (kas siis avaliku litsentsi läbi või autori ja algataja kokkuleppel). Vastasel juhul ei pruugi pildi levitamine autori soove järgida.

Kui saab midagi täiendada, anna teada! Fraasid kõik tõlketabelis.

**Comment by infokujur** [comment]
Palun lähtume sellest siin > https://et.wikipedia.org/wiki/Vikipeedia:Piltide_kasutamine

**Comment by infokujur** [comment]
Muutsin sõnastused tõlketabelis täpseks. Igal pool autor/litsents vaja paralleelselt mainida.
Palun viita praegu kasutatud viited algatuste juures
Tekst: Pixabay License Link: https://pixabay.com/service/license/

**Comment by moll** [comment]
"Autor/Litsents" prefiksina on päris pikk ja lükkab kõik mitmele reale. Miks mitte jätta lihtsalt "Autor" ja vajadusel viidata litsentsile, kui see on avalik? Või siis ehk lisada eraldi väli litsentsi URLile, kui tahame seda enda tarbeks andmebaasis hoida. Üldiselt mu meelest autorid ei kohusta litsentsile viitamist, vaid pigem autori nimele ja *autori* kodulehele. Näiteks Unsplash, üks teine populaarne _stock photo_ sait, palub viidet autori profiilile/lehele (https://unsplash.com/license), mitte litsentsile endale. Wikipediat aluseks võttes, nad ei too ka litsentsi (ega üldiselt ka autorit) tavalises vaates välja. Alles lisakliki peale.

Ok, lisan "Pixabay" vanematele algatustele, kuigi irooniliselt nad viitamist ei nõua. :P

**Comment by moll** [comment]
Lükkasin uue teksti laivi ja lisasin "Pixabay" vanematele lisatud piltidele.
Üks selline nt: https://rahvaalgatus.ee/initiatives/c79c1938-dc37-439e-9e5b-9033c534239b

Linkisin siiski Pixabay kodulehele, sest nt Creative Commons litsentsi enda "Best Practices" rõhutab alati esimesena autorile viitamist. Küll aga mulle üllatusena mainitakse, et viitamist nõudvad Creative Commons litsentsid tahavad _peale_ autori ka _eraldi_ litsentsi nime ja viidet. Hakkan vaikselt kahtlustama, et kas tuleks nõuda tõesti vaid CC0 litsentsiga pilte (mis ei nõua midagi) või keelata piltide üleslaadimine. Pildi laadimine tundub juba nagu Maksuameti vormide täitmine. :P

**Comment by infokujur** [comment]
Kõik pildid ongi CC0, et võiks ka viitamata jätta. Aga küsimusi on rohkem kui vastuseid. Võtame aluseks Wikimedia käsitluse ja loeme selle teema ra.ee jaoks lõpetatuks.

**Comment by infokujur** [comment]
Palun viita nii nagu palusin ja sulge uuesti teema.

**Comment by moll** [comment]
Oki, URLi <https://pixabay.com/service/license/>-ks muudetud.
