### ISSUE TITLE
Kuhu kuvada argumendid, kui algatus on hääletamisel/menetluses?

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#26]
Hetkel on backendis vaid üks vorm kommentaare algatuse kohta ehk diskussiooni argumente ja hääletuse kommentaare lahus hoida ei saa.

**Comment by moll** [comment]
Disainis oleme need vist praegu koondanud "kommentaarideks" ja samad kommid nähtaval esialgu diskussiooni ja siis hääletuse faasis.

**Comment by infokujur** [comment]
Jah, see oli quick fix. Samas hea oleks ikkagi eraldada need argumendid/kommentaarid, mis lisanduvad eri ettappides. Arutelu ajal ja allklirjastamisel ja miks ka mitte menetluses. Ehk lahendame koos menetlusinfo vaatega kui OD API Riigikogu Kantseleist tuleb.

#20

**Comment by moll** [comment]
Citizen peab siin ka lisama kommentaaridele faasi toe. See oli mu meelest pool aastat tagasi ka jutuks. Veel ei ole tehtud, eks, @tiblu?

**Comment by tiblu** [comment]
@moll Jah, mingi hetk oli arutelul, et kas kommentaarid peaks kuuluma kindla etapi juurde ehk siis iga etapp saaks oma kommentaariumi. Arutelu uppus kuhugi filosofeerimise sohu. Kokkuvõttes mul ise-enesest pole selle vastu midagi, Kokkuvõttes peab Margo (@loorm)  otsustama, millal ja kas me seda teeme.

**Comment by infokujur** [comment]
Praegu olemas samad kommentaarid igal pool. Tulevikus vastavalt staatusele tuleb tagasi teema.
