### ISSUE TITLE
Riigikogu ja KOVide algatused eraldi alamsaitidele ning ühine esileht

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#261]
Asendame "algatused" peamenüüst "Riigikogu" ja "Kohalik" linkidega, mis suunavad vastavalt  [riigikogu.rahvaalgatus.ee](riigikogu.rahvaalgatus.ee) ja [kohalik.rahvaalgatus.ee](kohalik.rahvaalgatus.ee) lehtedele. Logo suunab tagasi ühislehele <rahvaalgatus.ee>. Ühisel lehel kuvame kõiki algatusi, teistel vaid suunatud algatusi.

Lihtsustame ühislehe tervitusteksti ja lisame joonise protsessist. Ühisele esilehele lisame ka hiljuti aktiivsed algatused, otsngukasti ja lingid Riigikogu algatuste, KOVide algatuste või arhiveeritud algatuste vaatamiseks. Statistika juures asendame "Riigikogus" sõnaga "Saadetud" ja võtame ka KOVide numbreid arvesse. Riigikogu lehele ([riigikogu.rahvaalgatus.ee](riigikogu.rahvaalgatus.ee)) jääb aga statistka alles nagu praegu.

Algatuste lehe muudame rohkem arhiivileheks, kus on näha kõik algatused koos esialgsete filtreerimisvõimalustega. Näiteks sihtkoht (Riigikogu/mõni KOV). Arhiivilehe küljendame rohkem tabelina, et pikka lehte oleks kergem lugeda.

**Comment by moll** [comment]
https://github.com/rahvaalgatus/rahvaalgatus/issues/15 raames suuname Riigikogule suunatud algatuste lingid <riigikogu.rahvaalgatus.ee> domeenile. Nii saab ühendada domeeni suunamine numbriliste id-de ja inimloetavate URLide suunamistega.

**Comment by moll** [comment]
Küljendasin algatuste/arhiivilehe hetkel selliseks: https://rahvaalgatus.ee/initiatives. Kuidas tundub? Filtrid tulevad peatselt. Kas võiks iga algatuse real veel mingit infot kuvada peale praeguse? Sihtkohata algatustel puhul jäi veel lahtiseks, kas tühi ruum vasakul ülal pealkirjaga täita või sinna midagi muud asemele panna.

**Comment by moll** [comment]
Koondlehe video on graafiku vastu vahetamata, kuid ootaks sellega, kuniks Kaspar disaininäidised ära teinud.

**Comment by infokujur** [comment]
Üldlehele:
![RA(3)](https://user-images.githubusercontent.com/12999094/89651790-1cb8f480-d8cd-11ea-8d0a-6b623e50451e.png)

**Comment by infokujur** [comment]
**Riigikogu lehele**
Pealkiri: Algatused Riigikogule
Tekst: Selle lehe kaudu saad Riigikogule koostada ja esitada kollektiivseid ehk vähemalt 1000 digiallkirjaga pöördumisi ning jälgida, kas algatused saavad seaduseelnõudeks. 

**Kohalikule lehele**
Pealkiri: Algatused kohalikule omavalitsusele
Tekst: Kohalikule omavalitsusele on õigus teha ettepanekuid vähemalt 1% hääleõiguslikel elanikel.
