### ISSUE TITLE
Sotsiaalmeedia (FB) feed esilehele

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#262]
https://www.facebook.com/EestiKoostooKogu/
https://www.facebook.com/rahvaalgatus/

**Comment by infokujur** [comment]
Või #rahvaalgatus agregatsioon @moll palun uuri, mis FB API võimaldab.

**Comment by moll** [comment]
@infokujur poolt ligipääs Zapieri kontole.

**Comment by moll** [comment]
Avalike postituste otsimine tundub olevat aastaid tagasi kinni pandud — https://developers.facebook.com/docs/public_feed. Lähim API postituste saamise soovile, mis hetkel leidsin, on lehe _tagged_ päring, kust saavat lehte maininud inimeste postitusi: https://developers.facebook.com/docs/graph-api/reference/page/tagged/. Selle API kasutamine vajab mitte ainult FB äpi registreerimist (mis meil juba on), vaid ka vastutava organisatsiooni Facebooki registreerimist ja lepinguid. Kui seda tegema hakkate, vaadake väga kriitilise pilguga üle, millele alla kirjutate. Olen varem osade API lepingutega kokku puutunud ja seal nõuti täiesti absurdseid ja ebaseaduslikke asju — a la ligipääsu serverile "auditeerimiseks". Neile võib alla kirjutada vaid siis, kui hiljem on julgust nad oma lepinguga seenele saata. ;) 

Ma hetkel ei leidnud Rahvaalgatuse Facebooki lehelt üldse kohta, kust sildistatud postitused välja paistaks. Teavituste lehel (https://www.facebook.com/rahvaalgatus/notifications) esinevad üksikud sellised viitega postitused. Ilmselt ka seepärast, et lehele õigesti viitamine on lisasamm ja tülikam, kui lihtsalt tekstis Rahvaalgatuse mainimine. FB enda otsingu kaudu leiab küll rohkem Rahvaalgatust mainivaid postitusi — https://www.facebook.com/hashtag/rahvaalgatus  — kuid siiski mitte paljusid. Ega Facebook pole ka lõpuks avalikuks aruteluks, vaid pigem tuttavate keskis suhtluseks.

**Comment by infokujur** [comment]
Mõtlesime asja ümber.
Tuleb kogu.ee Uudiste feed. 
Uudise küljes on pealkiri, kuupäev, pilt, märksõna(d). Mõelda läbi, kus seda infot kuvada "Hiljuti aktiivsed" algatused sektsioonis esilehel.

Hiljem kogu.ee uuendatakse. Tuleb siis vajadusel kohendada.

**Comment by moll** [comment]
Liikus edasi https://github.com/rahvaalgatus/rahvaalgatus/issues/271 teemasse.
