### ISSUE TITLE
Hiljuti aktiivsed kasti info täiendamine

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#265]
Kasti lisada info - millega oli hiljuti aktiivne. 
Probleem, mida lahendame - kui algatus on loodud nt aastal 2016, siis see kuupäev on eksitav - inimene loeb ja mõtleb - kuidas küll see hiljuti aktiivne sai olla.

**Comment by moll** [comment]
Eemaldasin hiljuti aktiivsetelt algatustelt kuupäeva kuvamise, kuna tõesti polnud selge, mille kohta see käib. Lisasin algatuse kasti alla ka selgituse, mis aktiivsus algatuse juures hiljuti oli.
