### ISSUE TITLE
Jaluses uus EKK logo - kõik alalehed + abileht

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#266]
![KOGU_logo_peamine_transparent](https://user-images.githubusercontent.com/12999094/89021123-ae05f500-d328-11ea-850a-c1c1ce337f40.png)

**Comment by moll** [comment]
Kas sellest inglisekeelne variant ka on?

**Comment by moll** [comment]
Logo muidu Rahvaalgatuses ja abilehtedel vahetatud.

**Comment by infokujur** [comment]
Veel ei ole ENG varianti.
