### ISSUE TITLE
Initiative categories

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#27]
Praegu uuseakus ja arvamusfestival lisatakse käsitsi. Võiks olla läbi UI

**Comment by moll** [comment]
Uus Eakusel oma alamleht — mis kategooriad seal kasutuses? Rahvaalgatus.ee-l endal, ütleks, veel liiga vähe algatusi, et kategoriseerimisse investeerida. :)

**Comment by infokujur** [comment]
Jah, praegu oota, kas uuel eakusel tekib vajadus. Ra.ee peal tõesti vähe kategooriaid. Samas me ei tea veel, kuidas seda välja näidata. Ehk kuidas funktsionaalsust rakendada. Võib-olla selleks, et näidata mis viisil meneltused lõppevad / arvamusfestiavli ja rahvakogu protsessi algatuste eraldamiseks jne On hold praegu.

**Comment by infokujur** [comment]
@moll Kas siin uuseakus.rahvaalgatus.ee visuaali raames oli arengut?

**Comment by infokujur** [comment]
#49

**Comment by moll** [comment]
Uus Eakuse visualisatsiooni raames sai kategooriatega tutvust tehtud, kuid Rahvaalgatuse lehele tagasi sealt hetkel midagi ei ole liikunud. UE jaoks sai algatused seotud kategooriatega läbi andmebaasi, sest sel hetkel (ja minu teada ka täna) polnud võimalik läbi Citizeni API uusi kategooriad luua. 

Kui otsustame, et RA-le sobivad esialgu Citizeni nn *hard code'itud* kategooriad, siis võime midagi välja mõelda. K.a filtreerimise võimalus kas esilehele või algatuste lehele.

**Comment by infokujur** [comment]
See juba osaliselt tehtud - AF ja paberallkirjad saab juurde panna läbi admin liidese.
