### ISSUE TITLE
"Kodukoha kompass" märge kohalike omavalitsuste kaardile

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#270]
Valdadel, kuhu kompass jõuab, kuvame roosat ringi sarnaselt https://www.kogu.ee/kodukoha-kompass/ stiilile.

Popup akna sisse linnuke "Kodukoha kompass"-ile viitega https://www.kogu.ee/kodukoha-kompass/ lehele.

Roosa toon tuleb @infokujur -lt.

**Comment by infokujur** [comment]
Kogu tuur on siin - selle saab juba kaardile kanda > https://www.kogu.ee/rannugraafik/

**Comment by infokujur** [comment]
Beež > Pantone 148 CC = 0 M = 30 Y = 48 K = 0 R = 251 G = 193 B = 146
Sinine> Pantone 2728 CC = 100 M = 90 Y = 10 K = 0 R = 0 G = 90 B = 167

Kujunduses kasutada veel 50 % ja 20 % tint versiooni. Vaata kumb parem kaardil näeb välja. Sinise saad ka juba ülaltoodu järgi panna.

Ra.ee ikooni töös tuleb värve juurde.

**Comment by moll** [comment]
> Kas mõtlesid kaardil välja tuua kõik plaanitud näitusega KOVid, või ikka vaid need kolm (Paide, Rakvere, Narva), kuhu ta päriselt praegusega rändab?

Kõik 12.

**Comment by moll** [comment]
Teeme roosasid ka pisut erksamaks.

**Comment by moll** [comment]
Lisasin ülejäänud 9 näitusekohta ka omavalitsuste tabelisse. Mõne puhul tuleb välja natuke kohmakas KOVi keskkoha määramine. Nt Jõhvi indikaator on Jõhvi polügoni keskel, kuid Jõhvi keskel asub Kohta-Järve KOV:

![Screenshot from 2020-08-11 18-25-06](https://user-images.githubusercontent.com/156837/89934377-01692480-dc00-11ea-8994-4aa8d675449e.png)

Kaardiandmetes polnud KOVi keskkohta paigas ning kaarditeegi keskkoha leidmise funktsioon leiab selle naiivsel meetodil, mis kumerate polügonide puhul võib selle polügonist väljapoole jätta. Tulevikus võib uurida, kas leiab kaardiandmetele käsitsi paigutatud keskkohad või parema funktsiooni.

Roosadele andsin silma järgi värvi juurde. Vaata, kuidas tundub — https://kohalik.rahvaalgatus.ee.

Välja jäi hetkel viidatud Pantone 2728 CC, sest see on tumedama sinisega RA juures liiga ergas. Kui kord värvipalett paigas ja peamenüüd ka teises sinises, muudame toonid sobivaks.
