### ISSUE TITLE
Eesti Koostöö Kogu uudistevoog Rahvaalgatuse esilehele

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#271]
Praegu mõtleme panna peale "Hiljuti aktiivseid" algatusi.

**Comment by moll** [comment]
Näide: https://next.rahvaalgatus.ee

"Uudised" tundus momendil parem pealkiri kui "sündmused", sest "sündmused" jätsid mu meelest rohkem mulje üritustest või kalendrist kui Rahvaalgatust puudutavatest uudistest. Kogu enda leht kutsub neid ka uudisteks.

Praegu uudistefiltrit ei ole ehk kõik Kogu uudised laetakse sisse ja kuvatakse viimast 5. Saaks kuvada ka viimast 8-t, et desktopis rida täis oleks, kui see tähendaks, et mobiilis oleks veel rohkem kerida...

Kas tasub uudise autori nime ka näidata nagu praegu?

**Comment by infokujur** [comment]
Need kastid on liiga algatusega sarnased. Hea oleks teha midagi sellist, mis ei võta rohkem ruumi kui otsinguala. Saame Uudised ees kasutada EKK logo (ja riba taust 25% roosa nagu visuaalses identiteedis) seniks, kuni tuleb filter ja täpsemad disainijuhised.

**Comment by moll** [comment]
Kuidas selline tundub?

![Screenshot from 2020-08-14 22-11-32](https://user-images.githubusercontent.com/156837/90296611-7e540280-de7b-11ea-97b8-05899fdecdf0.png)

Oranž taust kahjuks ei lähe sinna mu meelest küll kuidagi.

Demo https://next.rahvaalgatus.ee lehel.

**Comment by infokujur** [comment]
Kõige viimane variant - töösse :).

**Comment by moll** [comment]
Laivis. Hetkel sünkitakse uudiseid iga 4 tunni tagant. Kui vaja tihedamini, anna teada!
