### ISSUE TITLE
Hiljuti aktiivsed lisada ka menetlusinfo uuendatud, meediakajastus lisatud, kommentaar lisatud

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#274]
Mis seal praegu on? Ma neid teisi ei ole hiljuti näinud.

**Comment by moll** [comment]
Praegu on allkirjastamine ja kommentaarid. Kommentaare lihtsalt eriti tihti ei tehta, et need põhjuseks ilmuks. :) Viimane kommentaar on 5. augustil.

Menetlusinfo lisamine on ka hea mõte. Lisan.

**Comment by moll** [comment]
Nüüd ilmuvad hiljuti aktiivsete algatuste hulka ka algatused, kuhu on lisatud menetlusinfot. Kaasamine tugineb menetlusinfo meie andmebaasi lisamise hetkel. See võib erineda ajahetkest, mil sündmus ise aset leidis — nagu menetlusse võtmine või mõni tulevane komisjoni arutelu.
