### ISSUE TITLE
Kaarti täiendada osalusvõimalustega

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#275]
1%:
- omavalitsuse IS pakub võimalust - link sinna,

kaasav eelarve:
- kaasav eelarve on/ei ole
- omavalitsuse IS pakub võimalust - link sinna,
- omavalitus on meile esitanud ajakava - tõstame esile perioodid, kui palutakse sisendit (ideede esitamine, hääletus)

Lisaks on veel muud osalusvõimalused - planeeringud, küla ja kandikogud jm ühistegemised. Seda võiks välja tuua viidetena omavalitust kirjeldavad lõigus. Kui tekib üldistamise võimalus, siis toome kaardile.

Vaadata RAM AVP tegevuskava raames tehtavat rakendust. Eeldatav esitlus augusti lõpp 2020.

**Comment by infokujur** [comment]
Esitlus 25.08 ja peale seda üle vaadata kogutud info üle.

**Comment by infokujur** [comment]
RAM lehega seotud ülesanded: https://github.com/rahvaalgatus/rahvaalgatus/issues/282

**Comment by moll** [comment]
Kaardile on vahepeal ilmunud Demokraatia töövihikus osalevad KOVid jms. Ülejäänud lisab jooksvalt.
