### ISSUE TITLE
Viidata iga omavalitsuse hüpikusse viide RAM lehelt

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#281]
Nt Alutaguse valla kohta

Kiri: Vaata ülevaadet teenuste kohta
Link: https://minuomavalitsus.fin.ee/et/kov/alutaguse-vald

**Comment by moll** [comment]
Lisasin hüpikaknasse "Ülevaade teenuste tasemetest" lingi RAMi lehele. Ei tahtnud seda lihtsalt kutsuda "ülevaade teenustest", sest see viitaks rohkem riiklike ja vabaajategevuste loendile, kust elanik saab nädalavahetuse plaane teha. RAMi lehel on aga lihtsalt küsitluste tulemused.

**Comment by infokujur** [comment]
Palun pane mouse-over versiooni ka.

**Comment by moll** [comment]
On mõtet? Ta oleks ju kõikidel KOVidel ja seega ei annaks mingit infot edasi.

**Comment by infokujur** [comment]
On mõte, sest suure ekraani taga ei taipa klikkida ja ei näe, et selline ülevaate saamine on võimalik.

**Comment by moll** [comment]
Lisatud.
