### ISSUE TITLE
Ikoonide uuendamine Rahvaalgatuse lehel 

### ISSUE THREAD

**Issue by orgkadri** [rahvaalgatus/rahvaalgatus#285]

**Comment by moll** [comment]
Kus need ikoonid-pildid asuvad?

**Comment by moll** [comment]
Esilehe visand asub https://xd.adobe.com/view/88523a26-9abc-42c3-84e5-c98ec4fbbd2f-dd01/.

**Comment by orgkadri** [comment]
Kaspar on ilmselt unustanud need kaasa panna. Palun tal seda teha.

**Comment by orgkadri** [comment]
Need leiab paremalt poolt </z nupule vajutades avanevas jaotisest "Assets". 
![image](https://user-images.githubusercontent.com/70175655/94110009-917aca80-fe4a-11ea-84f7-28d4c44b9df1.png)

**Comment by moll** [comment]
Mu küsimus oli tehtud ajal, kui eelnev Adobe XD link polnud minuni jõudnud. :)

**Comment by moll** [comment]
Esilehe ja algatuse lehe faasijoone ikoonid said nüüd värskendatud.
