### ISSUE TITLE
Algatuse esitaja muutmine 

### ISSUE THREAD

**Issue by orgkadri** [rahvaalgatus/rahvaalgatus#286]
Algatajal võimalus end algatajate seast kustutada (kui algatus on veel arutelufaasis), juhul kui lehel on registreeritud ka kaasalgataja(d).

**Comment by orgkadri** [comment]
Vajab kaasautorite lehele nt mingi nupu lisamist, millega saab juba kaasautoriks lisatud inimese määrata... "algatajaks"? "Eestvedajaks"? Selle peale tuleb [tehniliselt] kaasautor määrata algatuse külge ning eelnev algataja panna kaasautoriks. Lõpuks saab kaasautor end ise algatuse küljest eemaldada või jääda vaid kaasautoriks.

**Comment by moll** [comment]
Tehtud, kuid veel mitte laivis.

**Comment by moll** [comment]
Lubame ka allkirjastamisefaasis.
