### ISSUE TITLE
Tagi lisamine Arutelule/Algatusele - # (social mentions)

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#29]
#19

**Comment by infokujur** [comment]
Saadaval Twitteri feed.

**Comment by infokujur** [comment]
Ma ei tea, miks see minu peal on. Palun täpsusta @moll, kui mul on õige põhjus ununenud.

**Comment by moll** [comment]
Tundub, et 12. juunil ta endale määrasid. :) Lahedasime hetkel https://github.com/rahvaalgatus/rahvaalgatus/issues/54 raames läbi märkmete. Uhkemad sotsmeedia integratsioonid jäävad tulevikku.

**Comment by infokujur** [comment]
ok
