### ISSUE TITLE
Harjuta digiallkirjastamist alalehel kirjeldus ja fail, millele allkiri antakse 

### ISSUE THREAD

**Issue by orgkadri** [rahvaalgatus/rahvaalgatus#291]
"Minu esimene allkiri" vm vm

**Comment by orgkadri** [comment]
Muudatused tehtud nii sõnede tabelis kui ka digiallkirjastamise alalehe teistes sisutekstides.

**Comment by moll** [comment]
See on vahepeal tehtud saanud ja laivis.
