### ISSUE TITLE
Rahvaalgatus.ee tiimile kommenteerimise võimaluse loomine 

### ISSUE THREAD

**Issue by orgkadri** [rahvaalgatus/rahvaalgatus#294]
Kommentaari kirjutamise hetkel salvestada kommentaari juurde märge, et selle tegi admin — peida alati nime, isegi kui autor enam admin pole. "Märke" all mõeldakse märget andmebaasi.

**Comment by moll** [comment]
Tehtud, kuid laivis veel pole.

Kommenteerides saab administraator valida, kas kommentaar teha enda nime või Rahvaalgatuse alt. Näha saab https://next.rahvaalgatus.ee lehel "30303039914" isikukoodiga sisselogides.
