### ISSUE TITLE
Failide lisamise võimalus 

### ISSUE THREAD

**Issue by orgkadri** [rahvaalgatus/rahvaalgatus#297]
Eelkõige oluline KOV tasandi algatuste menetlusinfo puhul.

**Comment by moll** [comment]
Piirame kuus kuud või vanemate teavituste saatmist.

Lisame adminni juurde ka mõned sündmuse tüübid:
- Menetlusse võetud
- Arutelu omavalitsuses
- Menetlus lõppenud

**Comment by moll** [comment]
Nüüd saab adminniliideses sündmustele ka faile juurde lisada. Hetkel saab faile lisada vaid uutele sündmustele. Lisatud faile ei saa ka veel kustutada.

Seoses sündmuste tagant järele lisamisega tuli ka võimalus lisada sündmusi ilma teavituste saatmiseta. Nii saab mõnele algatusele tagant järele mitu sündmust lisada ja siis korraga mitme kohta teavituse saata.
