### ISSUE TITLE
Don't build

### ISSUE THREAD

**Issue by VenusKanami** [rahvaalgatus/rahvaalgatus#298]
Hello, i can build you project bun not compile. I was install all depencies. I use your instrucuin on github but i can't do it.
Where i do make i get:
make[1]: Entering directory '/home/venus/rahvaalgatus/app'
Compiling public/assets/html5.js…
Compiling public/assets/inputs.js…
Compiling public/assets/hwcrypto.js…
Compiling public/assets/editor.js…
jq  -c -f ../scripts/local_governments_geojson.jq \
        --argfile govs ../lib/local_governments.json \
        ../lib/local_governments.geojson \
        > "../tmp/local_governments.geojson.json"
/bin/sh: 1: cannot create ../tmp/local_governments.geojson.json: Directory nonexistent
Makefile:69: recipe for target '../tmp/local_governments.geojson.json' failed
make[1]: *** [../tmp/local_governments.geojson.json] Error 2
make[1]: Leaving directory '/home/venus/rahvaalgatus/app'
Makefile:16: recipe for target 'love' failed
make: *** [love] Error 2

Please tell me, how to fix it

**Comment by moll** [comment]
Hey,

Umm, it reads like it needs the `tmp` directory under the project root to exist. I don't think the `Makefile` in `app/Makefile` does this automatically now. I'll fix that, but until then, just create it manually.

**Comment by VenusKanami** [comment]
I was do it but get 
make -C app compile
make[1]: Entering directory '/home/venus/rahvaalgatus/app'
make[2]: Entering directory '/home/venus/rahvaalgatus/app'
Compiling public/assets/html5.js…
Compiling public/assets/inputs.js…
Compiling public/assets/hwcrypto.js…
Compiling public/assets/editor.js…
jq  -c -f ../scripts/local_governments_geojson.jq \
        --argfile govs ../lib/local_governments.json \
        ../lib/local_governments.geojson \
        > "../tmp/local_governments.geojson.json"
jq: error: round/0 is not defined at <top-level>, line 10:
        $gov + {threshold: [$gov.population * 0.01 | round, 5] | max}
jq: 1 compile error
Makefile:69: recipe for target '../tmp/local_governments.geojson.json' failed
make[2]: *** [../tmp/local_governments.geojson.json] Error 3
make[2]: Leaving directory '/home/venus/rahvaalgatus/app'
Makefile:16: recipe for target 'love' failed
make[1]: *** [love] Error 2
make[1]: Leaving directory '/home/venus/rahvaalgatus/app'
Makefile:72: recipe for target 'javascripts' failed
make: *** [javascripts] Error 2

**Comment by moll** [comment]
The error message there is referencing `jq`. What version of `jq` do you have there? Mine here is v1.6rc1.

**Comment by VenusKanami** [comment]
my jq jq-1.5-1-a5b5cbe

**Comment by VenusKanami** [comment]
how i can install jq v1.6rc1

**Comment by moll** [comment]
That depends on what operating system you're using and how you installed it in the first place.
What you could do to speed things up is instead ignore generating that file by creating an empty JSON file yourself

```
echo "{}" > tmp/local_governments.geojson.json
```

What are you trying to accomplish there in general, if I may ask? Browse the source code? Learn? Try your hand at open source? :)

**Comment by VenusKanami** [comment]
I was learn NodeJs. I thynk that your project is cool for my practice. Thenkyou. I'm so sorry but i can't run make web; module.js:478
    throw err;
    ^

Error: Cannot find module 'root/lib/underscore'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/venus/rahvaalgatus/bin/web:4:9)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
Makefile:107: recipe for target 'web' failed
make: *** [web] Error 1

**Comment by moll** [comment]
When you cloned the repository, it should've created a `node_modules/root` symlink. If that's disappeared, you should be able to get it back from Git:

```
git checkout node_modules/root
```

If not, you can recreate it with `ln`:

```
ln -s .. node_modules/root
```

> I was learn NodeJs. I thynk that your project is cool for my practice

Ah, great.

**Comment by moll** [comment]
I am curious, how did you stumble upon Rahvaalgatus?

**Comment by VenusKanami** [comment]
to be honest, I was told that your project is unrealistic to assemble and I was very interested

**Comment by moll** [comment]
What do you mean by "unrealistic to assemble"?

**Comment by VenusKanami** [comment]
Sorry for my English i mean that your project hard build

**Comment by VenusKanami** [comment]
Thenks, i could build your project. I was dont sleep 3 night

**Comment by moll** [comment]
Haha, that's a good one. Who told you that? :P

Ideally it should really be as simple or as hard as the README says, but I admit, I don't test compiling (frontend) assets that often. The backend seems to build easily on Travis (with just `npm install` as in https://github.com/rahvaalgatus/rahvaalgatus/blob/master/.travis.yml).

**Comment by VenusKanami** [comment]
a classmate told me this. I wanted up it on Server. I like smething do from zero.

**Comment by moll** [comment]
In other news, I do find it somewhat curious that the files on your repo (https://github.com/VenusKanami/soldante) are classified as viruses by VirusTotal. ^_^

**Comment by VenusKanami** [comment]
Oh, yes. i'm love virus analyst
I was every dream be InfoSec or PentesterTester or Reverse Engineer

**Comment by VenusKanami** [comment]
i go to localhost:3000/about and get TypeError: process.send is not a function
    at exports.readSync (/home/venus/rahvaalgatus/lib/markdown.js:6:36)
    at Object.exports.markdown (/home/venus/rahvaalgatus/lib/i18n.js:46:32)
    at module.exports (/home/venus/rahvaalgatus/views/home/about_page.jsx:13:18)
    at View.module.exports [as engine] (/home/venus/rahvaalgatus/node_modules/j6pack/express.js:5:26)
    at View.render (/home/venus/rahvaalgatus/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/venus/rahvaalgatus/node_modules/express/lib/application.js:640:10)
    at EventEmitter.render (/home/venus/rahvaalgatus/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/venus/rahvaalgatus/node_modules/express/lib/response.js:1012:7)
    at exports.router.get (/home/venus/rahvaalgatus/controllers/home_controller.js:114:63)
    at Layer.handle [as handle_request] (/home/venus/rahvaalgatus/node_modules/express/lib/rou

**Comment by moll** [comment]
Ah, I know. Go to `lib/markdown.js` and comment the `process.send` line out. I'll fix that, too, thanks.

**Comment by VenusKanami** [comment]
Great. Thenk you. You are very good human and developer.

**Comment by moll** [comment]
Where are you from that your class mate is talking about a random project on GitHub? ^_^

And well, now that you've got it running on your system, feel free to poke around in the codebase and if you find anything that's an actual vulnerability, I'll buy you lunch! When testing, stick with the local version, though! ;)

**Comment by VenusKanami** [comment]
Ooooy. heah. I do it. (if can))

**Comment by VenusKanami** [comment]
I'm from Ukraine. My classmate like read news and loock you site. Hes tried search your site  in google and found you github

**Comment by moll** [comment]
Great. Well, let me know what you find and good luck!
I'll close the issue for now, but feel free to continue chatting.

**Comment by moll** [comment]
Oh, and if you've got the news article your classmate found that made it to Ukraine, please share! I'd love to take a look.
