### ISSUE TITLE
Don't work port 3001

### ISSUE THREAD

**Issue by VenusKanami** [rahvaalgatus/rahvaalgatus#299]
Hello, don't work port 3001 with admin panel) What is it ?

**Comment by VenusKanami** [comment]
Not an Admin

**Comment by moll** [comment]
Hey again,

This indicates you need to authenticate on the primary site before you can log into the admin interface. You can use one of the demo authentication numbers I refer to in the README. Btw, if you see an error, you can also search for that phrase in the code base and work backwards from there, reading code. It could be faster for when I'm not around. ;)

**Comment by VenusKanami** [comment]
Thenk friend)
