### ISSUE TITLE
Menetlusinfos pealkiri vaja terviklikult välja näidata (praegu ei mahu ära)

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#3]
Vt nt https://rahvaalgatus.ee/initiatives/dbe5cd08-afe1-47fd-aac6-6abb8e1f24ea/events

**Comment by moll** [comment]
Tegin selle vist tollal "kaitseks" algatuste vastu, kus pool teksti on pealkirjaks määratud (kuskil selline kungi oli), kuid see mure sai vist muul moel lahendatud ning "kaitse" võib eemaldada.

**Comment by moll** [comment]
Mulle tundub, et see lõikamine on hoopis Citizeni backendi poolel. Uurin sealt.

**Comment by moll** [comment]
Ootab Margolt otsustamist CitizenOS-i poolse pealkirja piirangu osas.

**Comment by moll** [comment]
@loorm: Lepiks kokku pikima pealkirja pikkuse. Praegu on ülallingitud algatuse pealkiri muudes kohtades lõigatud, algatuse enda vaates aga mitte.

**Comment by infokujur** [comment]
@moll Olenemata sellest, kuidas ja kui pikalt lõpetatakse, on vaja see konkreetne pealkiri terviklikuks. Ilma ... punktiirita.
Igal juhul on vaja, et inimene ei saakski pikemat pealkirja anda, kui meie välja näitame.

**Comment by moll** [comment]
@infokujur: Yep. Ootab aga @loorm heakskiitu Mikule implementeerimiseks.

**Comment by moll** [comment]
Palusin konkreetselt selle case'i kohta Rahvaalgatuse chatis otse Ilmarilt ka.

**Comment by infokujur** [comment]
Siin veel üks case: https://rahvaalgatus.ee/initiatives/dbe5cd08-afe1-47fd-aac6-6abb8e1f24ea/events @moll

**Comment by moll** [comment]
@infokujur: See on sama case, mis esimeses postituses. :) Aga ootab ikka Citizeni poolelt @loorm "jah"-i.

**Comment by tiblu** [comment]
https://github.com/citizenos/citizenos-api/issues/2

**Comment by moll** [comment]
Lahendatud https://github.com/rahvaalgatus/rahvaalgatus/issues/58 raames.
ignoreerime CitizenOSi tuvastatud pealkirja ja üritame ise Etherpadi HTMList ta tuletada.
