### ISSUE TITLE
Kasutaja nõusoleku küsimise lehe eestikeelne tõlge

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#30]
Rahvaalgatus.ee would like to access following data from your CitizenOS account
view and edit your CitizenOS profile - name, company, email, picture
view and edit your Topics
view and edit your Votes
view and edit your Groups

Rahvaalgatus.ee will use this information in accordance with their terms of use and privacy policy.

AGREE / DISRUPT

Rahvaalgatus.ee soovib ligipääsu Sinu CitizenOS kasutajakontole, et süsteemi sees jagada Sinu kasutajaandmeid (nimi, organisatsioon, e-post, foto), arutelusid, algatusi, hääletusi ja arutelurühmi.

Rahvaalgatus.ee kasutab seda infot vastavalt oma kasutamise heale tavale ja privaatsuspoliitikale.

NÕUSTU / KATKESTA

**Comment by infokujur** [comment]
#9

**Comment by moll** [comment]
Meenutuseks: Problemaatiline oli muuhulgas ka fraas "view and edit your Votes", mida võib tõlgendada kui "Rahvaalgatus/Citizen võib muuta teie häält".

**Comment by infokujur** [comment]
Probleem laheneb, kui läheme vaid eID peale üle.
