### ISSUE TITLE
hi i get error

### ISSUE THREAD

**Issue by ValeriaVis** [rahvaalgatus/rahvaalgatus#302]
make db/create
sqlite3 "config/development.sqlite3" < config/database.sql
/bin/sh: 1: sqlite3: not found
Makefile:133: recipe for target 'config/development.sqlite3' failed
make: *** [config/development.sqlite3] Error 127

**Comment by ValeriaVis** [comment]
and when i do make in app folder i was get:
:~/rahvaalgatus/app$ make
make[1]: Entering directory '/home/venus/rahvaalgatus/app'
Compiling public/assets/html5.js…
Compiling public/assets/inputs.js…
Compiling public/assets/hwcrypto.js…
Compiling public/assets/editor.js…
Compiling public/assets/local.js…
make[1]: Leaving directory '/home/venus/rahvaalgatus/app'

**Comment by moll** [comment]
Hey,

When you read the output of `make db/create`, what do you think the problem could be? ;)

As for the second `make` invocation, what about it? ;)

**Comment by ValeriaVis** [comment]
i try do npm i sqlite3

**Comment by moll** [comment]
The `sqlite3` executable doesn't come from NPM. Try installing `sqlite3` like you install other software. For example, if you're on Ubuntu/Debian, that'd be `apt-get install sqlite3`, I believe.

**Comment by moll** [comment]
I added a note about SQLite to the README now, too. ;)

**Comment by ValeriaVis** [comment]
Man you are the best!
