### ISSUE TITLE
Algatust avalikustades palume meiliaadressi kinnitamist

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#304]
Seda nii automaatsete teavituste saatmiseks kui ka algatajaga ühenduse võtmiseks.

**Comment by moll** [comment]
Siin puhul tasub vist veenduda, et parasjagu algatust avalikustaval inimesel on meiliaadress lisatud, eks, mitte tingimata algatuse looja? Peale looja saavad algatust avalikustada ka kaasautorid.

**Comment by orgkadri** [comment]
Jah, täpselt.

**Comment by moll** [comment]
Laivis.
