### ISSUE TITLE
Kohalikele omavalitsuste algatustele eraldi kirjelduslause allkirjastamise juurde

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#307]
@orgkadri lisab `HEADING_VOTE_REQUIRE_HARD_ID`-le lisaks KOVi teksti.

**Comment by orgkadri** [comment]
Lisasin enda poolt KOV teksti - HEADING_VOTE_REQUIRE_LOCAL_ID - juurde.

**Comment by moll** [comment]
Tehtud. Nüüd kuvatakse kohalike algatuste puhul teist kirjeldust.
