### ISSUE TITLE
Algatust avalikustades tellime algatajale kommentaaride teavitused

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#308]
Seotud: https://github.com/rahvaalgatus/rahvaalgatus/issues/304

**Comment by moll** [comment]
Algatust võib avalikustada ka kaasautor. Kas arvad, et võiks nii autorile kui ka kõigile kaasautoritele kommentaarid tellida?

**Comment by orgkadri** [comment]
Võiks küll, sest ühisloome perioodil laekuv sisend on ideeliselt oluline nii autoritele kui ka kaasautoritele.

**Comment by moll** [comment]
Tehtud. Laivi läheb koos #304-ga varsti.
