### ISSUE TITLE
Day count till end of voting on timeline

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#31]
Siin on mingi error.

Kaks arutelu. Lõppevad samal päeval, aga kollane bar näitab (kasti vaates) päeva võrra erinevalt:

https://uuseakus.rahvaalgatus.ee/initiatives/1b7617be-1069-40ba-8692-d33019f151f3
https://uuseakus.rahvaalgatus.ee/initiatives/90806467-1a48-427b-a558-50cb816f8530

Erinevus on arutelu loomise ajas.

@moll Palun vaata, milles võib olla küsimus.

**Comment by moll** [comment]
Tõepoolest, riba pikkus tulenes alguse aja erinevustest. Putitasin, et sõltumata alguskellajast oleksid ribad võrdse pikkusega. Näha: https://uuseakus.rahvaalgatus.ee/initiatives.
