### ISSUE TITLE
Ühisloome perioodil mitmekeelsuse (st tõlgete) lubamine

### ISSUE THREAD

**Issue by orgkadri** [rahvaalgatus/rahvaalgatus#310]

**Comment by moll** [comment]
Tehtud ja laivis. Tõlked on ühisloomefaasis nüüd nähtavad. Allkirjastamisfaasi liikudes aga lähevad kuniks tõlgete allkirjastamiseni peitu.

**Comment by moll** [comment]
Allkirjastamise faasis on praegu algatuse lehel allkirjastamata tõlke indikaatoriks vaid kursiivis _tab_, nagu https://github.com/rahvaalgatus/rahvaalgatus/issues/146#issuecomment-647214416 pildil näha. Kardan pisut, et ei ole selge peale algatuse allkirjastamisele saatmist, et tuleks tõlkeid allkirjastada. Ehk peaks kuvama alati algatuse lehel teadet, kui on allkirjastamata tõlkeid, isegi kui algataja parasjagu tõlget ei vaata...
