### ISSUE TITLE
Ühendame ametliku ja algataja menetlusinfo teavitused

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#312]
Nende eraldi hoidmine pole eriti selge.

**Comment by orgkadri** [comment]
Pakuksin nende koondnimetuseks: Riigikogule või KOVile saadetud algatuste menetlusinfo ja teavitused

**Comment by moll** [comment]
Tegelikult käib sinna alla ka lävendite ületamine stiilis "algatus on kogunud 100 allkirja".

**Comment by orgkadri** [comment]
Sellisel juhul oleks täpsem ehk variant: "Teavitused ja menetlusinfo algatuste käekäigust"

**Comment by moll** [comment]
Tehtud, kuid laivi läheb, kui https://github.com/rahvaalgatus/rahvaalgatus/issues/313 ka valmis.
