### ISSUE TITLE
Uute algatuste ja allkirjastamisele saadetud algatuste teavitused

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#313]
Puudutab vaid esilehel _kõikide_ teavituste tellimist.

**Comment by orgkadri** [comment]
Pakun välja teavituste valikuteks järgneva. 

[Kõik Rahvaalgatus.ee-s:]

- Loodud uued algatused 
- Allkirjastamisele saadetud algatused 
- Riigikogule või KOVile saadetud algatuste menetlusinfo ja teavitused 
- Algatustele antud kommentaarid 

Kas ja millised "linnukesed" on juba vaikimisi olemas, kui inimene on kinnitusmeilile vajutanud? Kas praegu on olnud kõik?

**Comment by moll** [comment]
Vaikimisi on seni saanud kõik menetlusinfo teavitusi, olgu see siis ametlik või algataja poolt.

**Comment by orgkadri** [comment]
Kas see tähendab, et vaikimisi ei ole olnud kommentaaridel linnukest? Ja selle soovi on saanud inimene ise juurde panna.

**Comment by moll** [comment]
Jep, vaikimisi ei olnud kommentaare tellitud. Eks osaliselt seepärast sai ka kommenteerimise vormi juurde linnuke lisatud, et neile, kes kommenteerivad, sellest võimalusest teada anda.

**Comment by orgkadri** [comment]
Pakun välja, et pärast muutmist võiks vaikimisi olla "linnuke kastis" "loodud uued algatused" ja "allkirjastamisele saadetud algatused" valikus. Ning teised saavad kasutajad soovi korral juurde lisada (või siis eelnevad eemaldada). 

Sama loogika: et eraldi algatuste menetlusinfo käekäigust saab teavitusi tellida ka ju ühekaupa. Ning tõenäoliselt nö esmane soov oleks saada teavitus uutest (allkirju koguvatest) algatustest endist, mille osas saab kasutaja siis ise täpsemalt otsustada, kas seda oma allkirjaga toetada ja kas on soov ka edasise käekäiguga kursis olla.

**Comment by moll** [comment]
Uue allkirjastamisele saadetavate algatuste teavitusvaliku valguses, kas neile, kes on tellinud kõikide algatuste sündmusi ja menetlusinfot, tuleks ka jätkuvalt saata teade allkirjastamisele minekust? Eeldatavasti pole kedagi, kas tahab saada menetlusinfot, aga _ei taha_ saada teada, kui algatus allkirjastamisele läheb.

**Comment by moll** [comment]
@orgkadri, oled oodatud uute algatuste teavituste fraase muutma tõlketabelis:
- `INITIATIVE_PUBLISHED_MESSAGE_TITLE`
- `INITIATIVE_PUBLISHED_MESSAGE_BOBY`

**Comment by moll** [comment]
Tehtud. Võid testkeskkonnas (https://next.rahvaalgatus.ee) pilgu peale visata ja sõnastuste osas tagasisidet anda.

**Comment by orgkadri** [comment]
> Uue allkirjastamisele saadetavate algatuste teavitusvaliku valguses, kas neile, kes on tellinud kõikide algatuste sündmusi ja menetlusinfot, tuleks ka jätkuvalt saata teade allkirjastamisele minekust? Eeldatavasti pole kedagi, kas tahab saada menetlusinfot, aga _ei taha_ saada teada, kui algatus allkirjastamisele läheb.

Jaa, ma arvan ka, et vaevalt on keegi, kes tahab saada kõikide algatuste sündmustest ja menetlusinfost teavitust, aga mitte allkirjastamisele minekust. Seega see teave võiks ka minna. 

PS! Tsipa kohendasin sõnastust sõnede tabelis. Mulle tundub päris hea! Aitäh!

**Comment by moll** [comment]
Laivis.
