### ISSUE TITLE
Algatuse disclaimer

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#314]

**Comment by orgkadri** [comment]
Pakun välja järgneva: 

**Kollektiivses pöördumises väljatoodud mõtted esindavad üksnes pöördumise autorite seisukohti ning need ei pea ühtima osalusportaali Rahvaalgatus.ee haldava organisatsiooni Eesti Koostöö Kogu seisukohtadega.**

**Comment by moll** [comment]
Lisasin küljeribale _disclaimeri_. [Tõlketabelis](https://docs.google.com/spreadsheets/d/1JKPUNp8Y_8Aigq7eGJXtWT6nZFhd31k2Ht3AjC-i-Q8/edit#gid=0) nime `INITIATIVE_PAGE_DISCLAIMER` all. Laivis veel pole.
