### ISSUE TITLE
Ühisloome ja allkirjastamise miinimumperioodi kuupäeva korrigeerimine

### ISSUE THREAD

**Issue by orgkadri** [rahvaalgatus/rahvaalgatus#316]

**Comment by moll** [comment]
Normaliseerisin ühisloome ja allkirjastamise miinimum- ja maksimumperioodide käsitlemise. Nüüd saab 1. juunil valida tähtajaks 3. juuni, mis telgi taga määrab tähtajaks 4. juuni 00:00. Külastajatele kuvatakse tähtajana siiski 3. juuni 23:59, et 00:00-ga mitte segadust tekitada. Õige oleks ka 3. juuni 24:00, kuid see võib olla harjumatu. Maksimumperioodiga sama printsiip. Loodetavasti on nii algatajatele loogilisem, sest allkirjastamisele saab algatuse saata kohe peale 3. juuni kl 23:59 möödumist ehk 4. juunil 00:00. 

Uuendasin ka [testkeskkonda](https://next.rahvaalgatus.ee/), kui tahad seal katsetada.
