### ISSUE TITLE
sisselogimiskatsel küsitakse mitte pin1 vaid pin2

### ISSUE THREAD

**Issue by jaanusnurmoja** [rahvaalgatus/rahvaalgatus#320]
Süsteemi sisselogimise leht nõuab id-kaardiga sisseloginult PIN2, mis on aga allkirja andmiseks. Peaks nõudma PIN1

![image](https://user-images.githubusercontent.com/1138055/136103276-b6747ec7-0077-484c-9e48-89ad47ee89c0.png)

**Comment by moll** [comment]
Hei

Tänu _issue_ eest. Sisselogimine sai aasta algul PIN2 peale viidud, kui RIA eID pistikprogrammis sisselogimise välja lülitas. Rantisin sellest https://m811.com/articles/id-kaardi-brauserilaienduse-turvalisusest/ artiklis, kui huvi pakub. Eks ta natuke segadust tekitab tõesti praegu.

Uuesti PIN1 kasutamiseks on käsil ID-kaardiga sisselogimise kohandamine ja selleks juba https://github.com/rahvaalgatus/rahvaalgatus/issues/317 issue. Panen käesoleva #317 valguses kinni, kuid võime siin või #317 teemas edasi suhelda.
