### ISSUE TITLE
Tekst kalendri juurde (18 kuu piirang)

### ISSUE THREAD

**Issue by orgkadri** [rahvaalgatus/rahvaalgatus#323]
Pakun välja kalendri juurde minevaks tekstiks järgneva: 

Isikuandmete kaitse nõudest tulenevalt piirame allkirjade kogumist 18 kuuga. See tähendab, et kui algatus ei ole alates allkirjade kogumise perioodi algusest 18 kuuga piisavas koguses allkirju kokku saanud, läheb see arhiivi ning allkirjad kustutatakse. Pärast perioodi lõppu saab soovi korral luua samal teemal uue algatuse.

**Comment by moll** [comment]
Allkirjastamisele saates on nüüd kuupäeva valiku juures ka tekst ülal. Lisasin ka lihtsa ingliskeelse tõlke. Tõlketabelis `INITIATIVE_SEND_TO_SIGN_DESCRIPTION` all.
