### ISSUE TITLE
Kasutajate profiilis selgitus allkirjastatud pöördumiste osas

### ISSUE THREAD

**Issue by orgkadri** [rahvaalgatus/rahvaalgatus#324]
Pakun selgitava tekstina välja järgneva: 

Siin kuvatakse sinu allkirjastatud algatused, mis ei ole veel Riigikogule või kohalikule omavalitsusele menetlemiseks saadetud või mille puhul ei ole Rahvaalgatus.ee-l teavet, et algatuse menetlusse võtmiseks oleks digiallkirjadele teostatud kontroll. 

Algatustelt, millele antud allkirjadele on kontroll teostatud, on isikuandmete kaitsest tulenevalt allkirjastajate isikuandmed eemaldatud.

**Comment by moll** [comment]
Profiili allkirjade lehekülg sai natuke selgitusteksti.
