### ISSUE TITLE
Twitteri eemaldamine 

### ISSUE THREAD

**Issue by karlpallo** [rahvaalgatus/rahvaalgatus#329]
Kuna EKK Twitterit aktiivselt ei uuenda, siis võiks eemaldada selle lingi kodulehelt (see on hetkel kolmes kohas- kohe "ole algatustega kursis" kõrval Riigikogu ja KOV alarubriikides ning ka veebi allosas jaluses).

**Comment by moll** [comment]
Esilehelt sai Twitter link ammu eemaldatud, aga märkasin, et e-kirjade jalusesse jäi ta veel alles. Eemaldasin ka sealt. Lükkan varsti muutuse laivi.
