### ISSUE TITLE
Ekirja lisada juurde märge selle kohta, et Digidoc seda konteinerit ei suuda avada.

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#33]
E-kirja tekstid üle vaadata.
Teeme süsteemselt kogu teksti töö.

#14

**Comment by moll** [comment]
@tiblu mõtlevat, kuidas lubada kõiki Mailchimpi template'e muuta.

**Comment by moll** [comment]
Seotud: https://github.com/citizenos/citizenos-api/issues/6

**Comment by infokujur** [comment]
Ei ole teema, kuna algatajaid neid enam ei saa.
