### ISSUE TITLE
Eraldi jaotus "saatmata pöördumised" 

### ISSUE THREAD

**Issue by orgkadri** [rahvaalgatus/rahvaalgatus#330]
Esilehel eraldi jaotus neile pöördumistele, millel on allkirjad koos, aga mis pole riigikokku/KOVi menetlusse saadetud: 

Hetkel on meil "allkirjastamisel" faasis ka need, millel tegelikult allkirjastamise kuupäev on lõppenud ja/või pole algataja pikendanud seda. Aga kasutajamugavuselt võiks olla lihtsam ja selgem, kui sellised algatused oleksid eradi jaotuses "Saatmata pöördumised" nt. Ning allkirjastamisel all oleksid need pöördumised, mida siis reaalselt saab allkirjastada.

**Comment by moll** [comment]
Tähtaja ületanud ja edukad algatused on nüüd eraldi "Saatmisel" grupis. Lahtine on, mida teha algatustega, mis allkirjalävendit ei ületanud. Praegu on nad veel 2 nädalat "Allkirjastamises" grupis. Kas peaks, huvitav, nad kohe esilehelt eemaldama?
