### ISSUE TITLE
Statistika esilehel klikitavaks

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#335]
Esilehel olevad numbrid (nt x algatust viimase 30p jooksul) võiksid olla lingid ja viia eelfiltreeritud algatuste lehele, kus on nt loetelu hiljuti Riigikokku saadetud algatustest

**Comment by moll** [comment]
Seotud https://github.com/rahvaalgatus/rahvaalgatus/issues/361.

**Comment by moll** [comment]
Selle raames sai lisatud ka väliste algatuste filter, mida hetkel ise valida ei saa, aga rakendub läbi esilehe linkide. Näiteks https://next.rahvaalgatus.ee/initiatives?external=true. Nimetasin selle praegu "Keskkond" filtriks, aga kui tuleb paremaid terminoloogia mõtteid, andke teada!

Statistika https://next.rahvaalgatus.ee ja Riigikogu-spetsiiflisel esilehel (https://next.rahvaalgatus.ee/parliament) on nüüd klikitav. Sorteerimine on neil veel määramata. Ilmselt peaks igas kontekstis olema eelvalitud sorteerimine ka. Nt "Saadetud" linkidele vajutades saatmiskuupäeva järgi.

Viimati antud allkirjadega algatuste filtrini/sorteerimiseni veel ei jõudnud.

**Comment by infokujur** [comment]
> Nimetasin selle praegu "Keskkond" filtriks, aga kui tuleb paremaid terminoloogia mõtteid, andke teada!

Täpsem vaste oleks - kanal / channel
(täpne oleks meedium või modaalsus, aga see on liiga erialane meediateooria sõnavara ja pigem ajab segadusse)

> Statistika https://next.rahvaalgatus.ee ja Riigikogu-spetsiiflisel esilehel (https://next.rahvaalgatus.ee/parliament) on nüüd klikitav. Sorteerimine on neil veel määramata. Ilmselt peaks igas kontekstis olema eelvalitud sorteerimine ka. Nt "Saadetud" linkidele vajutades saatmiskuupäeva järgi.

Jah, vastavalt kontekstile on hea lähenemine:
- arutelusid - algatus loodud kuupäeva järgi (pm mis praegu on)
- algatusi - allkirjastamisele saadetud kuupäeva järgi
- allkirju - viimati allkirjastatud järgi
- saadetud - viimati saadetud järgi
 
> Viimati antud allkirjadega algatuste filtrini/sorteerimiseni veel ei jõudnud.

Kas mõtled kõikide algatuste kuva? Selle all mõtlesime viimati muudetud (mh allkirjastatud) sorteerimsit. Sama nagu esielehel "Hiljuti aktiivsed" rubriigis.

**Comment by moll** [comment]
> arutelusid - algatus loodud kuupäeva järgi (pm mis praegu on)

Arutelu statistikale klikkides on sorteerimine faasi järgi tegelikult. Lihtsalt faasi siseselt on ühisloomes see loomise kuupäeva järgi.

> algatusi - allkirjastamisele saadetud kuupäeva järgi
> allkirju - viimati allkirjastatud järgi

Sai nii tehtud.

> saadetud - viimati saadetud järgi

Hetkel läks menetluse alguse kuupäev, sest saatmise kuupäeva meil tabelis kuvatud pole. Kas oleks vaja?

> Täpsem vaste oleks - kanal / channel

Asendasin sõna "platvorm" sõnaga "kanal".

**Comment by moll** [comment]
> allkirju - viimati allkirjastatud järgi

Selle raames sai lisatud ka "Allkirjastatud" tulp ja filter. Praegu kuvatakse viimati allkirjastamise kuupäev välja vaid allkirjastamises olevate algatuste puhul, et infohulka minimeerida. Kas on tugevaid seisukohti, et peaks viimase allkirja kuupäeva kuvama ka teistes faasides? On sellest vanemate algatuste puhul kasu? 

CSV ekspordis on viimase allkirja kellaaeg alati olemas.

**Comment by infokujur** [comment]
Need asjad sobivad. Praegu on piisavalt küps, et testida ja suuremalt ringilt tagasiside küsida. Ilmselt meil on vaja mingisuguseid infomulle, mis täpselt selgitavad, mis ja kuidas, aga selleks avame juba uue teema.
