### ISSUE TITLE
Prindi algatus funktsioon, mis loob puhta print vaate

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#343]
Vaade sisaldab:
Algatuse pealkiri
Adressaat
Algataja nimi
Algataja kontakt (kui on)
QR kood, mis viib algatuse lehele
Algatuse tekst

Uuelt lehelt:
Disclaimer (selle teksti peab täpsustama, aga sisult on a'la: Olen lugenud läbi algatuse:"_algatuse pealkiri_" ja avaldan toetust oma allkirjaga.)
Tabel allkirjade kogumiseks (tulbad pealkirjadega: nimi; isikukood; allkiri)

**Comment by moll** [comment]
Rahvaalgatusest pärit algatuste juures on küljeribal nüüd "Prindi" valik, kus saab sisse-välja lülitada algatuse teksti, menetlusinfot, kommentaare kui ka allkirjade kogumiseks lehekülje. Vaikimisi prinditakse (ehk see, mis niisama File -> Print valides juhtub) tekst, menetlusinfo ja kommentaarid.

**Comment by moll** [comment]
Paberallkirjade kogumiseks tabeli printimine vajab ilmselt katsetamist erinevate operatsioonisüsteemide tagant, sest veeb ja CSS pole just loodud täpselt ühte A4 (või kes teab, mis lehesuurust) täitva tabeli tegemiseks. Linuxi tagant nii Firefox kui ka Chromium tegid vähemalt õige suurusega tabeli.

**Comment by karlpallo** [comment]
> Paberallkirjade kogumiseks tabeli printimine vajab ilmselt katsetamist erinevate operatsioonisüsteemide tagant, sest veeb ja CSS pole just loodud täpselt ühte A4 (või kes teab, mis lehesuurust) täitva tabeli tegemiseks. Linuxi tagant nii Firefox kui ka Chromium tegid vähemalt õige suurusega tabeli.

Mul töötas ka ilusti windowsis- chrome'is. Telefonis (iOS-safari) pidi natukene timmima aga oli ka kättesaadav
