### ISSUE TITLE
Algatajal nime muutmise võimaluse eemaldamine

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#351]

**Comment by moll** [comment]
Need, kes on oma nime juba muutnud, jäävad alles.

Eesmärk nime muutmise takistamisel on vältida allkirjastajate eksistamist ja pseudonüümide kasutamist.

**Comment by moll** [comment]
Oma nime enam muuta ei saa. Muutmiseks tuleb meile kirjutada.
