### ISSUE TITLE
Lause osa "algatust veel allkirjastada ei saa" - boldiks ja punaseks

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#353]
![image](https://github.com/rahvaalgatus/rahvaalgatus/assets/12999094/cb393758-dcb1-4fcc-9d21-5c8360992b31)

**Comment by moll** [comment]
Vaatame, kas sellest on abi:

![Screenshot from 2023-10-27 20-11-17](https://github.com/rahvaalgatus/rahvaalgatus/assets/156837/8fb436ec-6e04-4fed-b91c-a816703d98c0)

@karlpallo, kuidas tavaliselt inimesed selle osas segadusse sattuvad? Kas peamine segadus tuleb algatajatelt või ülejäänutelt? Ehk saab seda mujal paremini selgitada.

**Comment by karlpallo** [comment]
Mina olen neid ühisloome küsimusi kuulnud ainult algatajatelt seoses sellega, et tavaliselt pole sellega arvestatud ja on kiire avalikustamisega

**Comment by moll** [comment]
Konkreetne lause sai rasvaseks tehtud. Kui algatajad on peamised segaduses olijad, siis nende jaoks on meil lootust parem algatuse teksti ja settingute lehekülg, kus protsess on sõbralikumalt lahtiseletatud.

**Comment by karlpallo** [comment]
> Konkreetne lause sai rasvaseks tehtud. Kui algatajad on peamised segaduses olijad, siis nende jaoks on meil lootust parem algatuse teksti ja settingute lehekülg, kus protsess on sõbralikumalt lahtiseletatud.

Probleem pigem isegi selles, et need algatajad ei ole hakanud varem algatust tegema kui sel momendil kui neil on *vaja* algatus allkirjastamisele saata.  Ja sellele probleemile mul ei ole veel ühtegi lahendavat mõtet tekkinud.
