### ISSUE TITLE
Ühisloomes peatunud algatused arhiveerida ja kaardil avanevas aknas näidata ainult aktiivseid

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#356]
Vt nt Tallinnas on 5 algatust ühisloomes seiskunud algatust
![image](https://github.com/rahvaalgatus/rahvaalgatus/assets/12999094/47933e6c-8796-4207-ab35-be78fd1930a5)

**Comment by moll** [comment]
Järgmine sama loogikat, mis esilehel, ehk lõppenud arutelusid ei kuvata kui ühisloomes jne.

**Comment by moll** [comment]
Tegelikult võib isegi "arhiveeritud"  asendada "järelkajaga". Vbla lisada juurde "kõik algatused" ka (koos numbriga nt).

**Comment by infokujur** [comment]
See on saanud tehtud, sulgen.
