### ISSUE TITLE
Lõpetatud diskussioonid ning hääletused

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#36]
Nt kõrvaklappide arutelu

**Comment by infokujur** [comment]
@moll Palun sildista õieti.

**Comment by moll** [comment]
Kõrvaklappide arutelu https://rahvaalgatus.ee/initiatives/a2089bf7-9768-42a8-9fd8-e8139b14da47 paistab olevat kellegi-millegi poolt saanud `closed` staatuse. Kuna meil jäi `closed` algatuste kuvamise feature tollal pooleli, siis seda tõesti RA peal vee praegu näha pole. 

Jõuan homme menetluses läbi käinud algatuste feature'iga küll nii kaugele, et neid kuvada, kuid mida me selliste suletud diskussioonidega teha võiks? Kuvaks nad diskussioonide sektsioonis lõpus ja/või teeme eraldi alamlehe nupuga "Vaata lõpetatud diskussioone"?

**Comment by moll** [comment]
Võtsin bugi sildid küljest ja tegin sellest https://github.com/rahvaalgatus/rahvaalgatus/issues/4-ga seotud feature'i.

**Comment by infokujur** [comment]
Siin on lõppenud arutelud praegu näha: https://rahvaalgatus.ee/initiatives
Seal rodus võiks kõik olla. Ei hakka enne eraldi sektsioone tegema, kui neid tõesti palju sinna tuleb.
Siis võiks kuidagi sortimis/otsimis võimalus olla.

**Comment by moll** [comment]
Ok. Tehniliselt on diskussioonid seal praegu vaid lõppenud tähtaja möödumise tõttu, kuid mitte *suletud* staatuse saanud.

**Comment by moll** [comment]
Kas hääli mitte täis kogunud algatused jätame ka "Hääletuses" sektsiooni nagu lõppenud diskussioonidki?

**Comment by infokujur** [comment]
Jah.

**Comment by moll** [comment]
Tehtud ja laivis. Suletud (manuaalselt lõpetatud) diskussioonid ja hääletused on oma grupis. Menetluse läbinud algatused aga eraldi "Menetletud" pealkirja all.

Ülalmainitud kõrvaklappide arutelu https://rahvaalgatus.ee/initiatives/a2089bf7-9768-42a8-9fd8-e8139b14da47 on ka kenasti https://rahvaalgatus.ee/initiatives lehel näha.

Teen ka ettepaneku millalgi peita suletud diskussioonid ja tuua nad nähtavale nt vaid "Vaata suletud diskussioone" nuppu vajutades. Muidu jääbki vanu teemasid, mis Riigikoguni pole jõudnud, kogunema. Küll aga teeme selle kohta eraldi GitHub issue, kui tegemiseks läheb. ;)

**Comment by moll** [comment]
PS. UI-st sai manuaalse sulgemise nupp su soovil mingi aeg tagasi eemaldatud, nii et hetkel pole võimalust ühtegi küll sulgeda. :) K.a "menetluses" teemasid "menetletud" gruppi liigutada.
