### ISSUE TITLE
Allkirjade arhiivi lehele mõned filtrid

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#361]
A la ka sorteerimine allkirjade arvu järgi vms.

**Comment by infokujur** [comment]
https://rahvaalgatus.ee/initiatives
- [ ] Arhiivi leht ümber kujundada tabeliks, mille päis on sorteeritav
Tulbad: Avaldamise kuupäev, Algatuse pealkiri, Algataja(d), Faas/Staatus, Adressaat, Kogutud allkirjad, Allkirjastamise tähtaeg, Menetluse algus, Menetleja, Menetluse lõpp
- [ ] Tabeli ette filtrid: kuupäeva vahemikud, Adressaat, ringdiagramm - Menetleja, tulpdiagramm - TOP 20 enim allkirjastud algatust

**Comment by karlpallo** [comment]
Imo avaldamise kuupäevale lisaks võiks olla ka "allkirjastamisele saadetud". Lisaks võiks saada vaadata ka nt mis algatused said menetlusinfot ajavahemikus X-Y. 
 

Ja lisamõte, et algatuste filtreerimise võimalus peaks hiljem minema mingil kujul ka esilehele, sest juba praegu ei ole see esileht enam informatiivne infoülekülluse tõttu (liiga palju algatusi, et neid päriselt läbi vaadata või mingit ülevaadet omada (kasutaja vaates).

**Comment by moll** [comment]
Lükkasin esmase versiooni testkeskkonda vaatamiseks üles: https://next.rahvaalgatus.ee/initiatives
Vaatasin, et staging polnud ka kunagi Riigikoguga sünkinud. Panin korra sünkima ja enne, kui Riigikogu API timeoute viskama hakkas, tulid mõned läbi. Vähemalt natuke rohkem algatusi tabelis filtreerimiesks. 

Visualisatsioonide osa jäi eraldi issuesse (https://github.com/rahvaalgatus/rahvaalgatus/issues/375) ja vajab natuke läbi rääkimist, mis on erinevate graafikute eesmärk ja milline graafiku vorm on erinevate atribuutide jaoks parim vorm.

"Menetleja" tulpa hetkel pole. Millist menetlejat te mõlemad silmas pidasite? Riigikogu algatuste puhul viimast komisjoni? Esimest komisjoni? Kõiki komisjone? Mis aga kohalike algatuste puhul? Mis nende puhul, mis on läinud Riigikogust valitsusse? Me hetkel Riigikogust valitsusse läinud algatusi vist praktikas ei jälgi ja isegi kui menetlusinfos vabas vormis on, siis masinloetavalt pole veel seda infot kogunud.

Menetlemiskuupäevade tulpadeks panin hetkel Riigikokku ja KOVidesse saatmise kuupäeva, kuid praktikas on seal mitu astet — saatmine, vastuvõtmine ja menetlusse võtmine (või tagasilükkamine). Millie neist kuupäevadest võiks-peaks olema menetluse algus? Äkki peaks tagasilükkamist ka tabelis näitama — näiteks menetluse alguse-lõpu kuupäevade asemel.

**Comment by infokujur** [comment]
- Täiendasin #375, et kaks graafikut. Ring- ja tulpdiagramm, vastavalt menetleja ja häälte arv . Kõnes rääkisin (kui need taskid tegime), et neid küsitakse pidevalt ja oleme sellises vormis seda infot välja andnud (slaidid jne). Praegu peab pidevalt käsitsi tegema.

- Riigikogu juhatus määrab menetlejaks ÜHE komisjoni (kes seda protsessi juhib ja selle eest vastutab) - seda kuvamegi - reeglina toimub esimene arutelu selles komisjonis.
Arutelud toimuvad mitmes, saadetakse valitsusse, ministeeriumi, asjadel on erinevad lõpud, sellega me praegu veel ei tegele.

- KOV tasandil on menetlejaks KOV.

- Meneltuse algus on menetlusse võtmine (ehk RK juhatuse otsuse kuupäev)

**Comment by moll** [comment]
>  Riigikogu juhatus määrab menetlejaks ÜHE komisjoni (kes seda protsessi juhib ja selle eest vastutab) - seda kuvamegi - reeglina toimub esimene arutelu selles komisjonis.

Isegi kui korraga on üks komisjon, siis võivad need paraku aja möödudes muutuda. Sellest ka küsimus — kas kuvame viimast või esimest. Riigikogu liideses on nt https://rahvaalgatus.ee/initiatives/22-n%C3%B5uame-5g-tehnoloogia-paigaldamise-peatamist-eestis* algatusel kaks aktiivset komisjoni korraga, kus mõlemad on arutelusid pidanud — Keskkonnakomisjonis ja Sotsiaalkomisjonis. Eeldan, et kuvame alati kõige viimast.

**Comment by infokujur** [comment]
> > Riigikogu juhatus määrab menetlejaks ÜHE komisjoni (kes seda protsessi juhib ja selle eest vastutab) - seda kuvamegi - reeglina toimub esimene arutelu selles komisjonis.
> 
> Isegi kui korraga on üks komisjon, siis võivad need paraku aja möödudes muutuda. Sellest ka küsimus — kas kuvame viimast või esimest. Riigikogu liideses on nt https://rahvaalgatus.ee/initiatives/22-n%C3%B5uame-5g-tehnoloogia-paigaldamise-peatamist-eestis* algatusel kaks aktiivset komisjoni korraga, kus mõlemad on arutelusid pidanud — Keskkonnakomisjonis ja Sotsiaalkomisjonis. Eeldan, et kuvame alati kõige viimast.

Vastutab ja juhib ÜKS komisjon algusest lõpuni. Arutelud võivad toimuda mitmes. Kuvame seda ÜHTE, mille protsessi alguses määrab Riigikogu juhatus (see on otsuses kirjas, aga afaik toimub seal alati ka esimene arutelu).

**Comment by moll** [comment]
Tundub, et vastutada ja juhtida saavad siiski ka kaks komisjoni korraga. Ülalviidatud algatus on algusest saadik suunatud kahele komisjonile ja Riigikogu API viitab kahele komisjonile kui aktiivsele.

https://www.riigikogu.ee/tegevus/dokumendiregister/dokument/9f2e6794-53b1-413a-842f-2e451def4fe6 lehel on ka otsus kahele komisjonile suunamise kohta:

> Lähtudes Riigikogu kodu- ja töökorra seaduse §-st 1529 Riigikogu juhatus otsustab:
> Võtta menetlusse Liis Ellerti k.a 4. aprillil algatatud kollektiivne pöördumine „Nõuame 5G
tehnoloogia paigaldamise peatamist Eestis!“ ja edastada see menetlemiseks
keskkonnakomisjonile ja sotsiaalkomisjonile.

Pärast võin vaadata, kas leian ka algatusi, mille komisjon on vahetunud. Hetkel eeldaks, et Riigikogu API-s `responsibleCommittee` jadas oleksid need siis `active:false` lipuga, aga mine sa tea.

5G algatuse komiteed APIs, kus on näha ka `active` lippu:
```json
    "responsibleCommittee": [
      {
        "uuid": "4f907fd8-ace5-c3eb-d50a-b65606cd3621",
        "name": "Keskkonnakomisjon",
        "active": true
      },
      {
        "uuid": "44584179-67a8-ce54-da37-569f1a480919",
        "name": "Sotsiaalkomisjon",
        "active": true
      }
    ]
```

**Comment by moll** [comment]
Nüüd näeb tabel loetav välja ka mobiilis. Seal kuvatakse tulbad teineteise all ja osade ridade ees ka nimi.

**Comment by moll** [comment]
Lükkame tabeli laivi ilma graafiku/visualisatsioonina.

**Comment by infokujur** [comment]
Paar tähelepanekut:

- [ ] Ühisloome kuupäev tabelis õigeks

Meil on ühisloomes mitmetel algatustel tabelis kuupäev 01.01.1970 vt nt
![image](https://github.com/rahvaalgatus/rahvaalgatus/assets/12999094/bda062bf-f9f9-4980-8c22-f0b958c8fa85)

Samal algatusel on algatuse vaates õige kuupäev
![image](https://github.com/rahvaalgatus/rahvaalgatus/assets/12999094/e42cce30-bf02-49d3-9329-1a9214194b39)

- [ ] Kuupäevade sisendi vorming (mh keel) samaks väljundiga

Praegu on mm/dd/yyyy vaja on pp/kk/aaaa

**Comment by moll** [comment]
> Paar tähelepanekut:
> 
>     * [ ]  Ühisloome kuupäev tabelis õigeks

Oih, aitäh märkamast! See oli tingitud sellest, et kõik varasemad CitizenOSist imporditud algatused olid tegelikult avalikustamise kuupäevata ja vaikimisi sai neile andmebaasi märgitud kuupäevaks 1970-01-01. Faasijoon algatuse lehel kuvas seepärast ka algatuse loomise kuupäeva. Kuna CitizenOSilt edasi liikudes hakkas RA ka avalikustamise kuupäeva salvestama, saab täna tegelikult juba seda kõikjal kasutada. CitizenOSi algatuste avalikustamise kuupäevaks panin nende loomiskuupäeva. Peaks olema korras ja laivis.

>     * [ ]  Kuupäevade sisendi vorming (mh keel) samaks väljundiga
> 
> 
> Praegu on mm/dd/yyyy vaja on pp/kk/aaaa

Kus kuupäevad USA formaadis on? Ma näen vaid dd.mm.yyyy ehk 20.12.2024 stiili.

**Comment by moll** [comment]
>  Kuupäevade sisendi vorming (mh keel) samaks väljundiga

Aa, sa räägid ilmselt filtrite vormielementidest. Need tulevad brauserist ehk peaksid järgima süsteemi enda seadeid. Kui näed USA formaadis, siis see peaks viitama sellele, et arvuti on seadistatud ingliskeelseks ja/või kasutab UK/US kuupäevaformaate. Mis brauseriga vaatasid ja kui Windowis tagant, siis kas Windowsi kell-kuupäev taskbaril all nurgas on Euroopa/Eesti formaadis?

**Comment by infokujur** [comment]
- [ ] Fraasid on vaja lisada tõlketabelisse ja
- [ ] tõlked lisada

**Comment by moll** [comment]
Kõik algatuste tabeliga seotud tekstid peaksid olema tõlketabelis `initiatives_page.` prefiksiga võtmete all. Ingliskeelsed on olemas. Venekeelsed, nagu ikka, puudu.
