### ISSUE TITLE
Allkirjastamise nupu juurde meeldetuletus, et iga inimese kohta läheb kirja üks allkiri

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#363]
![Untitled](https://github.com/rahvaalgatus/rahvaalgatus/assets/12999094/86b8e340-308e-4987-aee9-455ba877a2a7)
Kahe nupu vahele tekstiväli punase tekstiga: NB! Ka mitu korda allkirjastades läheb inimese kohta kirja ÜKS allkiri.

**Comment by infokujur** [comment]
Lause läheb hoopis lehe lõppu.

**Comment by moll** [comment]
Vaatame, kas sellest on abi:

![Screenshot from 2023-10-27 20-58-54](https://github.com/rahvaalgatus/rahvaalgatus/assets/156837/e70ae559-196f-4966-bbba-b81c54fde323)

**Comment by moll** [comment]
Asendaks käesoleva issue https://github.com/rahvaalgatus/rahvaalgatus/issues/355 -ga, mille pealkirja tegin üldisemaks. Praegu veel on topeltallkirjastamise põhjus teadmata ja rohkemate tekstide lisamine ei pruugi aidata.

**Comment by infokujur** [comment]
#355 tegeleme ka, see issue on siin quickfix seniks, kuni saame rohkem andmeid.

**Comment by moll** [comment]
Allkirjastamise nupu juures on meeldetuletus arvesse minemise kohta nii KOVi kui ka Riigikogu algatuse puhul.
