### ISSUE TITLE
Uuendada KOV kaardil valijate arvud, lävendid ning lisada täpsustus

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#366]
Lävendid uuendada 2021.a KOV valijate numbrite järgi ära (viidatud tabel):
https://www.siseministeerium.ee/tegevusvaldkonnad/rahvastikutoimingud/rahvastikustatistika#elanike-ja-valijate-

Täpsustavaks disklaimer kaardi alla - Valimisealiste elanike arv ja lävend on kajastatud 2021. aasta kohalike valimiste seisuga.

Kaardil on mulli sees vaja täiendada sõne:

5432 **valimisealist** ja 54 allkirja vajalik algatustele.

**Comment by karlpallo** [comment]
Ma tõmbaks sellele pidurit korraks.
Esiteks ma 2021. aasta andmetega ei hakkaks "uuendama", sest need on juba vananenud andmed (mul on endal 2022. aasta andmed olemas juba), kuid tegin päringu Rahvastikuregistrisse, et kõige värskemad andmed saada hääleõiguslike kodanike arvu kohta KOVides.
Teiseks, juhul kui me muudame praeguse süsteemi äranii et enam ei ole puhvrit (ja ma kardan, et see tähendab reaalsuses rohkem tagasilükatud algatusi ja seega raisatud digiallkirjade raha/aega ning rohkem tööd aka me peaks seda otsust veel arutama), siis oleks vaja tekitada mingi pop-up juurde ka. Ala, et kui vajutad "saada algatus", siis annab edasi info, et lihtsalt lävendi ületamisest võib-olla ei piisa, sest kõik allkirjastanud ei pruugi olla vastava KOVi sissekirjutusega vms.

**Comment by infokujur** [comment]
1) Jah - uuendame, kui saad vastuse - anna siia märku.
2) Palun paku selle pop-upi sõnastus.

**Comment by moll** [comment]
Tabel, mis ma Siseministeeriumilt möödunud nädalal sain, puudutab Riigikogu valijaid seisuga 3. veebr 2023. Seal on ka KOVi põhiselt numbrid olemas. Kas see pole praktikas sama number, mis valimisealiste arv?

 
[Riigikogu valijate arv 03.02.2023.xlsx](https://github.com/rahvaalgatus/rahvaalgatus/files/12879547/Riigikogu.valijate.arv.03.02.2023.xlsx)

**Comment by infokujur** [comment]
Ei. KOV valijad on 16+ alalised elanikud ja Riigikogu valijad 18+
kodanikud.

**Comment by karlpallo** [comment]
Siin on hääleõiguslike elanike arv KOVides 2023. aasta oktoobri seisuga: [](url)
[20231012_1924_KOV_haaleoiguslik_arv-1.xlsx](https://github.com/rahvaalgatus/rahvaalgatus/files/12892360/20231012_1924_KOV_haaleoiguslik_arv-1.xlsx)

Pop-up KOV algatustel võiks olla näiteks: "Kohalik omavalitsus kontrollib allkirjastanute elukohajärgset sissekirjutust, mistõttu võib arvesse minevate allkirjade hulk pärast saatmist väheneda. Rahvaalgatus.ee meeskond soovitab vähemalt 10% suuruse digiallkirjade puhvri olemasolu. Kas soovid jätkuvalt algatust saata?" - Ei, Jah.

**Comment by moll** [comment]
Karli jagatud KOVide hääleõiguslike elanike arv on nüüd laivis. KOVi kaardil on kõik kolm numbrit välja toodud — elanike arv, valimisealiste arv ja lävend.

**Comment by moll** [comment]
Lisame KOVile algatust saates ka kommentaaris https://github.com/rahvaalgatus/rahvaalgatus/issues/366#issuecomment-1761290028 mainitud hoiatuse.

**Comment by moll** [comment]
KOVile saatmise hoiatus on ka lisatud. Asub tõlketabelis `SEND_TO_LOCAL_GOVERNMENT_TEXT` all. Lisasin lihtsa ingliskeelse tõlke ka. Laivi läheb homme õhtul või nädalavahetusel koos fancy digiallkirjastamisega (https://github.com/rahvaalgatus/rahvaalgatus/issues/65).
