### ISSUE TITLE
Automaatkiri algatajatele kuu enne nende algatuse aegumist

### ISSUE THREAD

**Issue by karlpallo** [rahvaalgatus/rahvaalgatus#369]
Tekst võiks välja minna, siis kui algatusel tiksub 17 kuud täis:

"Tervist 

Teie algatus X aegub Rahvaalgatus.ee keskkonnas ühe kuu pärast "insertkuupäeval". Pärast aegumiskuupäeva möödumist algatusele kogutud allkirjad anonüümitakse ja Teil ei ole võimalik enam algatust ära saata.

Rahvaalgatus.ee keskkonnas saab algatusele allkirju koguda maksimaalselt 18 kuud. Nii kaua säilitatakse ka algatusele antud allkirju. Selle aja täitudes või varem, kui algatus kogub allkirjad kiiremini kokku ning see esitatakse vastavale institutsioonile, eemaldatakse allkirjadelt isikuandmed. See tähendab, et kustutatakse krüptograafiline allkiri ja säilitatakse vaid isikukoodi 3 esimest numbrit (allkirjastaja sugu ja sünniaasta), allkirjastamise kellaaeg, ligikaudne asukoht ning viide algatusele. Anonüümitud andmete põhjal on võimalik väljastada statistikat. 

Kui Te soovite oma algatust ära saata, siis saate seda teha *SIIN*

Parimat
Rahvaalgatus.ee meeskond"

**Comment by moll** [comment]
Ee.. selline meil juba läheb välja põhimõtteliselt. 3 kuud enne ja 2 nädalat enne. Tekst ise on `SIGNING_EXPIRING_EMAIL_BODY` võtme all tõlketabelis.

**Comment by karlpallo** [comment]
Aa okei, no siis pole üldse mingit probleemi sellega atm
