### ISSUE TITLE
Kommentaaride lipustamine

### ISSUE THREAD

**Issue by karlpallo** [rahvaalgatus/rahvaalgatus#370]
Kuna kommentaaride jälgimine ei ole enam suure mahu tõttu igapäevaselt võimalik, siis meil võiks olla süsteem paigas, et kui näed Rahvaalgatus.ee hea tava vastu eksivaid kommentaare, saad sellest teada anda, teavitus tuleb "info@rahvaalgatus.ee" ning Rahvaalgatus.ee meeskond vaatab selle üle.

**Comment by infokujur** [comment]
Dublikaat Kommentaari raporteerimise teema on siin, arendame seda edasi: https://github.com/rahvaalgatus/rahvaalgatus/issues/51
