### ISSUE TITLE
Algatuse loomise loogika uuendus

### ISSUE THREAD

**Issue by karlpallo** [rahvaalgatus/rahvaalgatus#373]
Uuendada algatuse loomise loogikat, et pärast arendust moodustuks kolm kastikest, kuhu vastuste kirjutamisel moodustub algatus selle kõigi vajalike osadega.
 
Pärast arendust:

Algatuse pealkiri
Algatuse sisu

Järgnevatesse kolme kasti kirjutatud infost moodustub algatust luues üks terviktekst. Nende ülesandeks on vaid Sind aidata võimalikult kõrge kvaliteediga algatuse loomise suunas. Tutvu ka [Rahvaalgatus.ee kasutamise hea tavaga](https://rahvaalgatus.ee/about).

JUHTLÕIK (200TM koos tühikutega mahupiirang + by default oleks BOLDis)

Too siia sissejuhatavasse lõiku välja üleskutse, mis annab lühidalt ja selgelt edasi kõige olulisema info, samal ajal hoides lugejate huvi. Mõtle, kuidas soovid oma sõnumit inimesteni viia. 

PROBLEEMIPÜSTITUS 

Too siin välja, mis on probleem ning miks praegune olukord Sind ja Su mõttekaaslasi ei rahulda.  

LAHENDUS

Uute lahenduste väljapakkumine on algatuse loomise olulisim osa. Too siin välja, mis on Sinu väljapakutud lahendus probleemile. Rahvaalgatus.ee meeskond on praktikas näinud, et mida konkreetsem ja kvaliteetsem on üleskutse, seda parem on ka menetlusprotsess. Seega mida rohkem statistikat, uuringuid ja head argumentatsiooni, seda parem!

Parem vaade Docsis:
https://docs.google.com/document/d/1SKhjO68Nq2fqhnniBGbe8wt_Wg63f1vXIdykSgKQcMk/edit

**Comment by moll** [comment]
@karlpallo käis välja, et need kolm sektsiooni võiksid ka kohustuslikud olla. Seda oleks parim kontrollida allkirjastamisele saates, (ja vajadusel varem lihtsalt hoiatada), et saaks ühisloomes oma tööd mugavalt salvestada, ilma et peaks vorminõuetega võitlema.

"Hea tava" viite võiks juhtlõigu ja pealkirja vahele liigutada. Siis saab sinna ka muid juhiseid lisada.

**Comment by moll** [comment]
- Eemaldame vahepealkirjad teksti kuvades.
  Nii ei pea inimene, kes on teksti väljaspool RA-d kirjutanud, hakkama võitlema RA lisatud vahepealkirjadega, ning saab teksti lihtsalt poolitada kahe kasti vahel. Võib-olla peaks siis küll andma inimestele võimaluse kõik pasteda ühte kasti ja mitte sundima neid oma teksti poolitama või kolmeks tegema.
- Paneme sissejuhatava teksti peale pealkirja.
  Seal saab mainida nt, et kolmest kastist moodustub tervik.

**Comment by moll** [comment]
Mitmes osas kirjutatud teksti enam vahepealkirjadega ei eraldata ning muutmise lehel on sissejuhatav tekst. Seda saab @karlpallo `edit_initiative_page.text.sections_description` võtme alt tõlketabelis kohandada.

**Comment by karlpallo** [comment]
Tundub hea, ma muudaks veel ühe väikese asja ära. Juhtlõigul võiks olla pikkuse maksimum (nt 30 sõna). Kuna juhtlõigu font on suurem muust tekstist, siis ei tahaks, et juhtuks olukord, kus algataja kopeerib terve teksti ainult juhtlõigu kasti ning tekib see: 
![pilt](https://github.com/rahvaalgatus/rahvaalgatus/assets/101321361/cc8af8c7-a561-4e74-859e-fa8312275a6b)

**Comment by moll** [comment]
Lisasin 280 tähemärgi piirangu juhtlõigule, mille pikkust kontrollitakse hetkel nii algatust luues kui ka salvestades. Potentsiaalselt saaks seda kontrollida ka ainult allkirjastamisele saates, kui tahta inimestel vabamalt teksti muuta.

Juhtlõiguga toimetades peitsin juhtlõigu kohalt ka need vormindusnupud, mis sinna ei sobi — loetelud, plokktsitaadid ja koodiplokid. Jäid tavalised _bold, italic, strikethrough_.

![image](https://github.com/rahvaalgatus/rahvaalgatus/assets/156837/f8b0360d-6060-479c-979a-2f17c251059e)
