### ISSUE TITLE
Allkirjade arhiivi lehele visualisatsioon/diagrammid

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#375]
Seotud: https://github.com/rahvaalgatus/rahvaalgatus/issues/361

Tõstan 361st siia ka:
ringdiagramm - Menetleja, tulpdiagramm - TOP 20 enim allkirjastud algatust

**Comment by infokujur** [comment]
Need diagrammid on filtrid, mis läbi räägitud ja töösse pandud.

**Comment by moll** [comment]
Üks ringdiagramm ootab tagasisidet https://next.rahvaalgatus.ee/initiatives lehel. Puudu vast mingi pealkiri talle ja väljanägemist võib kohendada (k.a värve), aga kas funktsionaalselt tundub selline nagu ette kujutasite? Mis funktsionaalsust ta veel omada võiks? Protsenti? Legendis hiirega üleminnes ehk sektori väljatoomist? Praegu on vaid vastupidi — sektoritel hiirega liikumine toob esile legendis õige rea.

**Comment by moll** [comment]
Lisasin tulpdiagrammi näidise ka. Testkeskkonnas on vaid käputäis allkirjadega algatust, nii et isegi kümme ei saa kokku. Võin sinna genereerida allkirju juurde sellises proportsioonis nagu täna laivis, kui soov on. Siis saab näha, kuidas graafikud päriselt välja nägema hakkaksid.

**Comment by infokujur** [comment]
Nextis need diagrammid ei toimi  filtritena.

**Comment by infokujur** [comment]
- [ ] Taasta algseis nupp (näita kõiki tagasi vms)
