### ISSUE TITLE
Matomo installimine serverisse logide põhjal analüütikaks

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#378]

**Comment by infokujur** [comment]
Impordime 2023 algusest ning selle pealt esialgne analüüs, kuidas infovajadus on kaetud.

**Comment by moll** [comment]
2023 märtsist andmed Matomos. Jaanuarist täitsa ei saanud, sest need olid ühes vanemas formaadis, mille importimist hetkel ei toeta.
