### ISSUE TITLE
Mitme Riigikogu komisjoni toetamine

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#379]
Algatustel võib olla mitu aktiivset Riigikogu komisjoni. Hetkel on meil algatuse lehel ja andmebaasis salvestatud vaid üks, kuid tuleb välja, et vähemalt ühel algatusel on neid kaks.

Algatus kahe komisjoniga: https://rahvaalgatus.ee/initiatives/22-n%C3%B5uame-5g-tehnoloogia-paigaldamise-peatamist-eestis*

https://www.riigikogu.ee/tegevus/dokumendiregister/dokument/9f2e6794-53b1-413a-842f-2e451def4fe6 lehel on otsus kahele komisjonile suunamise kohta:

> Lähtudes Riigikogu kodu- ja töökorra seaduse §-st 1529 Riigikogu juhatus otsustab:
> Võtta menetlusse Liis Ellerti k.a 4. aprillil algatatud kollektiivne pöördumine „Nõuame 5G
tehnoloogia paigaldamise peatamist Eestis!“ ja edastada see menetlemiseks
keskkonnakomisjonile ja sotsiaalkomisjonile.

Riigikogu API kuvab selle algatuse kohta ka kahte `active` lippu:

```json
    "responsibleCommittee": [
      {
        "uuid": "4f907fd8-ace5-c3eb-d50a-b65606cd3621",
        "name": "Keskkonnakomisjon",
        "active": true
      },
      {
        "uuid": "44584179-67a8-ce54-da37-569f1a480919",
        "name": "Sotsiaalkomisjon",
        "active": true
      }
    ]
```

Jätk https://github.com/rahvaalgatus/rahvaalgatus/issues/361#issuecomment-1938385544 issuele.

**Comment by infokujur** [comment]
Juhatuse otsuse järgi kuvada komisjonid.

**Comment by moll** [comment]
Algatuste tabeli lehele kuvame algatust mitu korda, kui tabel on sorteeritud menetleja järgi ja algatus on kahes komisjonis.

**Comment by moll** [comment]
Teel mitme komisjoni kuvamiseni said komisjonid nn masinloetavaks tehtud ehk ülesloetletud Rahvaalgatuse koodis. Varasemalt salvestati Riigikogu liidesest tulnud eestikeelne komisjoni nimi maha. Nüüd aga sisemine identifikaator, et komisjoni nime saaks ka tõlkida. Ingliskeeles algatuse lehte vaadates (juba laivis) on nüüd nt menetlusinfos komisjoni nimi ka ingliskeeles.

**Comment by moll** [comment]
Mitme komisjoni tugi on nüüd lisatud. [Testkeskkonnas](https://next.rahvaalgatus.ee/) üleval, toodangus veel mitte. Testkeskkonda ühtki päris kahe komisjoniga algatust imporditud pole, nii et lisasin katsetamiseks suvalisele (https://next.rahvaalgatus.ee/initiatives/75) ühe teise komisjoni ka.

Ainsana on puudu algatuse topelt näitamine algatuste lehel, kui algatused on grupeeritud menetleja järgi ja algatus on kahes komisjonis. Ma pakuks, et selle võiks edasi lükata. Tundub natuke liigne töö veel haruldase use-case'i jaoks — praegu on Riigikogu APIs vaid üks algatus, millel päriselt kaks komisjoni on.
