### ISSUE TITLE
Rahvaalgatus.ee - Abi peamenüüs linkida urlile > http://help.rahvaalgatus.ee/abi/tagged/juhend

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#38]
Praegu on: http://help.rahvaalgatus.ee/abi
Vaja on: http://help.rahvaalgatus.ee/abi/tagged/juhend

**Comment by moll** [comment]
Kas inglise keele puhul http://help.rahvaalgatus.ee/help/tagged/guide ja vene help.rahvaalgatus.ee/pomosh/tagged/Руководство?

**Comment by infokujur** [comment]
@moll Jah. Tänan tähelepanu juhtimast.

**Comment by moll** [comment]
Sel juhul laivis. ;)
