### ISSUE TITLE
RIA SiGa toetamine allkirjastamisteks

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#380]
Kuna allkirjastamine on suurim kulu Rahvaalgatusele, uurime, kas annab kasutada [RIA arendatud SiGa teenust](https://www.ria.ee/riigi-infosusteem/elektrooniline-identiteet-ja-usaldusteenused/digiallkirja-serverteenused) digiallkirjade kogumiseks. 

Dokumentatsion:
- https://open-eid.github.io/allkirjastamisteenus
- https://github.com/open-eid/SiGa/wiki

**Comment by infokujur** [comment]
Sellisel kujul ei sobi.
