### ISSUE TITLE
CSV eksport algatuste lehest

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#384]
Võtab ka valitud filtreid arvesse.

**Comment by moll** [comment]
Esmane implementatsioon valmis. Toimib kõikide olemasolevate filtrite ja sorteerimistega. Kõik tulbad, mis algatuste lehel on, esinevad ka CSV-s. Katsetada saab https://next.rahvaalgatus.ee/initiatives lehel "Lae alla CSV" lingilt, mis on kohe tabeli paremal üleval. Võib-olla peaks selle asendama rippmenüüga, kus saab eksportida tabeli sisu nii CSV-sse kui ka JSONi. Praegu vajab JSONi formaadis pärimine API juhendi lugemist ja natuke rohkem tehnilisi teadmisi.

Tulpade nimedeks (ehk CSV esimene rida) said terminid, mis on kas telgitaga kasutuses või seotud filtrite ingliskeelsete nimedega. Ei teagi kohe, mis optimaalne oleks. Need, kes pisutki midagi automatiseerida tahavad, tõenäoliselt eelistavad masinloetavaid tulpade nimesid (ehk tühikuteta ja ingliskeelseid jne). Mittearendajatest inimesed ehk aga mitte.

**Comment by infokujur** [comment]
Oluline, et terminid on läbivalt samad. Tõlkele/dokumentatsioonile saab viidata, kui me lisainfo mummudeni mingi hetk jõuame.

CSV tundub piisav, sest vaevalt JSON-i tahaks kasutada keegi, kellel üldse mingit tehnilist teadmist ei ole ja dokumentatsiooni üles ei leia (mida me küll saame paremini leitavaks teha).
