### ISSUE TITLE
KOV rippmenüüs KOV-id vale haldusjaotuse järgi

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#388]
vt rippmenüü siin: https://rahvaalgatus.ee/local
ja rippmenüü "Saaja": https://rahvaalgatus.ee/initiatives

**Comment by moll** [comment]
Hei. Saad sa täpsustada, mida pead silmas "vale haldusjaotuse" järgi? Kas kuskil on mõni vald vales maakonnas?

Valdade info pärineb https://docs.google.com/spreadsheets/d/1DynXZ8Um9TsiYPDaYW3-RTgaPy8hsdq9jj72G41yrVE/edit?pli=1&gid=0#gid=0 tabelist.

**Comment by infokujur** [comment]
Ja! Nüüd nägin ka - kõik ok. Otsisin konkreetset valda. Kas oleks võimalik need maakonnad ära võtta ja panna tähestiku järjekorda need loendid?
Või oli seal mingi väga konkreetne põhjus, miks maakondasid ka rippmenüüs näidata?

**Comment by moll** [comment]
Tänases kõnes arutasime, et ehk tõesti lihtsam otsida, kui loetelu on tähestiku järjekorras. Maakonnad näevad kenad välja, aga ei saa eeldada, et kõik teavad, kus maakonnas mõni KOV asub.

**Comment by moll** [comment]
Nüüd peaks kõikjal olema KOVid tähestiku järjekorras.
