### ISSUE TITLE
Display error message when Chrome on Windows XP fails to connect to CitizenOS because of cipher mismatch

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#39]
Sõnede failis on tõlked olemas.

**Comment by infokujur** [comment]
@moll palun sildista.

**Comment by moll** [comment]
Arvan, et see pole enam aktuaalne. Rahvaalgatus võtab enamikel juhtudel Citizeniga ise ühendust ja kuvab selle vastused inimesele. Ainus koht, kus inimese arvuti Citizeniga otse suhtleb, on sisselogimisel ja seal pole kahjuks meil võimalus sellise probleemi kohta ise veateateid enam kuvada.

Sulgen seniks, kuid kui tuleb mõni lahendus mõttesse, võime taas avada.
