### ISSUE TITLE
RU keelest loobumine kasutajaliidses

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#391]
Praegu enamus tõlkimata ja näeb kehv välja. Ressurssi ei ole, et teha täielik keeletoimetatud vene tõlge. Kasutajal jääb võimalus ekraanilehitsejaga tõlkida.

**Comment by moll** [comment]
Vene keel eemaldatud. Algatusi saab edasi lisada/tõlkida ka vene keeles.
