### ISSUE TITLE
Luua MobiilID ja SmartID allkirjastamise aknasse lisatekstiväli

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#393]
![image](https://github.com/user-attachments/assets/bb58cde1-7e95-4d42-9446-cc826722eeb7)

Tekst A 

Mobiil-ID-ga allkirjastamine on sulle tasuta tänu annetustele.
Signing with Mobiil-ID is free for you thanks to donations.

Tekst B

Smart-ID-ga allkirjastamine on sulle tasuta tänu annetustele.
Signing with Smart-ID is free for you thanks to donations.

**Comment by moll** [comment]
Laivis. Just hirmus kaunis välja ei näe. Ma ei tea ka kohe, kuidas seda paremaks teha. Loodetavasti ei sega allkirjastamist.

![image](https://github.com/user-attachments/assets/cab869b3-c372-4566-ba5e-f1d88c2741d0)
