### ISSUE TITLE
Menetlus lõppenud

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#4]
- Esilehelt ära
- Menetlus lõppenud märge algatuse ruutu.
Kuvatav info: kuupäev, lõpetatud sümbol. Kas see info mahub jalusesse?

Praeguse seisuga need algatused:
- Lendorav 07.06.2016
https://rahvaalgatus.ee/initiatives/d400bf12-f212-4df0-88a5-174a113c443a
- Glüfosaat 24.11.2016
https://rahvaalgatus.ee/initiatives/343fa0e9-d3c2-4bde-b027-7ff76014fbd9
- Väike Väin 18.10.2016
https://rahvaalgatus.ee/initiatives/e1c1d544-0e80-4a82-a6f3-e02dc2f8565c

**Comment by moll** [comment]
Lisasin lõpetatud algatuste toe. @infokujur, palun viska pilk peale: http://next.rahvaalgatus.ee/initiatives/332e9231-b21b-4c2f-b470-1e87b749f129. Kas on midagi sellist, mida ette kujutasid?

Hetkel ilmub "Lõpeta menetlus" nupp algatuste administraatorile kohe kui algatus on Riigikokku saadetud. Testimiseks võta mõni suvaline menetluses olev algatus ja logi algatajana sisse. Näiteks http://next.rahvaalgatus.ee/initiatives/9a03964f-ca77-437f-92e9-7cf8bb76edcb ja "Seitsmes Testnumber" (+37060000007 ning 51001091072). Lõpetatud algatusi pole esilehel näha. Algatuste lehel on.

**Comment by moll** [comment]
> Menetlus lõppenud märge algatuse ruutu.
> Kuvatav info: kuupäev, lõpetatud sümbol. Kas see info mahub jalusesse?

Menetluse lõpukuupäeva osas pean veel uurima. Hetkel jäi lihtsalt häälte arv.

**Comment by moll** [comment]
@loorm: Palume algatuse lõpetamise kuupäeva salvestamiseks välja.

**Comment by moll** [comment]
Ootab Citizenilt ka ühte API muudatust, et lõppenud algatusi eristada lõppenud diskussioonidest või hääletustest, mis Riigikokku ei jõudnud.

**Comment by moll** [comment]
Selgituseks Margole:
Rahvaalgatus soovib kuvada lõppenud ja Riigikogust läbi käinud algatusi eraldi koos lõpukuupäevaga. Selleks kuluks ära, et backend mäletaks, millal algatus lõppes. See kuupäev ei pruugi ka olla sama, mil lõpetamise nuppu Rahvaalgatuses vajutatakse. "Eventidega" seda kuupäeva siduda ei tahaks, sest evente võib sõltumata lõpust juurde ilmuda. Sestap mu ettepanek teha eraldi lõpetamise kuupäeva väli, mida Rahvaalgatus saab staatust muutes kaasa anda.

Teine lahtine küsimus on backendi staatuse `closed` üle. Praegu läheb see nii feilinud diskussioonidele kui õnnelikele lõppudele. Kuidas peaks eraldama Riigikogust läbi käinud algatusi ebaõnnestunud hääletamistest?

**Comment by moll** [comment]
Kuidas lõppenud algatust nimetada võiks? Kas "Lõpetatud" või äkki "Menetletud" nagu riigikogus olevad algatused on täna "Menetluses"?

**Comment by infokujur** [comment]
Menetletud kõlab paremini ja siis erineb ka lihtsalt vahepeal lõpetatud/lõppenud (mis menetlemiseni ei jõudnud) algatustest.

NB! Algatuse autor ei saa ise lõpetada. See on midagi, mis käib superadmin rolli juurde. #43 

Proovisin testida, aga tuli "Vabandame, aga midagi meie süsteemis ei toiminud. Proovi palun uuesti. Kui viga kordub, võta ühendust kasutajatoega."

**Comment by moll** [comment]
Jaa, *suletud* Riigikogust läbi käinud algatust vaadates tundub Citizen hetkel viskavat 403 Forbidden vea, kui selle menetlusinfot pärida. Ootab @tiblu-lt kinnitust.

**Comment by tiblu** [comment]
@moll Tõesti, API-s esines puudujääk. See viga on eilse seisuga parandatud.

**Comment by tiblu** [comment]
@moll @infokujur Kustutasin eelmise kommentaari, sest see läks valesse auku.
Ühesõnaga - tahetakse, et "moderaator" saaks teha "followUp->closed". 
Äkki peaks seda hoopis Riigikogu kantselei tegema?
Kokkuvõttes peaks @loorm nende asjades viimase sõna ütlema.

**Comment by infokujur** [comment]
@tiblu Loodame, et nende OD API #20 annab selle info otse, aga seni kuni see pole testitud (sisse vaadanud, mis seal ikkagi tuleb), integreeritud ja meil UI valmis, on vaja kiiret fixi.

**Comment by moll** [comment]
See, et @tiblu või ma su käsitsi teatud algatuste "administraatoriks" lisan, quickfixi alla vist käib, kas mitte? :)

**Comment by tiblu** [comment]
@moll Quickfixina käib, aga siis peaks ka õigused pärast uuesti ära võtma. Teine võimalus on quickfixina käsitsi "closed" panna.

**Comment by moll** [comment]
Menetletud algatuste kuvamine on lahendatud (nagu https://github.com/rahvaalgatus/rahvaalgatus/issues/36).
Menetluse lõpetamise kuupäeva välja küsimus ootab aga @loorm-i kinnitust.

**Comment by infokujur** [comment]
@moll Kas sama välja näitamise küsimus laieneb ka sellele taskile? #49

**Comment by moll** [comment]
Põhimõtteliselt, jah. Konkreetsete etappide kestuste kirjeldamiseks peaks Citizen ka veel salvestama algatuse avalikustamise hetke. Seda ta ka ei tee. Mikul oli plaanis ka algatuse muutuste logi — kas see oli midagi, mille kallal juba praegu töötad, @tiblu? Mäletan, et aeg tagasi olin ka mina selle võimalik implementeerija. :)

**Comment by infokujur** [comment]
@moll Palun pane "menetlus lõpetatud" järgmistele algatustele:

Lendorav 07.06.2016
https://rahvaalgatus.ee/initiatives/d400bf12-f212-4df0-88a5-174a113c443a
Glüfosaat 24.11.2016
https://rahvaalgatus.ee/initiatives/343fa0e9-d3c2-4bde-b027-7ff76014fbd9
Väike Väin 18.10.2016
https://rahvaalgatus.ee/initiatives/e1c1d544-0e80-4a82-a6f3-e02dc2f8565c
Ravikanep 02.05.2017
https://rahvaalgatus.ee/initiatives/cde86956-ae36-4f04-b1d0-38277147512b
Kanepi turg 02.05.2017
https://rahvaalgatus.ee/initiatives/059ea23f-cef3-4ab5-a138-adfe915328ee

**Comment by moll** [comment]
Done. Näha https://rahvaalgatus.ee/initiatives lehel lõpus. Esilehelt seega peidetud.

**Comment by infokujur** [comment]
@moll Palun pane "menetlus lõpetatud" järgmistele algatustele:

- „Eestimaa kaitseks“ 06.06.2017
https://rahvaalgatus.ee/initiatives/373edf9a-f39c-4c69-894e-3f1cf043d845

- Palun paranda vale kuupäev protokoll 116 juures. Peab olema 16.05.2017.
Algatuse "Lisame riigipüha. Lisame puhkepäeva, kui rahvuspüha või riigipüha langeb nädalavahetusele."
https://rahvaalgatus.ee/initiatives/5140419e-2c53-47d7-a596-922a6bb1eeff/events

**Comment by moll** [comment]
Done and done.

**Comment by infokujur** [comment]
@moll Menetlus lõpetatud
- 20.06.2017 Balti riikide vahelise Rail Balticu lepingu allkirjastamine 31. jaanuaril on praegusel kujul lub...
https://rahvaalgatus.ee/initiatives/dbe5cd08-afe1-47fd-aac6-6abb8e1f24ea/events

**Comment by moll** [comment]
Ka tehtud.

**Comment by infokujur** [comment]
#43

**Comment by infokujur** [comment]
@moll Patarei merekindlus on ohus menetlus lõpetati 06.02.2018 https://rahvaalgatus.ee/initiatives/db3d09d6-18ba-467a-9527-6bfc0605aab9

**Comment by moll** [comment]
@infokujur: Patarei liigutatud "Menetletud" staatusse.

**Comment by moll** [comment]
@infokujur, "Hoolduskindlustus" liigutatud "Menetletud" staatusse.

**Comment by infokujur** [comment]
@moll Palun panna menetlus lõpetatud: Aita lõpetada seaduslikud veelindude tapatalgud! 5.06.2018 seisuga https://rahvaalgatus.ee/initiatives/92cc16ee-107e-4208-b92c-2ffed24d4f4b/events

**Comment by infokujur** [comment]
@moll Palun panna menetlus lõpetatud: Keelustada Eestis GMO-kultuuride kasvatamine 17.04.2018 seisuga https://rahvaalgatus.ee/initiatives/78ba564c-9843-4dc1-8e79-dcad2941537c

**Comment by moll** [comment]
Mõlemad liigutatud "menetletud" staatusse, @infokujur.

**Comment by infokujur** [comment]
Avan edaspidi iga kord uue teema.
