### ISSUE TITLE
Improve error message for when digital signature plugins are disabled

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#40]
Sinu arvutis puudub digitaalse allkirjastamise tarkvara. ...". Tegelikult viga hoopis selles, et pistikprogrammid on blokeeritud ("plug-ins were blocked on this page").

**Comment by infokujur** [comment]
#39 Siin ka paremad veateated vaja.
@moll Palun sildista

**Comment by moll** [comment]
Mul on kahtlus, et me ei saa eristada neid kahte situatsiooni. Mul pole Id-kaardi softiga Firefoxi käepärast, et kohe testida, kuid tõenäoline on, et brauser ei anna veebilehele pistikprogrammi eksistentsi kohta enne infot kui see lubatud ei ole. Oled kuskil täheldanud teistsugust käitumist, @infokujur?

**Comment by infokujur** [comment]
@moll Ei ole täheldanud, aga ma ei ole ka nii massiliselt testinud. Praegu ei ole kasutajad palju kurtnud ka, kuna aktiivseid kampaaniaid ei ole.

Sellisel juhul on parem veateade vaja kuvada. On me.

**Comment by infokujur** [comment]
See on mingil hetkel korda läinud.
