### ISSUE TITLE
Admin/Superadmin roll

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#43]
Erinevad õigused, mis praegu käivad läbi @tiblu.

#8

**Comment by tiblu** [comment]
@infokujur @moll Et menetluse teavet sisestada, said osapooled e-kirjas tokeni, millega seda teha. Admin roll ei tule kõne alla, sest siis saab muuta kogu Algatusega seonduvat, mis poleks aus - las algataja ise hoolitseb oma asjade eest ja üritame vältida liigset modereerimist ning kallutamist.
Tegelikult peaks nendes teemades otsustama koos @loorm -ga.

**Comment by infokujur** [comment]
Superadminil vaja:
- Kasutajakontaktid (ligipääs ja haldamine)
- Kontosid ühendada (isikukoodi lisamine kontole, et saaks ID-ga sisse)
- Algatust lõpetada ja taasavada (menetlus lõpetatud staatus)
- Menetlusvaatesse info lisamine

**Comment by infokujur** [comment]
Osaliselt API-s olemas moderaatori rollil.
Hiljem samad õigused liiguvad superadmin rollile üle.
1. Teema autori kontaktandmeid näeb moderaator "Minu teemad" vaates vastava teema andmetes, hoides hiire kursorit autori nime peal.
2. Kommentaari autori andmed on moderaatori õigustes kasutajale kuvatud kommentaari juures, autori nime juurest avatava drop-downiga.
3. Avaliku teema kaasautorite andmed.

**Comment by moll** [comment]
@tiblu delegeerib otsuse Margo @loorm'ile.

**Comment by moll** [comment]
Kuna administreerimise liides sai mingi aeg tagasi laivi saadetud, arvan, et võib _issue_ sulgeda. Kasutajakontodega seotud tegevusi seal küll veel teha ei saa, kuid käsitleme neid siis, kui konkreetsed vajadused kerkivad.
