### ISSUE TITLE
Kampaania algataja kontaktide kuvamine/jagamine huvilistele

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#44]
Kellele on just korraldajale mingisuguseid küsimused, võiksid need küsimused saada kuhugi esitada.
Algataja kontaktide avaldamine vabatahtlik

**Comment by infokujur** [comment]
#21

**Comment by moll** [comment]
Saab lahendada algatuse märkmetega: https://github.com/rahvaalgatus/rahvaalgatus/issues/54#issuecomment-396518957.
