### ISSUE TITLE
Kommenteerimine menetletud algatusel

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#46]
Citizen viskab praegu serveri veateate kui keegi Rahvaalgatusel üritab kommenteerida menetletud (suletud) algatusel. Kas see peaks olema võimalik, @infokujur? Kui Citizen hakkab kommenteerides meelde jätma ka algatuse faasi, siis võiks ju lubada ka kommenteerimist algatuse menetluse ajal ja pärast sedagi...

**Comment by moll** [comment]
Citizeni error oli ajutine, kuid küsimus, kas ja kuidas kommenteerimine peale menetlust peaks toimima, kehtib edasi. ;)

**Comment by infokujur** [comment]
@moll pm küll. See teema tuleb ühtselt läbi mõelda koos nende issudega #34 #19 #20 #35 

Praegu on otsuse koht - kus on lõpp? Kui on arhiveeritud (mõju hinnang jms tehtud), siis kommentaare ja arvamust võiks küll veel saada kuskil avaldada, aga ta ei oleks enam algatuse/protsessi vaates (kus praegu kommentaarid on). Ehk jätan lahtiseks ja ootan selgumist viidatud teemades.

**Comment by moll** [comment]
@tiblu, on mul õigus, et see sai teil vahepeal parandatud? Lülitasin menetletud algatuste kommenteerimise mitu nädalat tagasi sisse ja tollasel katsetusel töötas. Igaks juhuks küll küsin üle, kas on _by design_ ja jääb töötama?

**Comment by tiblu** [comment]
@moll Jah, see on parandatud.

**Comment by moll** [comment]
Thx.
