### ISSUE TITLE
Inimloetav veateade Windows 10 ja Edge'iga allkirjastamise jaoks

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#47]
Windows 10 Edge brauseriga ei saa Id-kaardiga hääletada. Põhjuseks Id-kaardi tarkvara. Seda võiks külastajale paremini teavitada kui.... ei mäleta hetkel, kas ja mis veateade selle peale preagu tuleb.

**Comment by infokujur** [comment]
Puudub tarkvara teade. Ticket 749

**Comment by infokujur** [comment]
Ei ole probleem hetkel enam.
