### ISSUE TITLE
Kuupäevas viga

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#5]
https://rahvaalgatus.ee/initiatives/343fa0e9-d3c2-4bde-b027-7ff76014fbd9/events

Siin vaja kahe menetlusetapi pealkirjas 25.11.2016 vahetada 24.11.2016 vastu.

**Comment by infokujur** [comment]
@moll Palun võta töösse.

**Comment by moll** [comment]
Küsisin CitizenOSi käest, kas vana eventi saab läbi API muuta. Kui saab, saan veerandiga UI info parandamiseks lisada ja selle läbi ka tulevikus sellised mured lahendada. Kui ei saa, peab Mikk andmebaasist otse muutma.

**Comment by moll** [comment]
Ilmari poolt tehtud.
