### ISSUE TITLE
Tõlked üle käia

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#52]
Nt:
DEADLINE_EXPLANATION
VOTE_DEADLINE_EXPLANATION
#14 

https://docs.google.com/spreadsheets/d/1JKPUNp8Y_8Aigq7eGJXtWT6nZFhd31k2Ht3AjC-i-Q8/edit#gid=0

**Comment by moll** [comment]
Tõlkevõtmed tuleks kunagi paremini ümber nimetada, kuid praegu selgituseks:
DEADLINE_EXPLANATION — Tähtaja tekst diskussiooni avalikustades.
VOTE_DEADLINE_EXPLANATION — Tähtaja tekst diskussiooni hääletama pannes.

**Comment by moll** [comment]
Sama ülesande ulatuses võiksin ka genereerida nimekirja fraasidest, mis päriselt kasutuses on ja eraldada tabelist ülearused read. Tundub, et vähemalt pooled read tabelis on ülearused.

**Comment by infokujur** [comment]
Jah, see tundub vajalik.

**Comment by moll** [comment]
Mitte-kasutatud fraasid tabelist teisele "Unused" lehele liigutatud. Alles jäi ca 150 fraasi ja kasutamata oli ca 200.

**Comment by infokujur** [comment]
Tegeleme jooksvalt.
