### ISSUE TITLE
Peale toetamist tekst kirjutada - kolmes keeles

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#53]
https://rahvaalgatus.ee/donated

**Comment by infokujur** [comment]
Lisada linnukesega - üldlisti - soovin regulaarset üelvaadet tegevustest ja annetustest.

**Comment by infokujur** [comment]
Mina kirjutan teksti ja siis @moll lahendab.

**Comment by moll** [comment]
Kui tahad mugavamalt teksti stiilida, võid ka Markdownis kirjutada.

**Comment by infokujur** [comment]
Tegeleme jooksvalt.
