### ISSUE TITLE
Algatuse vaate parendamine (Algatuse märkmed)

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#54]
**Algataja poolt**
- Tuua välja algataja kontaktid, mille kaudu ajakirjanikud allkirjastajad jt saavad vajadusel ühendust võtta
- Tuua välja, kui algatuse taga on mitmed organisatsioonid
- Logo või pildi lisamise võimalus
- Kampaanialehe / fb grupi linkimise võimalus

**Crowd-source**
- Seotud organisatsioonide ja kontaktisikute linkimise võimalus
- Seotud seadusandluse jm dokumentatsiooni (arengu- ja tegevuskavad) linkimise võimalus

#25 #34

**Comment by moll** [comment]
Lisame Citizeni algatuse tabelisse märkmete (notes) tulba, mida saame enamike ülemiste soovide jaoks kasutada.

**Comment by infokujur** [comment]
Lisan siia ka meediamonitooringu osa. St lingid ilmunud artiklitele jms tulevad meie enda meediamonitooringust aga ka crowd-sourcitult kasutajate poolt.

**Comment by moll** [comment]
Küljeriba paigutusest annaks ka veel nii graafiliselt kui informatsiooni osas optimeerida. Kohati tundub kirju, sest segamini on nii külastaja põhivalikud (allkirjasta ja märkmed), algataja valikud (muuda, saada riigikokku) kui ka lisavalikud mõlemale nagu jälgi ja jaga sotsmeedias. Ideed teretulnud.

**Comment by infokujur** [comment]
Suund on hea. Palun pea silmas, et menetlusvaatega teeme praegu veel tööd. Ehk mingi eraldi pesa on selle jaoks vaja. Sinna tuleb tn protsessi ülevaade, meedia ülevaade, faktikontroll jms Praegu valime metoodikat. Kui midagi selgub, siis annan kohe märku (sellel nädalal ei tule, aga enne jõule peaks asi konkreetsem olema).

**Comment by moll** [comment]
> Ehk mingi eraldi pesa on selle jaoks vaja.

Mõtled eraldi lehte või eraldi GitHub _issue_t? Kui lehte, siis kui disain ja parem kasutajakogemus ette näeb, muidugi. Paeguse menetlusinfo põhjal pole veel aga vaja.

Tahaksin ülal tehtud muudatused koos algataja märkmetega aga millalgi see nädal laivi lükata. On vastuväiteid? Tahaksid ise enne kuidagi testida või midagi muuta? Fraase veel korrigeerin ja viin tõlketabelisse.

**Comment by infokujur** [comment]
Jah, võid tehtu live panna.

Kui infot lisandub menetlusvaate kohta, siis teen eraldi issued. Seda tn on mitme jagu :).

**Comment by moll** [comment]
Laivis! "Loe edasi" efekt tuleb ka varsti.
