### ISSUE TITLE
Uue eakuse visuaali edasiarendus (menetlusprotses)

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#56]
Praegu näitab protsessi: ühisloome, allkirjade kogumine.

Peamiselt ootame Riigikogu OD API arenguid, et sellega seoses läbi mõelda.

https://github.com/riigikogu-kantselei/api/issues/5

**Comment by infokujur** [comment]
#19

**Comment by infokujur** [comment]
#66

**Comment by moll** [comment]
Kui Citizen lisab eventi tüüpide toe, saame seda ka UE jaoks kasutada.
https://github.com/rahvaalgatus/rahvaalgatus/issues/63
