### ISSUE TITLE
Algatuse menetlus lõpetati - märkida lõpetatuks 10.10.2017

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#60]
https://rahvaalgatus.ee/initiatives/84b1d496-1037-4c7b-b7f3-b2e1ca6b4781/events
Aita Linnahalli seinamaaling lõpuni viia ja säilitada

**Comment by moll** [comment]
Tehtud.

Menetlusinfos küll aga tundub, et algatus lõpetati enne kui ta menetlusse läks. Kas midagi kuupäevadega tagurpidi?
