### ISSUE TITLE
Kuupäev vale (menetlusse võeti kuu aega varem, kui märgitud)

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#62]
Menetlusse võeti 26.09.2017 mitte 26.10.2017. Vaja parandada.

https://rahvaalgatus.ee/initiatives/84b1d496-1037-4c7b-b7f3-b2e1ca6b4781

Sama info ka siin:
https://www.riigikogu.ee/tutvustus-ja-ajalugu/raakige-kaasa/esitage-kollektiivne-poordumine/riigikogule-esitatud-kollektiivsed-poordumised/

**Comment by infokujur** [comment]
Siin sama lugu:
https://rahvaalgatus.ee/initiatives/6b8e7472-897a-430f-955a-0726f3c717a5

Peab olema, et menetlusse võeti 12.09.2017 (praegu sama, mis eelmisel).

**Comment by moll** [comment]
Fiksitud. See oli väike bugi hoopis kuupäeva välja parsimises.

Parandasin seda käsitledes ka "Vastuskiri, menetlus lõpetatud" infokillu kuupäeva liigutades selle pealkirjas ettepoole. Nagu enne, seniks kuni CitizenOS toetab kuupäeva seadmist menetlusinfos, saame sellest mööda pannes kuupäeva "DD.MM.YYYY" või ISO formaadis "YYYY-MM-DD" pealkirja ette.
