### ISSUE TITLE
Menetlus lõpetatud kuupäeva näitamine

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#63]
@moll @tiblu Kas siin on mingisugust head varianti, kuidas seda teha?

**Comment by tiblu** [comment]
@moll Menetlus lõpetatud, siis läheb Teema "closed" staatusesse? Kui nii, siis "updatedAt" kuupäev on kattuv menetluse lõpetamisga.

**Comment by moll** [comment]
Kas me saame API kaudu updatedAt kuupäeva määrata? Teemad harva lähevad samal päeval "closed" staatusse, sest see töö on täna ju käsitsi ja tavaliselt paari päevase hilinemisega. Kokkuvõttes kahtlustan aga, et on riskantne sõltuda väljast, mille põhiotstarve on natuke teine kui ainult staatuse muutuse kellaaega hoida.

**Comment by tiblu** [comment]
"updatedAt" kuupäevas säilitatakse baasis suvalise välja muutmist antud real, seda ise määrata ei saa.

**Comment by moll** [comment]
Sel juhul ei saa me ju `updatedAt`-i kasutada. :)

**Comment by tiblu** [comment]
Et kindel olla - näidata tahaks siis "menetlus lõpetatud" kuupäevaks seda, millal Riigikogu lõpliku vastuse saatis? Ehk siis "menetlus lõpetatud" Riigikogu süsteemis, mitte meie süsteemis?

**Comment by moll** [comment]
Yep. Õigemini see kuupäev, millal menetlus seal lõpetatuks loeti, mitte isegi, millal Riigikogu sellest avalikkusele või meile teada andis.

**Comment by tiblu** [comment]
Kui me kunagi teeme ära selle RIS-ga integratsiooni, siis pole seda enam üldse vaja, et siis on juba kõik ajad õiged? Ise-enesest "menetlus lõpetatud" tähendab praegu ka viimase eventi kuupäeva?

**Comment by moll** [comment]
Sealt infosüsteemist tulnud staatuse muutuste kuupäeva võib vast usaldada, jep. Viimase "eventi" mudeli kuupäeva aga ma küll ei usaldaks. Keegi ei keela peale menetluse lõppu uudissõnumeid või edulugusid lisada. Muidugi eventi kuupäeva ei saa ju ka praegu API kaudu määrata. :P See kuluks ka ära, sest hetkel on sellist workaroundi vaja: https://github.com/rahvaalgatus/rahvaalgatus/blob/0f2f02bdf8686bed1f5e7e774650a6c454bcda52/controllers/initiatives/events_controller.js#L58

**Comment by tiblu** [comment]
Mõttekoht - kas teha "events" tabelisse eraldi väli `publishedAt` (vms) või kasutada `createdAt`. Ainuke argument minu peaks `publishedAt` poolt ja `createdAt` vastu on, et `createdAt` on meie ORMi süsteemne väli kus salvestatakse baasis iga rea loomise hetke, samuti on `updatedAt` viimane uuendamine ehk siis ühtsus (en: consistency) kõigi tabelite vahel. Küsimus on, et kas `createdAt` väljal praegusel kujul on mingi väärtus või võime lasta seda uuendada...

**Comment by tiblu** [comment]
CitizenOS API needs an update:

* New fields:
    * `createdAt` (or similar) that can be modified via API
    * `eventType` - free text, partner classificator
* GET /topics/:topicId - include=events - ideally also provide in what detail you want the event object.

**Comment by moll** [comment]
Menetluse lõpukuupäeva saab nüüd adminliidese kaudu lisada ja seda kuvatakse algatuse juures: https://rahvaalgatus.ee/initiatives/1f821c9e-1b93-4ef5-947f-fe0be45855c5#initiative-events.
