### ISSUE TITLE
Värskendada stiile "Abi" lehel

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#64]
Rahvaalgatuse sait sai ammu mõned stiilimuudatuse loetavuse parandamiseks (fondi suurus, reavahede suurus jm). Need tuleks ka "Abi" (http://help.rahvaalgatus.ee/abi) lehe stiilifaili üle kanda.

**Comment by moll** [comment]
@infokujur mõtleb veel, kuidas ja mida Abi alamlehtedega ette võtta.

**Comment by infokujur** [comment]
Midagi ei võta ette. Lahendame läbi taggide alamenüü.

**Comment by infokujur** [comment]
Rahvaalgatuse stiiliraamatut uuendatakse ja sealt UId kohendada vastavalt.

**Comment by moll** [comment]
Eraldi domeenil olev abileht on tänaseks täiesti kinni pandud, nii et pole stiile, mida uuendada. :)
