### ISSUE TITLE
process visualization

### ISSUE THREAD

**Issue by RRisto** [rahvaalgatus/rahvaalgatus#66]
We made example visualisation of process: http://sidh2017.ut.ee/2017/11/11/what-does-the-vox-say/ if you have ideas how to use it (or what else to visualize) let us know. For more automatic visualisation it would be nice to get the data in some kind of machine readable format. @madisvalk @maritsir @Liisipark  @infokujur

**Comment by maritsir** [comment]
I improved a bit the process model viz for an individual case, which we showed at the blog (not design wise, but principles wise).
So if we have the process model shown for each process: 
![screen shot 2017-11-13 at 14 40 48](https://user-images.githubusercontent.com/26341300/32721677-b8643382-c880-11e7-82fb-1591e113c723.png)

What should be seen:
1. What is the initiative?
2. Is the process finished or not?
3. Which state is the process in?
4. When is the next event going to happen?
5. When did the previous events happen? 

Check out this link with three examples of processes in three different stages with the viz for these principles: https://infogram.com/rahvahaaletus-1g0gmj7n4z53m1q

1. Initiative info: Text (it could be a hyperlink which leads to a full project description)
2. Finished or not: colour coded - red indicates the end of the process, if a red dot is not on the picture, the process is still running.
3.  State of the process: grayscale coded - unfinished part of the process is gray, rest colorful
4. Next event: time - countdown
5. Previous events: hover effect with the dates of the events on the green dots

Also number of signatures and the name of commission give valuable information (text+symbol).

Additionally could be added the information of the length of the total process and how long is it till the very end (number of days till 6 months deadline is over).

**Comment by maritsir** [comment]
A separate timeline or list could include all the relevant documents (as you have it now on the website. We would suggest to make it either collapsable or like we did in the timeline that there is the headline of the document, date, couple of sentences summarising it and then a link to the full document. This would be plenty of information. Visually it is important to not to have all the document text just copy-pasted to the website - it is too much detail for a quick glimpse. It needs aggregation.
Said that, we did not figure out how to make the summaries automatic. Liisi just read the documents and wrote these 1-sentence summaries. The same applies to the summary of the final outcome.

**Comment by tiblu** [comment]
I like the idea of visualizing the process.
I think we should figure out what exactly do you want to show, what the graphic will look like.
Then we will figure out if and what data we can get to support generation of the graphic.

**Comment by infokujur** [comment]
@moll tegleb #160 edasi ja võtab siit ideid kaasa enne sulgemist.

**Comment by moll** [comment]
@RRisto, @maritsir, I sketched up a visualization for the initiative phases and I'd be glad if you could take a look and perhaps give some feedback. I briefly described it in https://github.com/rahvaalgatus/rahvaalgatus/issues/156#issuecomment-507239552. It's live in the staging environment — https://next.rahvaalgatus.ee/initiatives/11ad2c5e-01a8-4572-90f2-95e7e1d9f3e2 — where you can play with initiatives using credentials from https://github.com/rahvaalgatus/rahvaalgatus#accounts.

I'll also close this issue and let's carry on in https://github.com/rahvaalgatus/rahvaalgatus/issues/156.
