### ISSUE TITLE
FB jagamisele uus pilt - UV949

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#67]
Selline soovitus ühelt kampaaniatajalt, et soovitavad fb-s automaatset 
pilti vähema tekstiga panna. Kas nt jätta sinna ainult 
"Rahvaalgatus.ee-s on üks äge algatus!" või midagi muud.

**Comment by moll** [comment]
Kõne all olev algatus: https://rahvaalgatus.ee/initiatives/e05abc15-5e49-4205-bfb3-520ed6caf057
Algatuse Facebooki eelvaade: https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Frahvaalgatus.ee%2Finitiatives%2Fe05abc15-5e49-4205-bfb3-520ed6caf057
Kampaania algataja screenshot: https://rahvaalgatus.uservoice.com/assets/192651961/H_iva.JPG

Just väga palju teksti seal ei ole. Eelvaate "description" kastist näeb vaid lauset-paari ning needki võtab Facebook ise, kuna meil targemat kokkuvõtte feature'it ei ole.

**Comment by tiblu** [comment]
LAHENDUS1: Hetkel võtta RAA.ee näidataval logol teha tekst väiksemaks, et ta sisu ei vallutaks.
LAHENDUS2: KUI me seda teha tahame, et saaks pilti muuta ja lisada siis:
* UI muudatused RAA ja CitizenOS poolelt - lubada uploadi, näidata, kustutada, raporteerida.
* CitizenOS API - pildi raporteerimine

Ehk siis omajagu tööd, pole kindel kas hetkel saada olevate ressurssidega piisavalt suur tulu.

**Comment by infokujur** [comment]
Tegeleme edasi, kui lubame algatajal pilti üles laadida. Siis näitame seda.
