### ISSUE TITLE
Palun uuenda .md faile

### ISSUE THREAD

**Issue by ilmakodanik** [rahvaalgatus/rahvaalgatus#68]
Uuendasime pikki sisutekste, uus kuupäev failinimes.
https://drive.google.com/drive/folders/0Bzyw2X6-AWxmMW9YaVBnbTczVTA

**Comment by moll** [comment]
Uuendatud. Viska pilk peale @ https://rahvaalgatus.ee/about ja https://rahvaalgatus.ee/donate. Muid dokke polnud, eks? Toetajate list all on jätkuvalt kaks nime?

Oli mõni spetsiifiline põhjus, miks valisite kuupäevadega failinimed vanade eemaldamise asemel? :) Google Drive'is ju ka versioneerimine, nii et kui vajadusel vaja vana uurida, saate selle sama nime alt kätte.
