### ISSUE TITLE
Menetlusvaate banneri uuendamine

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#70]
Üks nupp vähem. Ühel nupul teine tekst ja link küljes.
https://docs.google.com/drawings/d/1zVNs0KZdYCdsfja_V8Mgi2jqGPNhwKQOAklw7g5ngOU/edit

@moll - kas meil on kuskil sõned/.md failid ka selle kohta? Ma neid tabelist ja kaustast ei leidnud.

Tabel: https://docs.google.com/spreadsheets/d/1JKPUNp8Y_8Aigq7eGJXtWT6nZFhd31k2Ht3AjC-i-Q8/edit#gid=0
Kaust: https://drive.google.com/drive/folders/0Bzyw2X6-AWxmMW9YaVBnbTczVTA

**Comment by moll** [comment]
Need fraasid jäid tollal vaid Eesti keelde ja otse lähtekoodi. Viisin nad tabelisse, et saaksite neid soovi järgi tõlkida. Tekstid `PARLIAMENT_BANNER_` prefiksiga.

Lükkasin ka muudatused juba üles (nt https://rahvaalgatus.ee/initiatives/db3d09d6-18ba-467a-9527-6bfc0605aab9). Anna teada, kui tekstid kohandatud. Nende uuendus on minuti küsimus.

**Comment by infokujur** [comment]
@ilmakodanik Palun uuenda ja siis @moll uuendab.
