### ISSUE TITLE
"Topic deadline must be in the future" viga parlamenti saates

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#74]
@tiblu'le ja @ilmartyrk'ile teada antud.

Toimus algatusega https://rahvaalgatus.ee/initiatives/623d03dd-512e-4fe2-8a8b-11671779770b.

**Comment by moll** [comment]
Sama viga esines 19. aprillil, kus ta vist Citizeni poolt ka parandati. Kuidas see nüüd uuesti ilmnes?

**Comment by infokujur** [comment]
Kui olete lahendanud, siis on vaja algatajale ka kohe märku anda. Ma saatsin talle küll selle teema lingi, kuid pange, siis @ilmakodanik peale ja ta võtab ühendust. Algataja kirjutas rahvaalgatus.ee facebooki.

**Comment by moll** [comment]
@infokujur ja @ilmakodanik: @ilmartyrk jälitas vea Citizeni valideerimisteni ja andis teatepulga @tiblu'le üle. @tiblu spekuleerib, et jõuab alles esmaspäeval sellega edasi tegeleda.

**Comment by tiblu** [comment]
@moll @infokujur Parandatud, bugi tekkis koodi refaktoorimisega ja ei jäänud testis vahele kuna testi kood oli vildakas.

**Comment by moll** [comment]
Aitäh! @infokujur, @ilmakodanik: Andsite algatajale teada?
