### ISSUE TITLE
Menetlusvaatesse lisada jätkuprotsessid ministeeriumides ja teistes asjaomastes institutsioonides

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#76]
#19

**Comment by moll** [comment]
Sama saatus, mis https://github.com/rahvaalgatus/rahvaalgatus/issues/19, kuid läheb wishlisti, sest on pisut konkreetsem. :)

**Comment by infokujur** [comment]
Sellega tegeleme juba. Võtan listist maha, sest on dublikaat.
