### ISSUE TITLE
Menetletud algatuse kommenteerimise lubamine

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#77]
Kommentaaridesse saab lisada järelkaja nt artikleid jms kui tegelikult protsess veel käib. 
Mõni algatus käib veel ministeeriumis edasi.

**Comment by infokujur** [comment]
@moll Kui see on kiire fix, siis palun tee ära, kui pikem ja süsteemsem, siis jätame groomingusse.

**Comment by moll** [comment]
Vaatan täna, kas Citizen ikka toetas kommenteerimist hilises faasis. Tahad kommentaare ka "menetlus" lehe alla?

**Comment by infokujur** [comment]
Kui kiirelt võimalik, siis jah, pusida ei ole vaja, sest menetlusvaade nõuab süsteemselt läbi mõtlemist. Aga kommentaaridel võiks seal tulevikus koht ka olla.

**Comment by infokujur** [comment]
Konkreetne juhtum (Hoolduskindlustus on parlamendis menetletud, kuid edasi läinud ministeeriumi ja seal protsess kestab):
Uudis kommentaariumi lisada, kui see võimalikuks saab:
04.04 - Vikerraadio Reporteritunnis (https://podtail.com/podcast/reporteritund-vikerraadio-err/reporteritund-hoolekandesusteemi-kaasajastamine/) oli teemaks hoolekandesüsteemi kaasajastamine. Stuudios olid külas on EPIKoja tegevjuht  Anneli Habicht, Eesti Liikumispuudega Inimeste Liidu tegevjuht Lili Tiri, Eesti Vaimupuudega Inimeste Tugiliidu juhataja Agne Raudmees ja Sotsiaalministeeriumi asekantsler Rait Kuuse.

**Comment by moll** [comment]
Võimaldasin menetluses olevate algatuste kommenteerimise ning lisasin kommentaarid ka menetluse lehele. 

@ilmakodanik, lisad @infokujur-i kommentaari ülal ise algatusele?

**Comment by infokujur** [comment]
@moll kommentaar nüüd lisatud.
