### ISSUE TITLE
Telli teavitus - otse Mailchimpi

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#78]

**Comment by moll** [comment]
Nagu räägitud sai, algatuste ja meiliaadresside sidumiseks on kaks varianti:
1. Iga algatuse kohta uus MailChimpi list.
2. Üks list ning igale algatusele oma grupp (https://mailchimp.com/help/getting-started-with-groups/).

Plussid-miinused:
- Eraldi listide puhul on väiksem tõenäosus, et inimene peatab kõikide teavituste tellimise. Praeguste meilide lõpus olev link "Kui Sa ei soovi enam teavitusi selle algatuse kohta saada, siis palun kliki siin" peatab tegelikult teavitused _kõikide_ algatuste kohta.
- Gruppide puhul on vähem administratiivtööd. Tundub, et mitmed konfiparameetrid ja saatja detailid on MailChimpil listipõhiselt.
- Gruppide variant oleks kuutasuliste pakkettide puhul odavam. "Pay as you go" puhul pole vist vahet.
- Gruppide kasutamine lubab inimesel oma teavitusi hallata ühelt lehelt. Kahjuks on seal lehel küll vaid algatuste pealkirjad, linke mitte.

Hetkel läheb käiku gruppide variant, sest kohandades jaluse _unsubscribe_ lingi teksti ning lisada sinna link teavituste haldamiseks (https://mailchimp.com/help/add-an-update-profile-link/), saab gruppide kasutamise peamise probleemi lahendatud. Jaluse täiendamise töö jätan sulle, @infokujur. :)

Seni on teavitusteks ka gruppe kasutatud. Pooled "Soovin olla kursis algatustega" pealkirja all, teised igaüks eraldi algatuse nimelise pealkirjaga. Need tasuks üks hetk ka kõik "Soovin olla kursis algatustega" gruppi (nime võib muuta) liigutada. Praeguses vormis tekitavad nad haldamise lehele topelt peakirju.

**Comment by moll** [comment]
@infokujur, gruppide-põhine variant katsetusteks https://next.rahvaalgatus.ee/initiatives/44ffb1ef-5b80-4174-9afe-cec3e29a864e lehel ülal. Võid algatusi juurde teha.

Tehniliselt tehakse siis iga algatuse esimese teavituse tellides uus Mailchimpi samanimeline alamgrupp. Stagingu jaoks näiteks https://us1.admin.mailchimp.com/lists/dashboard/groups?id=1249097 gruppi. Seos grupi id ja algatuse id vahel salvestatakse lokaalsesse andmebaasi. Mailchimpi lehelt võib pea- või alamgruppide nimesid muuta, see seost ei lõhu.

Peale esimese teavituse tellimist saadab Mailchimp inimesele kinnituse. Järgnevate algatuste jälgimise puhul mitte. Ei tea, kas see on optimaalne, aga nõnda ta vaikimisi toimib, sest nende jaoks on tegu on alati sama meililoendiga. Teavitusi saab tellida vaid avalike diskussioonide/algatuste kohta. See väldib kellegi privaatse diskussiooni pealkirja lekkimist.

Mailchimp nõuab ka, et iga grupp oleks unikaalse pealkirjaga. Olukorra, kus keegi peaks tegema juba olemasoleva nimega *avaliku* algatuse, lahendasin grupi nime lõppu pandava kuupäevaga. Nagu enne ütlesin, saame seda nime käsitsi kohandada.

Nüüd jääb vaid olemasolevad alamgrupid kõik ühte gruppi liigutada ning gruppide ja algatuste vahelised seosed luua. Viimase teen ise, aga kas esimese korraldad ise või jätad mulle? + jaluse tekst nagu eelmises kommentaaris kirjutasin.

**Comment by moll** [comment]
Ahjaa, ning peale teavituse tellimist kuvatud teksti saad muuta tõlketabelis `SUBSCRIBED` võtme alt.

**Comment by infokujur** [comment]
Aitäh! Hea algus. 
@moll Kas ma pean gruppidesse liigutamise enne tegema, kui seosed?
Kas see seoste tegemine on läbi klikkimine või käib see Sul automaatselt?

**Comment by moll** [comment]
Mõte oli väike skript kirjutada, mis võtab Mailchimip grupid ja algatused ning üritab pealkirjade järgi seosed luua. Kui mõni pealkiri erineb, klapitan käsitsi.

Ühte gruppi liigutamine ("Soovin olla kursis algatustega") tuleks teha enne skripti jooksutamist, sest kahtlustan, et liigutamine saab olema uue tegemine ja vana kustutamine, ja see muudab id-sid.

**Comment by infokujur** [comment]
@moll - jätan Sulle selle esimese liigutuse ka :).
Hea, et see nüüd korras.

**Comment by moll** [comment]
Laivis! Eksiteerinud listigruppide liikmed viisin kõik "Soovin teavitusi..." alamgruppideks.

Ära's unusta meilijaluse korrigeerimist, sest üksainus "unsubscribe" vajutus võtab inimese kõigist algatustest maha ja see pole tõenäoliselt see, mida keegi ootab. ;)

**Comment by infokujur** [comment]
Ok - see tähedab siis seda, et kõik kes on liitunud pärast 28.10.2018 on automaatselt liigutatud?

**Comment by moll** [comment]
Yep! Kui mõni grupp puudu, kuhu tahad tabelist inimesi liigutada, siis viska oma meiliaadress Rahvaalgatuse saidil sisse ja grupp ning seos luuakse ära. Praegu paremat viisi gruppide tekkimiseks pole. :)
