### ISSUE TITLE
uuseakus.rahvaalgatus.ee esilehele uus video 

### ISSUE THREAD

**Issue by teelepehk** [rahvaalgatus/rahvaalgatus#79]
See video praeguse asemele panna (sest praegune on 2017. aasta kohta): http://joonmeedia.ee/uuseakus/telekool_piret_krumm/1-2_telekool_piret_krumm_esimene_video_2017-03-15.mp4

**Comment by moll** [comment]
On too uus klipp teil YouTube'is Koostöö Kogu konto (https://www.youtube.com/channel/UC4DE9FdPXuEpI2DwMGuZAsQ) all ka? Uue Eakuse lehe videomängija tuleb YouTube'ist.

**Comment by infokujur** [comment]
Jaa, on küll: https://www.youtube.com/watch?v=B3ZbPIR42P4&index=2&list=PLP7BuGofliXQZLevKaYvfiOqVoL_1P2jL

**Comment by moll** [comment]
Andestust, jäi vahepeal kahe silma vahele. Nüüd üleval.
