### ISSUE TITLE
Kommentaariumi arendused

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#8]
- Uuest kommentaarist teavitus
- Ebasobivast kommentaarist teatamine (sellest teavitus modele)
- Modereerimiskahtlusega kommentaari autorile teavituse saatmine (manuaalne - mode küsib, kas jääb oma seisukoha juurde või mitte)
- Kui ebasobivast kommentaarist on teatatud x korda, siis automaatselt varjata kommentaar märkusega modereerimisel
- Juba läbi modereerimise protsessi käinud kommentaar enam automaatselt peitu ei lähe (st protsess ei käivitu)

**Comment by moll** [comment]
Kommentaaride raporteerimine olevat CitizenOSil tehtud. API dokk on Citizeni Trellos.
Ootab su töösse andmist, @infokujur. ;)

**Comment by moll** [comment]
Raporteerimisega seotud _issue_ on https://github.com/rahvaalgatus/rahvaalgatus/issues/51.

**Comment by moll** [comment]
Algataja või tavalise kasutaja kommentaariumi jälgimine jääb @tiblu uurida. @infokujur'i teavituse saab hetkel Rahvaalgatuse pool teha ilma Citizeni kinnituseta.

**Comment by infokujur** [comment]
Uuest kommentaarist on teavitus olemas.

**Comment by moll** [comment]
Teavitust veel ei ole, aga https://github.com/rahvaalgatus/rahvaalgatus/issues/177 käsitleb seda.

**Comment by moll** [comment]
Nimetan _issue_ tagasi "Kommentaariumi arendused"-ks, sest muidu on hiljem raske käesolevat üles leida. Kuna aga siit jäi vaid teavituste tegemine ja see on #177 -s, siis võib sulgeda.
