### ISSUE TITLE
Rahvaalgatus.ee esitlus esilehele linkida koos üldise uudiskirja tellimisega

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#80]
Vaja veel mõelda kuidas täpselt Call to action tuleb.

https://docs.google.com/presentation/d/1xkp4akP5wbQS8cPHxGPLjNY-S5yf8NCIeKfmuK6jgpc/edit#slide=id.g212033cc5a_1_20

**Comment by moll** [comment]
Olete välja mõelnud?

**Comment by moll** [comment]
Kõikide algatuste tellimist me praeguse gruppide setupi järgi teha ei saa, sest grupid luuakse alles esimese tellimuse teavitamise hetkel. "Kõikide tellimine" tuleb kuidagi eraldi märkida. Saame teha uue grupi pealkirjaga "Kõikide algatuste kohta". Teavitusi saates tuleb siis valida nii algatuse grupp kui ka "kõik algatused" grupp. "Kõik algatused" grupi võime teha nii  "Soovin teavitusi..." kategooriasse esimeseks kui ka teha eraldi kategooria. Samasse ülesse vist näeb parem Mailchimpi profiilil (see, kus inimene linnukesi hiljem panna saab) välja.

**Comment by infokujur** [comment]
Jah, selline variant katab vajaduse. Saagu grupp "Kõikide algatuste kohta" :). Lisame siis selle alati adressaatide hulka, kui teavitused välja lähevad.

**Comment by moll** [comment]
Lisasin lihtsa nupu ja väikese selgitusteksti esilehele: https://next.rahvaalgatus.ee. Kuidas tundub? Ajab hetkel asja ära?

Millalgi võiks algatuste jälgimise rohkem Rahvaalgatusega enda lehega siduda. Nagu https://github.com/rahvaalgatus/rahvaalgatus/issues/115 -s kirjeldasin, saaks tellitud teavitustega algatuste tuvastamise läbi ka häälte hoidmise vajadusest lahti. A la linnuke või kirjaikoonike vm nende algatuste ees, mida inimene jälgida soovib.

**Comment by infokujur** [comment]
Nii on praeguseks hea küll.

**Comment by moll** [comment]
Laivis.
