### ISSUE TITLE
Arutelu loojale "automaatkiri" järgmiste etappide ja tema vastutuse kohta 

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#81]
Et sellise ülesehitusega algatus ei liiguks allkirju koguma: https://rahvaalgatus.ee/initiatives/0f6d0892-5fd5-427c-a671-7523ad2ba344

**Comment by infokujur** [comment]
#14

**Comment by infokujur** [comment]
ning lõppenud arutelu jätkuks algatusena (autor ei pruugi teada, et ta peab ise nuppudele klikkima, et asi edasi liiguks): https://rahvaalgatus.ee/initiatives/21a35053-a2a9-4e6e-8982-a787446517ff

**Comment by moll** [comment]
Meil peaks minema tähtaja möödudes automaatselt inimesele meeldetuletuseks. Hetkel on lahtine, kuidas implementeerida. Käis läbi idee, et CitizenOS teeb HTTP päringu Rahvaalgatuse süsteemi, kui tähtaeg saabub.

**Comment by moll** [comment]
@infokujur, millise tekstiga meeldetuletuse algatajale saata võiksime? Tegin neli fraasi tõlketabelisse tekstinäidistega:
```
DISCUSSION_END_EMAIL_SUBJECT
DISCUSSION_END_EMAIL_BODY
SIGNING_END_EMAIL_SUBJECT
SIGNING_END_EMAIL_BODY
```

Mõned algatusega seotud muutujad (nagu pealkiri ja link) on saadaval. Kui tahame ka lõpukuupäeva jm, anna teada. Ehk peaks ka eristama allkirjastamise faasi lõppedes, kas algatus sai 1k allkirja kokku või mitte. Kui ka nii arvad, lisa veel paar fraase ja ühedan pärast koodis.

Praegu läheks meil vaid esimesel autorile. Kas tasuks saata kõikidele, keda algatuse autor ühisloomesse kutsunud? Laivi lükates, kas saadame ka tagantjärele vanadele algatustele või alustame puhtalt ja tuletame Rahvaalgatust vaid uutele algatustele meelde?

**Comment by infokujur** [comment]
**Tekstid sobivad.**

Ehk peaks ka eristama allkirjastamise faasi lõppedes, kas algatus sai 1k allkirja kokku või mitte. Kui ka nii arvad, lisa veel paar fraase ja ühedan pärast koodis.

**Jah. Praegune tekst käib selle kohta, kui 1k on kogutud.**

Praegu läheks meil vaid esimesel autorile. Kas tasuks saata kõikidele, keda algatuse autor ühisloomesse kutsunud?

**Saadame autorile.**
Laivi lükates, kas saadame ka tagantjärele vanadele algatustele või alustame puhtalt ja tuletame Rahvaalgatust vaid uutele algatustele meelde?
**Saadame kõigile, kelle kuupäev on kukkunud viimase 6 jooksul ja algatus ei ole vanem kui 1 aasta.**

**Comment by moll** [comment]
Lisasin algatuse edukuse eristamise.

Meilid ja subjektid on tabelis järgmiselt:

- `SIGNING_END_COMPLETE_EMAIL_SUBJECT` — Edukas algatus.
- `SIGNING_END_COMPLETE_EMAIL_BODY`
- `SIGNING_END_INCOMPLETE_EMAIL_SUBJECT` — Allkirju puudu.
- `SIGNING_END_INCOMPLETE_EMAIL_BODY`

**Comment by moll** [comment]
Saatmine ei ole veel laivis. See juhtub https://github.com/rahvaalgatus/rahvaalgatus/issues/172 raames.
