### ISSUE TITLE
Kaasautori kutse aktsepteerimine teise meiliaadressiga (või olemasoleva kontoga)

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#83]
Hetkel väidetavalt pakutakse uue CitizenOS konto loomist. Võiks pakkuda võimalust kutse aktsepteerimist sisselogitud kontoga, isegi kui selle meiliaadress ei ole sama, kuhu kutse saadetakse.

**Comment by tiblu** [comment]
@infokujur Ma ootaks, et mõtlete välja ideaalse voo ja siis me CitizenOS-i poolelt mõtleks rakendamisele.

**Comment by infokujur** [comment]
Probleem laheneb, kui läheme eID peale.
