### ISSUE TITLE
Lisada hea annetuste koguja logo ra.ee päisesse - kõige vasemasse serva

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#84]
Logod siin:
http://heakodanik.ee/emsli-logod/

**Comment by moll** [comment]
Vasemasse? Mitte paremale, kus "Uus Eakus" täna on? Peame vist logo jaoks vektorformaati ka paluma. Olgugi, et nende logod on läbipaistva taustaga, ei paista rohelise lilleõie ümbrune must tekst küll meie tumesiniselt välja.

**Comment by infokujur** [comment]
Tuli vektor. Jääb siis mustaga. Nii ta mulle anti.

[hea annetuste koguja.pdf](https://github.com/rahvaalgatus/rahvaalgatus/files/2175386/hea.annetuste.koguja.pdf)

**Comment by moll** [comment]
Lingitud.

> See on kvaliteedimärk

Keegi külastaja ka seda teab? :P Ma kahtlustan, et keegi ei tea ega saagi teada, sest miks peaks keegi tundmatuid ringe klikkima. :P

**Comment by infokujur** [comment]
Aitäh! Nad tegelevad ... Annan meie tagasiside edasi.

**Comment by moll** [comment]
Gotcha. Panen praegu _issue_ kinni, kuid uue info saabudes võib uuesti avada.
