### ISSUE TITLE
Algataja keskmine nimi on väikese tähega - vaja oleks suurega

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#85]
Vt nt siin: https://rahvaalgatus.ee/initiatives/d88fc139-21ae-456e-8426-68b3d7d1f0e5

**Comment by moll** [comment]
Jaanus peaks seda saama https://rahvaalgatus.ee/user lehelt ise muuta. Miks ta esialgu aga väikesega läks on küll kahtlane. Kas CitizenOS muudab inimeste nimesid, kui nad Id-kaardi või Mobiil-Id'ga sisse logivad, @tiblu?

**Comment by moll** [comment]
Kiikasin korra Citizeni kasutajate nimekirja ja mulle tundub, et kõik kolme ja enama nimelised on säherduselt väikesi tähti saanud. Pingin @tiblu-t. Kõlab nagu keegi nimetas produktsiooni andmebaasis inimesi ümber. ^_^

**Comment by tiblu** [comment]
@moll @infokujur ID-kaardi ja mobiil-ID autentimine ning allkirjastamine uuendavad baasis Kasutaja nime. See loogika sisaldas väga naiivset esi suurtähe algoritmi. Viga parandatud.

**Comment by moll** [comment]
Aitäh!
Kas olemasolevad nimed said ka parandatud? Miks nimesid korrigeerima peab? Kas Mobiil-Id'st tulevad nad ainult suurte tähtedega?

**Comment by tiblu** [comment]
Jah olemasolevad said parandatud.
Jah, Mobiil-ID ja ID kaardi puhul tagastab DigiDocService nime läbiva suurtähega. Nimeuuendus aitab ka nimemuudatuse puhul, aga peamine põhjus ikka esimene.

**Comment by moll** [comment]
Oki @ uued külastajad, aga kas ja miks olemasolevad nimed üle kirjutatakse? See on natuke ootamatu, sest kasutajaprofiil, olgugi, et elementaarne, lubab meil praegu ka inimestel ise nimi määrata. @infokujur?

**Comment by infokujur** [comment]
Meilt seda nõuet ei ole tulnud, et peaks midagi üle kirjutama.

**Comment by moll** [comment]
@infokujur, ega kõik Citizeni feature'id vast meie poolt ei tellitagi. :) Küsimus küll õhus, kas see on hea feature kõigile, meile või Citizenile.

**Comment by tiblu** [comment]
@moll @infokujur See "feature" on kõigile.
Nüüd kus sa selle küsimuse tõstatasid, tundub ka mulle endale kummaline see nime uuendamine.
Küllap ma mõtlesin nimemuudatustega kaasas käia, kuid päeva lõpus rikub see teisest otsast kasutajakogemust ega anna sisuliselt midagi juurde. Allkirja puhul on lõpuks oluline isikukood.

https://github.com/citizenos/citizenos-api/issues/11
