### ISSUE TITLE
Algatusse kopeeritud pilt võib takistada hääletusse saatmist

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#86]
30. juunil 2018 ilmnes viga https://rahvaalgatus.ee/initiatives/83beeb14-b161-4708-beb4-7e578c7911a1 algatusega, mis oli kuidagi korjanud endasse base64 kodeeritud pildi. Pilt takistas hiljem inimesel algatust hääletusse saatmast. @tiblu leidis vea CitizenOSi koodist ja tegi selle jaoks https://github.com/citizenos/citizenos-api/issues/12.

**Comment by tiblu** [comment]
@moll Märkus selle vea kohta - viga ainult siis kui pildid lisatakse väljaspool tekstiredaktori pildi lisamise funktsionaalsust. Tehnilisemalt - kui pildid pole viited vaid on Base64-na. Kuidas need Base64 pildid tavakasutajal tekivad on hetkel veel lahtine.

**Comment by moll** [comment]
Arutelu faasis Etherpadi sees paistis ta kenasti välja vist, eks? Lihtsalt hääletusse saatmise hetkel MS Wordi formaati genereerides läks katki? Eks ta vast copy-paste'iga tuli ning Etherpad paste'tud HTMLi koos sellise pildiga ilmselt ka aktsepteeris. Kui nii, siis peab vast ütlema, et Etherpadi vaatenurgast kõik okei.

**Comment by tiblu** [comment]
@moll Jah, välja näitas korrektselt, katki läks alles DOCX genereerimisel.

**Comment by ilmartyrk** [comment]
Fixed https://github.com/citizenos/citizenos-api/commit/90455b0d22c7b75982b111b7adef38b3e3a4c537

**Comment by moll** [comment]
Danke!
