### ISSUE TITLE
Vanematel algatustel on ajajoon kohati segane - dokumendid ei ole järjestuses tekkimise vaid sisestamise järgi

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#87]
Nt kanepi algatus: https://rahvaalgatus.ee/initiatives/cde86956-ae36-4f04-b1d0-38277147512b

Vaja on teha nii, et kuupäevad, mis on pealkirjas on need, mille järgi on menetluskäik ajajoonel reastatud.
Praegu on osad dokumendi kuupäevade järgi ajajoonel, teised sisestamise järgi.

**Comment by infokujur** [comment]
Tegelikult oleks ikka väga hea, kui seda menetlusvaade sisu saaks admin kuidagi parandada @tiblu. Overkill on seda teha läbi arendustiimi.

**Comment by moll** [comment]
Njaa, see häkk, mida kuupäeva sisestamiseks meie poolele tegin, tahab, et kuupäev oleks pealkirja alguses. Mitmeil tundub kuupäev olevat kas keskel või lõpus.

@tiblu, mis seis täna events-ide muutmisega on? Saab muuta ja kas ka createdAt kuupäeva sisestada?

**Comment by moll** [comment]
Fiksisin algatuse menetlusinfo pealkirjad, nii et meie süsteem loeks neist õiged kuupäevad välja. "Õigeks" lahenduseks aga ootab https://github.com/rahvaalgatus/rahvaalgatus/issues/63.
