### ISSUE TITLE
Menetlus lõpetatud 13.06.2018

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#88]
Vaja panna menetlus lõpetatud: https://rahvaalgatus.ee/initiatives/623d03dd-512e-4fe2-8a8b-11671779770b

**Comment by moll** [comment]
Panin "menetletud" staatusse. Lõpukuupäev aga jätkuvalt vaid "Menetluses" lehel näha kuniks Citizen staatuse muutmise kuupäeva mäletama hakkab.
