### ISSUE TITLE
Reprole uus värske logo

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#89]
@moll Kui mulle pääsud annad, siis tegelen sellise vajaliku tilu-liluga ise.

![29571363_1030491613774940_483020280537254398_n](https://user-images.githubusercontent.com/12999094/42372738-bd40f940-811b-11e8-829c-3cf73e4f565d.png)

**Comment by infokujur** [comment]
Jaa, nii mõtlen. Ei pääse ligi.

**Comment by moll** [comment]
Oih, panin "Owner" ning GitHub küsis parooliga kinnitust, kuid tuleb välja, et kinnituse vältel unustas ta ka mu soovi ära. Katse kaks. Seekord ka näitab su nime juures "Owner" staatust. Palun proovi uuesti.

**Comment by infokujur** [comment]
All good!
