### ISSUE TITLE
Palun uuenda about teksti lehele - täpsemad isikuandmete töötlemise kirjeldused

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#90]
https://drive.google.com/open?id=0Bzyw2X6-AWxmaWxnSVpBbG1VbW8

Tekst pikkade sisutekstide kaustas uuendatud.

**Comment by moll** [comment]
Uuendasin eestikeelset "Platvormist" teksti. Teised paistsid puutumata.
Teksti lõpus oli ka pool vanast lingist alles. Fiksisin.
