### ISSUE TITLE
Arvamusfestivali logo 2035 algatuse juurde

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#91]
https://rahvaalgatus.ee/initiatives/390151d0-8913-4151-91b3-4127f1a2ef06

Nagu on PÕXIT-i algatusel
https://rahvaalgatus.ee/initiatives/e05abc15-5e49-4205-bfb3-520ed6caf057

**Comment by moll** [comment]
Lisatud.
