### ISSUE TITLE
#kestame rahvaalgatus.ee päisesse

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#92]
Päisesse Uue eakuse kõrvale, lingituna kestame.rahvaalgatus.ee lehele.

**Comment by moll** [comment]
On teil mingi muu logo ka peale tag'i #kuidasmekestame, @katjadanilova?

**Comment by katjadanilova** [comment]
muud logo ei ole ja tellija plaani järgi ei tule ka.

**Comment by moll** [comment]
Natukese hilinemisega sai logo päisesse lisatud. :innocent:
Päis hakkab meil RA-s pisut kirjuks muutuma juba. Äkki peaks jalusesse või lehe sisusse sellised alamlehtede viited viima...
