### ISSUE TITLE
Palun muuda kuupäeva menetluse juures

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#96]
https://rahvaalgatus.ee/initiatives/e05abc15-5e49-4205-bfb3-520ed6caf057/events

On 11.10.2018
Riigikogu majanduskomisjoni istungi protokoll nr 215 

Vaja oleks 11.09.2018
Riigikogu majanduskomisjoni istungi protokoll nr 215

**Comment by moll** [comment]
Tehtud!
