### ISSUE TITLE
Vaja viia algatus "Vähendame palgalõhe Meie kõigi võrdse tuleviku nimel" menetlusvaatesse

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/rahvaalgatus#98]
https://rahvaalgatus.ee/initiatives/4cd98a74-3f69-4369-886f-893e7353a7da

Seda menetletakse märgukirjana. Teen sellekohase kande, kui annad mulle ka menetlusinfo ligipääsu.
Hääli ei saada.

**Comment by infokujur** [comment]
@moll - Sellega oleks vaja tegeleda, sest oodatakse teateid ning vaja oleks need välja saata ja menetlusvaadet Riigikogu juhatuse otsusega uuendada. Ehk mulle ligipääs, aga allkirju ei saada, kuna ei läinud kollektiivse pöördumisena (sest kasutame allkirju ainult selleks, milleks nad on kogutud).

**Comment by moll** [comment]
Oih, andestust. Jäi kahe silma vahele. Ligipäästetud!
