### ISSUE TITLE
Kuvada peale allkirjastamist, kas tegu on kordushäälega

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/rahvaalgatus#99]
Korduvalt on inimestel meelest läinud, et nad on mõnda algatust juba toetanud. Kuna toetajate number kordushääle puhul ei tõuse, jääb mulje, nagu hääl ei läinud läbi. Võiksime peale allkirjastamist kuvada, kas tegu oli uue või kordushäälega.

Märkasin ka, et sellekohane märge on koodis juba poolteist aastat istunud. :P 
https://github.com/rahvaalgatus/rahvaalgatus/blob/7532066fb6c1a686148460f8dc3ae2b1015afc10/controllers/initiatives_controller.js#L360-L369

**Comment by moll** [comment]
Vajab Citizeni tuge. Teil seda vist veel pole, eks, @tiblu?

**Comment by tiblu** [comment]
@moll Ei. Kas sul on mingi response mida sooviksid sel puhul saada?

**Comment by moll** [comment]
Tehtud. Kuvame tänufraasi asemel `THANKS_FOR_SIGNING_AGAIN` fraasi, kui tegu on korduva toetusallkirjaga. Testida saab nt testalgatusel: https://rahvaalgatus.ee/initiatives/a3adaaaa-207e-4816-9479-c7f61e3e33da. Allkirja tühistamise puhul ka enam ei tänata, vaid informeeritakse tühistamisest.

**Comment by moll** [comment]
Natuke aega tagasi selgus, et korduvallkirja tuvastamine ei vasta täpselt Citizeni käitumisele. Nimelt tekitab Citizen vahel Mobiil-Id-ga allkirjastades mitu sissekannet ja need näivad meile nagu varasemad allkirjad. Teksti kuvamise heuristikat tasub täiendada vbla ka ajalise piiranguga — kui varasem allkiri on pärit viimase minut sees, siis on tegu Citizeni kalaga.

Seotud https://github.com/citizenos/citizenos-api/issues/69.

**Comment by moll** [comment]
Korduva allkirja tuvastamine on täiendatud. Seekord võtab arvesse vaid enam kui 15 sekundit tagasi tehtud allkirju.
